### ISSUE TITLE
 java.util.zip.DataFormatException: incorrect header check

### ISSUE THREAD

**Issue by chengdedeng** [apache/rocketmq#1055]
rocketmq version:4.3.2
error information in the console:

> java.lang.NullPointerException
        at org.apache.rocketmq.broker.transaction.queue.TransactionalMessageBridge.getMessage(TransactionalMessageBridge.java:136)
        at org.apache.rocketmq.broker.transaction.queue.TransactionalMessageBridge.getHalfMessage(TransactionalMessageBridge.java:108)
        at org.apache.rocketmq.broker.transaction.queue.TransactionalMessageServiceImpl.pullHalfMsg(TransactionalMessageServiceImpl.java:379)
        at org.apache.rocketmq.broker.transaction.queue.TransactionalMessageServiceImpl.getHalfMsg(TransactionalMessageServiceImpl.java:444)
        at org.apache.rocketmq.broker.transaction.queue.TransactionalMessageServiceImpl.check(TransactionalMessageServiceImpl.java:164)
        at org.apache.rocketmq.broker.transaction.TransactionalMessageCheckService.onWaitEnd(TransactionalMessageCheckService.java:76)
        at org.apache.rocketmq.common.ServiceThread.waitForRunning(ServiceThread.java:121)
        at org.apache.rocketmq.broker.transaction.TransactionalMessageCheckService.run(TransactionalMessageCheckService.java:65)
        at java.lang.Thread.run(Thread.java:748)

I found issue at uncompress of body in the MessageDecoder.java by debug broker code，get error info:

> java.util.zip.DataFormatException: incorrect header check

**Comment by chengdedeng** [comment]
I found abnormal message in the RMQ_SYS_TRANS_HALF_TOPIC,this message causes the above exception.But i can't understand why there is such a message in the topic?

**Comment by chengdedeng** [comment]
If i reset consumer offset of RMQ_SYS_TRANS_HALF_TOPIC,skip the message,the exception disappears.

**Comment by chengdedeng** [comment]
when i get message in rocketmq-console,i get exception information:

> Caused by: java.lang.reflect.InvocationTargetException: null
        at sun.reflect.GeneratedMethodAccessor333.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.joor.Reflect.on(Reflect.java:694)
        ... 88 common frames omitted
Caused by: org.apache.rocketmq.client.exception.MQClientException: CODE: 208  DESC: query message by key finished, but no message.
For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
        at org.apache.rocketmq.client.impl.MQAdminImpl.queryMessage(MQAdminImpl.java:409)
        ... 92 common frames omitted

**Comment by duhenglucky** [comment]
@chengdedeng this issue has been resolved in 4.6.0:)
