### ISSUE TITLE
No route info of this topic

### ISSUE THREAD

**Issue by zhengjf1988** [apache/rocketmq#1064]
使用的是4.4.0版本的
确定服务启动成功  fastjson 已导入

在发送消息时，报错。
跟踪了一下代码
![image](https://user-images.githubusercontent.com/16054422/54006879-34e98900-419a-11e9-8b5b-1504890b91bc.png)
没太懂这里是判断什么的
topic一直没有创建

**Comment by liangyuanpeng** [comment]
尝试过在mq服务器上使用提供的脚本创建topic 发送消息吗，如果可以的话，再判断是否是防火墙问题

**Comment by dut-xiayuan** [comment]
有可能是在启动producer客户端之前没有指定**nameSvr**的地址，这里的例子应该更全一点[RocketMQ_Example](https://github.com/apache/rocketmq/blob/master/docs/cn/RocketMQ_Example.md)

**Comment by Loveslife** [comment]
我也有这个问题，用官网的命令启动Namesrv和Broker 之后，Producer是可以发送消息的。但是如果用源码 里面的NamesrvStartup和BrokerStartup启动，Producer 会报No route info of Topic

**Comment by ChesterZheng** [comment]
1.检查防火墙
2.检查集群状态(用rocketmq-console)
3.检查配置文件是否关闭了自动创建topic的配置
4.检查代码

**Comment by MagicEpoch** [comment]
我也遇到了同样的问题，回退到4.2.0才行，4.3、4.4都会抛这个异常

**Comment by zhengjf1988** [comment]
首先说一下，这个问题我不知道是bug还是说我的服务启动连接还是说网络问题。。。。

- 我在代码中创建了一个订单的topic，现在创建成功了，后来我也没时间继续折腾，所以不知道这个问题有没有解决，因为我也试了使用命令创建topic，所以不知道是代码创建成功的还是命令创建成功的。我不确定其他的topic是否可以创建成功。我自己后来没有继续测试这个问题。

- 本地连接服务器会出现连接超时的问题。我确定不是代码问题，因为我把代码发到阿里云ECS
 的MQ同一个服务器后，连接可以成功，也可以使用，但是在本地连接mq一直超时报错。

不是防火墙问题
没有使用集群 
自动创建topic在新版本中是默认开启的

**Comment by zhengjf1988** [comment]
`        <dependency>
            <groupId>org.apache.rocketmq</groupId>
            <artifactId>rocketmq-client</artifactId>
            <version>${mq.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.rocketmq</groupId>
            <artifactId>rocketmq-common</artifactId>
            <version>${mq.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.rocketmq</groupId>
            <artifactId>rocketmq-remoting</artifactId>
            <version>${mq.version}</version>
        </dependency>`

在pom中添加这三个jar就可以了 我使用的是4.4.0版本的

**Comment by zhengjf1988** [comment]
<dependency>
            <groupId>org.apache.rocketmq</groupId>
            <artifactId>rocketmq-client</artifactId>
            <version>${mq.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.rocketmq</groupId>
            <artifactId>rocketmq-common</artifactId>
            <version>${mq.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.rocketmq</groupId>
            <artifactId>rocketmq-remoting</artifactId>
            <version>${mq.version}</version>
        </dependency>

pom中添加这三个jar 使用的是4.4.0版本的 测试后可以正常创建没有问题

**Comment by zhengjf1988** [comment]
在关闭VIP通道后连接目前会超时。
org.apache.rocketmq.remoting.exception.RemotingTooMuchRequestException: sendDefaultImpl call timeout
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendDefaultImpl(DefaultMQProducerImpl.java:634)
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1279)
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1225)
	at org.apache.rocketmq.client.producer.DefaultMQProducer.send(DefaultMQProducer.java:283)
	at com.mjs.mojisishop.mq.producer.MqProducerService.send(MqProducerService.java:72)
	at com.mjs.mojisishop.controller.SaleController.mqtest(SaleController.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:897)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)

**Comment by zhengjf1988** [comment]
关闭VIP通道后，回报超时错误

**Comment by liangyuanpeng** [comment]
检查下相应端口是否开放
[Apache RocketMQ单机部署](https://liangyuanpeng.com/post/2018-11-27-rocketmq%E7%8E%AF%E5%A2%83%E6%90%AD%E5%BB%BA/)

**Comment by duhenglucky** [comment]
this issue has been resolved in this [pr](https://github.com/apache/rocketmq/pull/1415)

**Comment by vongosling** [comment]
@zhengjf1988 please refer to the pinned issue in issue home page. Any problem, please let us know:-)

**Comment by Garlichead** [comment]
> 1.检查防火墙
> 2.检查集群状态(用rocketmq-console)
> 3.检查配置文件是否关闭了自动创建topic的配置
> 4.检查代码
您好 第3点 这个配置是哪里可以查呢
