### ISSUE TITLE
Exception “No route info of this topic” throws when the client connects 4.4.0 server with its version 4.3.0.

### ISSUE THREAD

**Issue by onethin** [apache/rocketmq#1112]
**BUG REPORT**

1. 4.4.0服务端，4.3.0客户端，首次使用新topic发送消息报错：
Exception in thread "main" org.apache.rocketmq.client.exception.MQClientException: No route info of this topic, test-topic2
See http://rocketmq.apache.org/docs/faq/ for further details.
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendDefaultImpl(DefaultMQProducerImpl.java:610)
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1223)
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1173)
	at org.apache.rocketmq.client.producer.DefaultMQProducer.send(DefaultMQProducer.java:214)
	at com.test.Application.main(Application.java:29)

2. 服务端环境为RHEL 7.6 X64，oracle jdk version 1.8.0_191 x64

3. 如果使用4.4.0客户端能正常发送消息，而且4.4.0客户端成功发送消息后再用4.3.0客户端发送相同topic的消息可以发送成功。即在4.3.0客户端连接4.4.0服务端的情况下首次发送不能创建新的topic

**Comment by davidpdw** [comment]
4.3.0客户端修改了自动创建Topic所需要的内置Topic，所以默认4.3.0版本自动创建跟其它版本的broker会不兼容

**Comment by 3EDCKenneth** [comment]
@davidpdw 只有4.3才会出现这个不兼容的问题么？ 后期版本是否已经修复了这个问题？

**Comment by davidpdw** [comment]
@3EDCKenneth 4.3.1后将改动回退了，所以就4.3.0会有自动创建Topic版本不兼容

**Comment by onethin** [comment]
@davidpdw 因为现在生产上已经在用4.3.0客户端和4.3.0服务端，如果我升级服务端可能有些系统不能用了，有没有方法避免，或者让其他系统先升级到4.3.1客户端后我再升级服务端，这样客户端版本比服务端高可以兼容吗？

**Comment by davidpdw** [comment]
最简单方法建议使用手动创建Topic，目前自动创建Topic在特殊情况下会只创建在一个分片上，影响高可用。

**Comment by junminZ** [comment]
> @3EDCKenneth 4.3.1后将改动回退了，所以就4.3.0会有自动创建Topic版本不兼容

文档样例里的依赖版本还是4.3.0
