### ISSUE TITLE
Dledger集群搭建,启动报错,一下是详细配置文件信息

### ISSUE THREAD

**Issue by chyaz** [apache/rocketmq#1161]
配置文件内容:
brokerClusterName=XifanCluster
brokerName=XifanNode1
listenPort=30911
namesrvAddr=172.16.145.169:9876;172.16.145.168:9876;172.16.145.165:9876
storePathRootDir=/home/land/env/rocketmq/data/rmqstore/node00
storePathCommitLog=/home/land/env/rocketmq/data/rmqstore/node00/commitlog
enableDLegerCommitLog=true
dLegerGroup=XifanNode1
dLegerPeers=n1:40911;n2:40911;n3:40911
## must be unique
dLegerSelfId=n1
sendMessageThreadPoolNums=2

错误信息:

java.lang.ArrayIndexOutOfBoundsException: 1
	at io.openmessaging.storage.dledger.MemberState.<init>(MemberState.java:60)
	at io.openmessaging.storage.dledger.DLedgerServer.<init>(DLedgerServer.java:62)
	at org.apache.rocketmq.store.dledger.DLedgerCommitLog.<init>(DLedgerCommitLog.java:87)
	at org.apache.rocketmq.store.DefaultMessageStore.<init>(DefaultMessageStore.java:122)
	at org.apache.rocketmq.broker.BrokerController.initialize(BrokerController.java:238)
	at org.apache.rocketmq.broker.BrokerStartup.createBrokerController(BrokerStartup.java:218)
	at org.apache.rocketmq.broker.BrokerStartup.main(BrokerStartup.java:58)

**Comment by wlliqipeng** [comment]
Please describe the issue in English,thanks.

**Comment by reallax** [comment]
@chyaz the error caused by dLegerPeers config, you should use format like this:  {dLegerSelfId}-{peerHostIP}:{peerPort}, and you may config: dLegerPeers = n1-{host1}:40911;n2-{host2}:40911;n3-{host3}:40911

**Comment by chyaz** [comment]
> @chyaz the error caused by dLegerPeers config, you should use format like this: {dLegerSelfId}-{peerHostIP}:{peerPort}, and you may config: dLegerPeers = n1-{host1}:40911;n2-{host2}:40911;n3-{host3}:40911
thanks
