### ISSUE TITLE
send request to <ip:prot>                   failed

### ISSUE THREAD

**Issue by Suaron-Biliu** [apache/rocketmq#1176]
I am sure that my project jdk is the same as the rocketMQ jdk. I tried to start my project many times and reported the following exception. I don't know where the problem is. I am a mac environment, my colleague will not have this problem. I searched for this issue,   find no right solutions about this issue  

NettyClientWorkerThread_2  2019.04.23 at 17:00:37.935 CST [] INFO  org.apache.rocketmq.remoting.netty.NettyRemotingClient$NettyConnectManageHandler close():660 - NETTY CLIENT PIPELINE: CLOSE 122.112.204.214:9876
NettyClientWorkerThread_2  2019.04.23 at 17:00:37.935 CST [] INFO  org.apache.rocketmq.remoting.netty.NettyRemotingClient closeChannel():312 - eventCloseChannel: the channel[null] has been removed from the channel table before
NettyClientSelector_1  2019.04.23 at 17:00:37.936 CST [] INFO  org.apache.rocketmq.remoting.common.RemotingUtil$1 operationComplete():195 - closeChannel: close the connection to remote address[122.112.204.214:9876] result: true
MQClientFactoryScheduledThread  2019.04.23 at 17:00:37.935 CST [] WARN  org.apache.rocketmq.client.impl.factory.MQClientInstance updateTopicRouteInfoFromNameServer():658 - updateTopicRouteInfoFromNameServer Exception
 org.apache.rocketmq.remoting.exception.RemotingSendRequestException: send request to <122.112.204.214:9876> failed
	at org.apache.rocketmq.remoting.netty.NettyRemotingAbstract.invokeSyncImpl(NettyRemotingAbstract.java:389) ~[rocketmq-remoting-4.2.0.jar:4.2.0]
	at org.apache.rocketmq.remoting.netty.NettyRemotingClient.invokeSync(NettyRemotingClient.java:369) ~[rocketmq-remoting-4.2.0.jar:4.2.0]
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.getTopicRouteInfoFromNameServer(MQClientAPIImpl.java:1207) ~[rocketmq-client-4.2.0.jar:4.2.0]
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.getTopicRouteInfoFromNameServer(MQClientAPIImpl.java:1197) ~[rocketmq-client-4.2.0.jar:4.2.0]
	at org.apache.rocketmq.client.impl.factory.MQClientInstance.updateTopicRouteInfoFromNameServer(MQClientInstance.java:605) [rocketmq-client-4.2.0.jar:4.2.0]
	at org.apache.rocketmq.client.impl.factory.MQClientInstance.updateTopicRouteInfoFromNameServer(MQClientInstance.java:492) [rocketmq-client-4.2.0.jar:4.2.0]
	at org.apache.rocketmq.client.impl.factory.MQClientInstance.updateTopicRouteInfoFromNameServer(MQClientInstance.java:361) [rocketmq-client-4.2.0.jar:4.2.0]
	at org.apache.rocketmq.client.impl.factory.MQClientInstance$3.run(MQClientInstance.java:278) [rocketmq-client-4.2.0.jar:4.2.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:308) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: io.netty.handler.codec.EncoderException: java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.timeout.IdleStateHandler.write(IdleStateHandler.java:302) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.access$1900(AbstractChannelHandlerContext.java:38) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:1081) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1128) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:1070) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	... 1 more
Caused by: java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
	at org.apache.rocketmq.remoting.protocol.RemotingCommand.encodeHeader(RemotingCommand.java:427) ~[rocketmq-remoting-4.2.0.jar:4.2.0]
	at org.apache.rocketmq.remoting.protocol.RemotingCommand.encodeHeader(RemotingCommand.java:400) ~[rocketmq-remoting-4.2.0.jar:4.2.0]
	at org.apache.rocketmq.remoting.netty.NettyEncoder.encode(NettyEncoder.java:36) ~[rocketmq-remoting-4.2.0.jar:4.2.0]
	at org.apache.rocketmq.remoting.netty.NettyEncoder.encode(NettyEncoder.java:29) ~[rocketmq-remoting-4.2.0.jar:4.2.0]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.timeout.IdleStateHandler.write(IdleStateHandler.java:302) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.access$1900(AbstractChannelHandlerContext.java:38) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:1081) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1128) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:1070) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	... 1 more
MQClientFactoryScheduledThread  2019.04.23 at 17:00:37.937 CST [] INFO  org.apache.rocketmq.remoting.netty.NettyRemotingClient getAndCreateNameserverChannel():432 - new name server is chosen. OLD: 122.112.204.214:9876 , NEW: 122.112.204.214:9876. namesrvIndex = 182
MQClientFactoryScheduledThread  2019.04.23 at 17:00:37.937 CST [] INFO  org.apache.rocketmq.remoting.netty.NettyRemotingClient createChannel():479 - createChannel: begin to connect remote host[122.112.204.214:9876] asynchronously
NettyClientWorkerThread_3  2019.04.23 at 17:00:37.938 CST [] INFO  org.apache.rocketmq.remoting.netty.NettyRemotingClient$NettyConnectManageHandler connect():636 - NETTY CLIENT PIPELINE: CONNECT  UNKNOWN => 122.112.204.214:9876
MQClientFactoryScheduledThread  2019.04.23 at 17:00:37.967 CST [] INFO  org.apache.rocketmq.remoting.netty.NettyRemotingClient createChannel():496 - createChannel: connect remote host[122.112.204.214:9876] success, AbstractBootstrap$PendingRegistrationPromise@b4412ff(success)
NettyClientSelector_1  2019.04.23 at 17:00:37.968 CST [] WARN  org.apache.rocketmq.remoting.netty.NettyRemotingAbstract$3 operationComplete():379 - send a request command to channel </122.112.204.214:9876> failed.
MQClientFactoryScheduledThread  2019.04.23 at 17:00:37.968 CST [] WARN  org.apache.rocketmq.remoting.netty.NettyRemotingClient invokeSync():375 - invokeSync: send request exception, so close the channel[null]
MQClientFactoryScheduledThread  2019.04.23 at 17:00:37.968 CST [] INFO  org.apache.rocketmq.remoting.netty.NettyRemotingClient closeChannel():254 - closeChannel: begin close the channel[122.112.204.214:9876] Found: true
MQClientFactoryScheduledThread  2019.04.23 at 17:00:37.968 CST [] INFO  org.apache.rocketmq.remoting.netty.NettyRemotingClient closeChannel():267 - closeChannel: the channel[122.112.204.214:9876] was removed from channel table

**Comment by shouzimu** [comment]
i build in java12 and run with java8, report this error
```
Caused by: io.netty.handler.codec.EncoderException: java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer
```
then i build in java8 and run with java8, it's ok

```java
sh bin/tools.sh org.apache.rocketmq.example.quickstart.Producer
SendResult [sendStatus=SEND_OK, msgId=C0A801030861511D50C0904741AB0000, offsetMsgId=C0A8010300002A9F000000000002BEB2, messageQueue=MessageQueue [topic=TopicTest, brokerName=localhost, queueId=1], queueOffset=250]
```

**Comment by DKAngel** [comment]
I've had this problem, too. Have you solved it?
