### ISSUE TITLE
MultiThread Pull message,when restart application a RemotingSendRequestException throw

### ISSUE THREAD

**Issue by aa1215018028** [apache/rocketmq#1179]
2019-04-25 10:38:54.335 [TID:N/A] [PullMsgThread-datasource_consumer_group4] INFO  RocketmqRemoting line:90  -closeChannel: the channel[IP:port] has been closed before, and has been created again, nothing to do.
2019-04-25 10:38:54.339 [TID:N/A] [PullMsgThread-datasource_consumer_group4] WARN  RocketmqClient line:130 -fetchConsumeOffsetFromBroker exception, MessageQueue [topic=topic_history_data_stream, brokerName=broker-c, queueId=1]
org.apache.rocketmq.remoting.exception.RemotingSendRequestException: send request to <IP:PORT> failed
        at org.apache.rocketmq.remoting.netty.NettyRemotingAbstract.invokeSyncImpl(NettyRemotingAbstract.java:393)
        at org.apache.rocketmq.remoting.netty.NettyRemotingClient.invokeSync(NettyRemotingClient.java:374)
        at org.apache.rocketmq.client.impl.MQClientAPIImpl.queryConsumerOffset(MQClientAPIImpl.java:809)
        at org.apache.rocketmq.client.consumer.store.RemoteBrokerOffsetStore.fetchConsumeOffsetFromBroker(RemoteBrokerOffsetStore.java:246)
        at org.apache.rocketmq.client.consumer.store.RemoteBrokerOffsetStore.readOffset(RemoteBrokerOffsetStore.java:91)
        at org.apache.rocketmq.client.impl.consumer.DefaultMQPullConsumerImpl.fetchConsumeOffset(DefaultMQPullConsumerImpl.java:109)
        at org.apache.rocketmq.client.consumer.DefaultMQPullConsumer.fetchConsumeOffset(DefaultMQPullConsumer.java:293)
        at ****************doPullTask(ResourcePullConsumer.java:69)
        at org.apache.rocketmq.client.consumer.MQPullConsumerScheduleService$PullTaskImpl.run(MQPullConsumerScheduleService.java:172)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecut

**Comment by aa1215018028** [comment]
This phenomenon only happens occasionally, not every time. When it appears, it will cause the offset of the corresponding queue to reset to 0, which is a disgusting problem

**Comment by duhenglucky** [comment]
@aa1215018028 The latest version of RocketMQ provides a lightweight Pull Consumer，welcome to use this and give more suggestions.  so this issue will be closed first, but please feel free to reopen it if you have any other questions.
