### ISSUE TITLE
dLegerPeers 的地址解析有缺陷

### ISSUE THREAD

**Issue by meteorice** [apache/rocketmq#1443]
**BUG REPORT**

1. Please describe the issue you observed:
我的应用运行在kubernetes环境，当配置如
dLegerPeers=n1-broker1-0.brokersvc1:20911;n2-broke2-0.brokersvc2:20911;n3-broker3-0.brokersvc3:20911 解析就会数组越界,因为split”-“后 索引1不是完整域名地址，如图。
kubernetes中StatefulSet是会自动给pod的name加一个”-0“所以DNS分配的时候就会有这个问题
![image](https://user-images.githubusercontent.com/11306060/64183403-6ec2f000-ce9c-11e9-86a5-5c6585483fae.png)

2. Please tell us about your environment:
kubernetes 1.12.6 centos7
3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):
```
java.lang.ArrayIndexOutOfBoundsException: 1
	at io.openmessaging.storage.dledger.DLedgerRpcNettyService.<init>(DLedgerRpcNettyService.java:93)
	at io.openmessaging.storage.dledger.DLedgerServer.<init>(DLedgerServer.java:64)
	at org.apache.rocketmq.store.dledger.DLedgerCommitLog.<init>(DLedgerCommitLog.java:87)
	at org.apache.rocketmq.store.DefaultMessageStore.<init>(DefaultMessageStore.java:122)
	at org.apache.rocketmq.broker.BrokerController.initialize(BrokerController.java:239)
	at org.apache.rocketmq.broker.BrokerStartup.createBrokerController(BrokerStartup.java:218)
	at org.apache.rocketmq.broker.BrokerStartup.main(BrokerStartup.java:58)
```
**FEATURE REQUEST**
我希望能接受这样的配置
dLegerPeers.n1=broker1-0.brokersvc1:20911
dLegerPeers.n2=broker2-0.brokersvc2:20911
dLegerPeers.n3=broker3-0.brokersvc3:20911

**Comment by duhenglucky** [comment]
@meteorice this issue has been fixed in dledger repo, welcome to review this [PR](https://github.com/openmessaging/openmessaging-storage-dledger/pull/31) and give more verification.
