### ISSUE TITLE
org.apache.rocketmq.client.exception.MQBrokerException: CODE: 2  DESC: [TIMEOUT_CLEAN_QUEUE]broker busy, start flow control for a while, period in queue: 309ms, size of queue: 6

### ISSUE THREAD

**Issue by 942391815** [apache/rocketmq#1494]
org.apache.rocketmq.client.exception.MQBrokerException: CODE: 2  DESC: [TIMEOUT_CLEAN_QUEUE]broker busy, start flow control for a while, period in queue: 309ms, size of queue: 4
For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.processSendResponse(MQClientAPIImpl.java:556)
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessageSync(MQClientAPIImpl.java:358)
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessage(MQClientAPIImpl.java:340)
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessage(MQClientAPIImpl.java:294)
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendKernelImpl(DefaultMQProducerImpl.java:761)
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendDefaultImpl(DefaultMQProducerImpl.java:505)
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1223)

1.一个MQ集群有多个Topic其中一个topicA 对发送的实时性，可用性特别高。其他topic实时性要求不那么高。其他topic峰值，会不会导topicA 消息发送的延迟，变慢。 ps:同步发送，刷盘。

2.有没有高优先级的设置，或者topic线程隔离处理。

**Comment by duhenglucky** [comment]
1、topic之间的影响是存在的，但是可以通过不同topic的消息是否save来解决不同topic的可靠性问题。
2、我的理解是你希望对topic可以有优先级的区分，这个确实可以讨论一下。

**Comment by duhenglucky** [comment]
@942391815 ping?
