### ISSUE TITLE
server aclEnable=true,request's extFields value is null.

### ISSUE THREAD

**Issue by xiaoluobotouzi** [apache/rocketmq#1601]
The issue tracker is **ONLY** used for bug report(feature request need to follow [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal)). Keep in mind, please check whether there is an existing same report before your raise a new one.

Alternately (especially if your communication is not a bug report), you can send mail to our [mailing lists](http://rocketmq.apache.org/about/contact/). We welcome any friendly suggestions, bug fixes, collaboration and other improvements.

Please ensure that your bug report is clear and that it is complete. Otherwise, we may be unable to understand it or to reproduce it, either of which would prevent us from fixing the bug. We strongly recommend the report(bug report or feature request) could include some hints as the following:

**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
master/slave config add aclEnable=true.
- What did you expect to see?
slave success update master config.
- What did you see instead?
one:
`org.apache.rocketmq.client.exception.MQBrokerException: CODE: 1  DESC: org.apache.rocketmq.acl.common.AclException: request's extFields value is null, org.apache.rocketmq.acl.plain.PlainAccessValidator.parse(PlainAccessValidator.java:60)
For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
	at org.apache.rocketmq.broker.out.BrokerOuterAPI.getAllConsumerOffset(BrokerOuterAPI.java:368) ~[rocketmq-broker-4.5.0.jar:4.5.0]
	at org.apache.rocketmq.broker.slave.SlaveSynchronize.syncConsumerOffset(SlaveSynchronize.java:88) [rocketmq-broker-4.5.0.jar:4.5.0]
	at org.apache.rocketmq.broker.slave.SlaveSynchronize.syncAll(SlaveSynchronize.java:51) [rocketmq-broker-4.5.0.jar:4.5.0]
`
two:
`org.apache.rocketmq.client.exception.MQBrokerException: CODE: 1  DESC: org.apache.rocketmq.acl.common.AclException: request's extFields value is null, org.apache.rocketmq.acl.plain.PlainAccessValidator.parse(PlainAccessValidator.java:60)
For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
	at org.apache.rocketmq.broker.out.BrokerOuterAPI.getAllDelayOffset(BrokerOuterAPI.java:385) ~[rocketmq-broker-4.5.0.jar:4.5.0]
	at org.apache.rocketmq.broker.slave.SlaveSynchronize.syncDelayOffset(SlaveSynchronize.java:105) [rocketmq-broker-4.5.0.jar:4.5.0]
	at org.apache.rocketmq.broker.slave.SlaveSynchronize.syncAll(SlaveSynchronize.java:52) [rocketmq-broker-4.5.0.jar:4.5.0]
`
three:
`org.apache.rocketmq.client.exception.MQBrokerException: CODE: 1  DESC: org.apache.rocketmq.acl.common.AclException: request's extFields value is null, org.apache.rocketmq.acl.plain.PlainAccessValidator.parse(PlainAccessValidator.java:60)
For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
	at org.apache.rocketmq.broker.out.BrokerOuterAPI.getAllSubscriptionGroupConfig(BrokerOuterAPI.java:402) ~[rocketmq-broker-4.5.0.jar:4.5.0]
	at org.apache.rocketmq.broker.slave.SlaveSynchronize.syncSubscriptionGroupConfig(SlaveSynchronize.java:131) [rocketmq-broker-4.5.0.jar:4.5.0]
	at org.apache.rocketmq.broker.slave.SlaveSynchronize.syncAll(SlaveSynchronize.java:53) [rocketmq-broker-4.5.0.jar:4.5.0]
`
2. Please tell us about your environment:
CentOS release 6.9 X86
jdk1.8
mqVersion 4.5.0
3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by xiaoluobotouzi** [comment]
I debugged the problem.
In the placeaccessvalidator class, an exception thrown by a judgment branch in the parse method.
code:
`if (request.getExtFields() == null) {  
      throw new AclException("request's extFields value is null");
 }`.

In the BrokerouterAPI class, create remotingcommand in getalltopicconfig method, and extfields is null.

I added a piece of code：
`request.setExtFields(new HashMap<>());`

however,
In the plainpermissionloader class, validate method, a piece of code continues to throw an exception.
code:
`if (plainAccessResource.getAccessKey() == null) {
            throw new AclException(String.format("No accessKey is configured"));
        }`

I added - 192.168.1.2 to globalwhiteremoteaddress in the plain_acl.yml config file.

No exception thrown in log file.

I don't know if my understanding is correct.

**Comment by xiaoluobotouzi** [comment]
@zongtanghu @duhengforever

**Comment by ziyunmuxu** [comment]
I met the same problem，when master and slave broker have enabled acl，slave broker will call the method（SlaveSynchronize.syncTopicConfig）, but BrokerController init brokerOuterAPI whithout any RPCHook, so the master responsed AclException
I don't know if my understanding is correct.

**Comment by jinxbinder** [comment]
ava.lang.RuntimeException: org.apache.rocketmq.client.exception.MQBrokerException: CODE: 1  DESC: org.apache.rocketmq.acl.common.AclException: request's extFields value is null, org.apache.rocketmq.acl.plain.PlainAccessValidator.parse(PlainAccessValidator.java:57)
For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
	at com.google.common.base.Throwables.propagate(Throwables.java:160)
	at org.apache.rocketmq.console.task.DashboardCollectTask.fetchBrokerRuntimeStats(DashboardCollectTask.java:220)
	at org.apache.rocketmq.console.task.DashboardCollectTask.fetchBrokerRuntimeStats(DashboardCollectTask.java:219)
	at org.apache.rocketmq.console.task.DashboardCollectTask.fetchBrokerRuntimeStats(DashboardCollectTask.java:219)
	at org.apache.rocketmq.console.task.DashboardCollectTask.collectBroker(DashboardCollectTask.java:185)
	at org.apache.rocketmq.console.task.DashboardCollectTask$$FastClassBySpringCGLIB$$c818b8cd.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at org.apache.rocketmq.console.task.DashboardCollectTask$$EnhancerBySpringCGLIB$$65b498ea.collectBroker(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.rocketmq.client.exception.MQBrokerException: CODE: 1  DESC: org.apache.rocketmq.acl.common.AclException: request's extFields value is null, org.apache.rocketmq.acl.plain.PlainAccessValidator.parse(PlainAccessValidator.java:57)
For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.getBrokerRuntimeInfo(MQClientAPIImpl.java:1282)
	at org.apache.rocketmq.tools.admin.DefaultMQAdminExtImpl.fetchBrokerRuntimeStats(DefaultMQAdminExtImpl.java:266)
	at org.apache.rocketmq.tools.admin.DefaultMQAdminExt.fetchBrokerRuntimeStats(DefaultMQAdminExt.java:231)
	at org.apache.rocketmq.console.service.client.MQAdminExtImpl.fetchBrokerRuntimeStats(MQAdminExtImpl.java:185)
	at org.apache.rocketmq.console.service.client.MQAdminExtImpl$$FastClassBySpringCGLIB$$f6279829.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
	at org.apache.rocketmq.console.aspect.admin.MQAdminAspect.aroundMQAdminMethod(MQAdminAspect.java:63)
	at sun.reflect.GeneratedMethodAccessor48.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at org.apache.rocketmq.console.service.client.MQAdminExtImpl$$EnhancerBySpringCGLIB$$b089b07e.fetchBrokerRuntimeStats(<generated>)
	at org.apache.rocketmq.console.task.DashboardCollectTask.fetchBrokerRuntimeStats(DashboardCollectTask.java:210)
	... 27 common frames omitted
我是在broker4.5.0开启了acl机制后，console报的错，有人知道怎么解决吗

**Comment by caigy** [comment]
@jinxbinder Adding the console IP in global white addresses of ACL may help, or checking whether an admin ACL user can be adopted by console.
