### ISSUE TITLE
 broker & nameserver shutdown when testing

### ISSUE THREAD

**Issue by henrypoter** [apache/rocketmq#1641]
1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
rocketmq版本 4.6.0。使用dledger模式部署了一个broker分片，1主2从。
其中有一个从节点在压测过程中broker和namserver进程终止了，可能是由于磁盘使用率达到85%导致。 

nameserver终止前的log如下 :
`2019-12-04 17:30:13 INFO NSScheduledThread1 - --------------------------------------------------------
2019-12-04 17:30:13 INFO NSScheduledThread1 - configTable SIZE: 0
2019-12-04 17:30:30 INFO NettyServerCodecThread_8 - NETTY SERVER PIPELINE: channelRegistered 192.168.111.213:42205
2019-12-04 17:30:30 INFO NettyServerCodecThread_8 - NETTY SERVER PIPELINE: channelActive, the channel[192.168.111.213:42205]
2019-12-04 17:30:30 INFO NettyServerCodecThread_8 - NETTY SERVER PIPELINE: channelInactive, the channel[192.168.111.213:42205]
2019-12-04 17:30:30 INFO NettyServerCodecThread_8 - NETTY SERVER PIPELINE: channelUnregistered, the channel[192.168.111.213:42205]
2019-12-04 17:31:00 INFO NettyServerCodecThread_1 - NETTY SERVER PIPELINE: channelRegistered 192.168.111.213:42329
2019-12-04 17:31:00 INFO NettyServerCodecThread_1 - NETTY SERVER PIPELINE: channelActive, the channel[192.168.111.213:42329]
2019-12-04 17:31:00 INFO NettyServerCodecThread_1 - NETTY SERVER PIPELINE: channelInactive, the channel[192.168.111.213:42329]
2019-12-04 17:31:00 INFO NettyServerCodecThread_1 - NETTY SERVER PIPELINE: channelUnregistered, the channel[192.168.111.213:42329]
2019-12-04 17:31:30 INFO NettyServerCodecThread_2 - NETTY SERVER PIPELINE: channelRegistered 192.168.111.213:42437
2019-12-04 17:31:30 INFO NettyServerCodecThread_2 - NETTY SERVER PIPELINE: channelActive, the channel[192.168.111.213:42437]
2019-12-04 17:31:30 INFO NettyServerCodecThread_2 - NETTY SERVER PIPELINE: channelInactive, the channel[192.168.111.213:42437]
2019-12-04 17:31:30 INFO NettyServerCodecThread_2 - NETTY SERVER PIPELINE: channelUnregistered, the channel[192.168.111.213:42437]
2019-12-04 17:31:52 INFO ShutdownHook - shutdown hook was invoked, 1 times.
2019-12-04 17:31:52 INFO ShutdownHook - shutdown thread NettyEventExecutor interrupt false
2019-12-04 17:31:52 INFO NettyServerCodecThread_2 - NETTY SERVER PIPELINE: channelInactive, the channel[192.168.111.214:39066]
2019-12-04 17:31:52 INFO NettyServerCodecThread_3 - NETTY SERVER PIPELINE: channelInactive, the channel[192.168.111.212:56670]
2019-12-04 17:31:52 INFO NettyServerCodecThread_4 - NETTY SERVER PIPELINE: channelInactive, the channel[192.168.111.213:13615]
2019-12-04 17:31:52 INFO NettyServerCodecThread_2 - NETTY SERVER PIPELINE: channelUnregistered, the channel[192.168.111.214:39066]
2019-12-04 17:31:52 INFO NettyServerCodecThread_4 - NETTY SERVER PIPELINE: channelUnregistered, the channel[192.168.111.213:13615]
2019-12-04 17:31:52 INFO NettyServerCodecThread_3 - NETTY SERVER PIPELINE: channelUnregistered, the channel[192.168.111.212:56670]
2019-12-04 17:31:52 INFO NettyEventExecutor - the broker's channel destroyed, 192.168.111.214:30911, clean it's data structure at once
2019-12-04 17:31:52 INFO NettyEventExecutor - remove brokerAddr[3, 192.168.111.214:30911] from brokerAddrTable, because channel destroyed
2019-12-04 17:31:52 INFO NettyEventExecutor - NettyEventExecutor service end
2019-12-04 17:31:52 INFO ShutdownHook - join thread NettyEventExecutor elapsed time(ms) 0 90000
2019-12-04 17:31:52 INFO ShutdownHook - Try to shutdown service thread:FileWatchService started:true lastThread:Thread[FileWatchService,5,main]
2019-12-04 17:31:52 INFO ShutdownHook - shutdown thread FileWatchService interrupt false
2019-12-04 17:31:52 INFO FileWatchService - FileWatchService service end
2019-12-04 17:31:52 INFO ShutdownHook - join thread FileWatchService elapsed time(ms) 1 90000
2019-12-04 17:31:52 INFO ShutdownHook - shutdown hook done, consuming time total(ms): 13
`

broker终止前的log信息如下：

`2019-12-04 17:31:44 INFO brokerOutApi_thread_2 - register broker[2]to name serve                                              r 192.168.111.213:9876 OK
2019-12-04 17:31:44 INFO brokerOutApi_thread_4 - register broker[2]to name serve                                              r 192.168.111.212:9876 OK
2019-12-04 17:31:44 INFO brokerOutApi_thread_1 - register broker[2]to name serve                                              r 192.168.111.214:9876 OK
2019-12-04 17:31:48 INFO BrokerControllerScheduledThread1 - Update slave consume                                              r offset from master, 192.168.111.212:30911
2019-12-04 17:31:48 INFO BrokerControllerScheduledThread1 - Update slave delay o                                              ffset from master, 192.168.111.212:30911
2019-12-04 17:31:52 INFO ShutdownHook - Shutdown hook was invoked, 1
2019-12-04 17:31:52 INFO ShutdownHook - Try to shutdown service thread:PullReque                                              stHoldService started:true lastThread:Thread[PullRequestHoldService,5,main]
2019-12-04 17:31:52 INFO ShutdownHook - shutdown thread PullRequestHoldService i                                              nterrupt false
2019-12-04 17:31:52 INFO PullRequestHoldService - PullRequestHoldService service                                               end
2019-12-04 17:31:52 INFO ShutdownHook - join thread PullRequestHoldService elaps                                              ed time(ms) 0 90000
2019-12-04 17:31:52 INFO NettyEventExecutor - NETTY EVENT: remove channel[Client                                              ChannelInfo [channel=[id: 0xb276cb06, L:/192.168.111.213:30911 ! R:/192.168.111.                                              212:48948], clientId=192.168.111.212@1575364852429, language=JAVA, version=333,                                               lastUpdateTimestamp=1575451883690]][192.168.111.212:48948] from ProducerManager                                               groupChannelTable, producer group: CLIENT_INNER_PRODUCER
2019-12-04 17:31:52 WARN NettyEventExecutor - NETTY EVENT: remove not active cha                                              nnel[ClientChannelInfo [channel=[id: 0xb276cb06, L:/192.168.111.213:30911 ! R:/1                                              92.168.111.212:48948], clientId=192.168.111.212@1575364852429, language=JAVA, ve                                              rsion=333, lastUpdateTimestamp=1575451883690]] from ConsumerGroupInfo groupChann                                              elTable, consumer group: benchmark_consumer_2
2019-12-04 17:31:52 INFO NettyEventExecutor - unregister consumer ok, no any con                                              nection, and remove consumer group, benchmark_consumer_2
2019-12-04 17:31:54 INFO ShutdownHook - Try to shutdown service thread:FileWatch                                              Service started:true lastThread:Thread[FileWatchService,5,main]
2019-12-04 17:31:54 INFO ShutdownHook - shutdown thread FileWatchService interru                                              pt false
2019-12-04 17:31:54 INFO FileWatchService - FileWatchService service end
2019-12-04 17:31:54 INFO ShutdownHook - join thread FileWatchService elapsed tim                                              e(ms) 0 90000
2019-12-04 17:31:55 INFO ShutdownHook - Try to shutdown service thread:StoreStat                                              sService started:true lastThread:Thread[StoreStatsService,5,main]
2019-12-04 17:31:55 INFO ShutdownHook - shutdown thread StoreStatsService interr                                              upt false
2019-12-04 17:31:55 INFO ShutdownHook - join thread StoreStatsService elapsed ti                                              me(ms) 0 90000
2019-12-04 17:31:55 INFO ShutdownHook - Try to shutdown service thread:ReputMess                                              ageService started:true lastThread:Thread[ReputMessageService,5,main]
2019-12-04 17:31:55 INFO ShutdownHook - shutdown thread ReputMessageService inte                                              rrupt false
2019-12-04 17:31:55 INFO ShutdownHook - join thread ReputMessageService elapsed                                               time(ms) 0 90000
2019-12-04 17:31:55 INFO ShutdownHook - Try to shutdown service thread:FlushCons                                              umeQueueService started:true lastThread:Thread[FlushConsumeQueueService,5,main]
2019-12-04 17:31:55 INFO ShutdownHook - shutdown thread FlushConsumeQueueService                                               interrupt false
2019-12-04 17:31:55 INFO ShutdownHook - join thread FlushConsumeQueueService ela                                              psed time(ms) 11 60000
2019-12-04 17:31:55 INFO ShutdownHook - Try to shutdown service thread:AllocateM                                              appedFileService started:true lastThread:Thread[AllocateMappedFileService,5,main                                              ]
2019-12-04 17:31:55 INFO ShutdownHook - shutdown thread AllocateMappedFileServic                                              e interrupt true
2019-12-04 17:31:55 INFO ShutdownHook - join thread AllocateMappedFileService el                                              apsed time(ms) 0 90000
2019-12-04 17:31:55 INFO ShutdownHook - unregisterBroker OK, NamesrvAddr: 192.16                                              8.111.212:9876
2019-12-04 17:31:55 INFO ShutdownHook - unregisterBroker OK, NamesrvAddr: 192.16                                              8.111.214:9876
2019-12-04 17:31:55 WARN ShutdownHook - unregisterBroker Exception, 192.168.111.                                              213:9876
org.apache.rocketmq.remoting.exception.RemotingConnectException: connect to 192.                                              168.111.213:9876 failed
        at org.apache.rocketmq.remoting.netty.NettyRemotingClient.invokeSync(Net                                              tyRemotingClient.java:390) ~[rocketmq-remoting-4.6.0.jar:4.6.0]
        at org.apache.rocketmq.broker.out.BrokerOuterAPI.unregisterBroker(Broker                                              OuterAPI.java:248) ~[rocketmq-broker-4.6.0.jar:4.6.0]
        at org.apache.rocketmq.broker.out.BrokerOuterAPI.unregisterBrokerAll(Bro                                              kerOuterAPI.java:225) ~[rocketmq-broker-4.6.0.jar:4.6.0]
        at org.apache.rocketmq.broker.BrokerController.unregisterBrokerAll(Broke                                              rController.java:840) [rocketmq-broker-4.6.0.jar:4.6.0]
        at org.apache.rocketmq.broker.BrokerController.shutdown(BrokerController                                              .java:779) [rocketmq-broker-4.6.0.jar:4.6.0]
        at org.apache.rocketmq.broker.BrokerStartup$1.run(BrokerStartup.java:239                                              ) [rocketmq-broker-4.6.0.jar:4.6.0]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
2019-12-04 17:31:55 INFO ShutdownHook - Try to shutdown service thread:FileWatch                                              Service started:false lastThread:Thread[FileWatchService,5,]
2019-12-04 17:31:55 INFO ShutdownHook - Try to shutdown service thread:Transacti                                              onalMessageCheckService started:false lastThread:null
2019-12-04 17:31:55 INFO ShutdownHook - Shutdown hook over, consuming total time                                              (ms): 2574
` 

重启broker和NameServer后恢复log,从节点一直未收到消息

`
2019-12-05 14:20:24 INFO main - Begin to recover data from entryIndex=629360492 fileIndex=17 fileSize=20 fileName=/home/rocketmq/store/dledger-n1/data/00000000426275504128 
2019-12-05 14:20:25 INFO main - Trying to recover data file /home/rocketmq/store/dledger-n1/data/00000000427349245952
2019-12-05 14:20:26 INFO main - Trying to recover data file /home/rocketmq/store/dledger-n1/data/00000000428422987776
        at io.openmessaging.storage.dledger.store.file.DLedgerMmapFileStore.recover(DLedgerMmapFileStore.java:216) ~[dledger-0.1.jar:na]
        at org.apache.rocketmq.store.dledger.DLedgerCommitLog.recover(DLedgerCommitLog.java:253) [rocketmq-store-4.6.0.jar:4.6.0]
        at org.apache.rocketmq.store.dledger.DLedgerCommitLog.recoverNormally(DLedgerCommitLog.java:305) [rocketmq-store-4.6.0.jar:4.6.0]
        at org.apache.rocketmq.store.DefaultMessageStore.recover(DefaultMessageStore.java:1334) [rocketmq-store-4.6.0.jar:4.6.0]
2019-12-05 22:28:18 INFO main - Begin to recover data from entryIndex=629360492 fileIndex=17 fileSize=20 fileName=/home/rocketmq/store/dledger-n1/data/00000000426275504128 
2019-12-05 22:28:19 INFO main - Trying to recover data file /home/rocketmq/store/dledger-n1/data/00000000427349245952
2019-12-05 22:28:20 INFO main - Trying to recover data file /home/rocketmq/store/dledger-n1/data/00000000428422987776
        at io.openmessaging.storage.dledger.store.file.DLedgerMmapFileStore.recover(DLedgerMmapFileStore.java:216) ~[dledger-0.1.jar:na]
        at org.apache.rocketmq.store.dledger.DLedgerCommitLog.recover(DLedgerCommitLog.java:253) [rocketmq-store-4.6.0.jar:4.6.0]
        at org.apache.rocketmq.store.dledger.DLedgerCommitLog.recoverNormally(DLedgerCommitLog.java:305) [rocketmq-store-4.6.0.jar:4.6.0]
        at org.apache.rocketmq.store.DefaultMessageStore.recover(DefaultMessageStore.java:1334) [rocketmq-store-4.6.0.jar:4.6.0]
2019-12-03 10:47:56 INFO main - recover next consume queue file, /home/rocketmq/store/consumequeue/uat-topic/0/00000000000012000000
2019-12-03 10:47:56 INFO main - recover next consume queue file, /home/rocketmq/store/consumequeue/uat-topic/0/00000000000018000000
2019-12-03 10:47:56 INFO main - recover current consume queue file over,  /home/rocketmq/store/consumequeue/uat-topic/0/00000000000018000000 0 0 0
2019-12-03 10:47:56 INFO main - recover current consume queue queue over /home/rocketmq/store/consumequeue/uat-topic/0/00000000000018000000 22122820
2019-12-03 10:47:56 INFO main - recover next consume queue file, /home/rocketmq/store/consumequeue/uat-topic/1/00000000000012000000
2019-12-03 10:47:56 INFO main - recover next consume queue file, /home/rocketmq/store/consumequeue/uat-topic/1/00000000000018000000
2019-12-03 10:47:56 INFO main - recover current consume queue file over,  /home/rocketmq/store/consumequeue/uat-topic/1/00000000000018000000 0 0 0
2019-12-03 10:47:56 INFO main - recover current consume queue queue over /home/rocketmq/store/consumequeue/uat-topic/1/00000000000018000000 22123000
2019-12-03 10:47:56 INFO main - recover next consume queue file, /home/rocketmq/store/consumequeue/uat-topic/2/00000000000012000000
2019-12-03 10:47:56 INFO main - recover next consume queue f`

`
[rocketmq@y2_web212 rocketmqlogs]$ vi broker_default.log 

2019-12-05 03:38:01 ERROR EntryDispatcher-n0-n1 - [Push-n1]Error in EntryDispatcher-n0-n1 writeIndex=29222072 compareIndex=-1
io.openmessaging.storage.dledger.exception.DLedgerException: [code=410,name=INDEX_OUT_OF_RANGE,desc=] 29221072 should between 300627707-313007211
        at io.openmessaging.storage.dledger.utils.PreConditions.check(PreConditions.java:41) ~[dledger-0.1.jar:na]
        at io.openmessaging.storage.dledger.store.file.DLedgerMmapFileStore.get(DLedgerMmapFileStore.java:479) ~[dledger-0.1.jar:na]
        at io.openmessaging.storage.dledger.DLedgerEntryPusher$EntryDispatcher.doAppendInner(DLedgerEntryPusher.java:389) ~[dledger-0.1.jar:na]
        at io.openmessaging.storage.dledger.DLedgerEntryPusher$EntryDispatcher.doCheckAppendResponse(DLedgerEntryPusher.java:434) ~[dledger-0.1.jar:na]
        at io.openmessaging.storage.dledger.DLedgerEntryPusher$EntryDispatcher.doAppend(DLedgerEntryPusher.java:461) ~[dledger-0.1.jar:na]
        at io.openmessaging.storage.dledger.DLedgerEntryPusher$EntryDispatcher.doWork(DLedgerEntryPusher.java:602) ~[dledger-0.1.jar:na]
        at io.openmessaging.storage.dledger.ShutdownAbleThread.run(ShutdownAbleThread.java:87) [dledger-0.1.jar:na]
2019-12-05 03:38:02 INFO DLedgerFlushDataService - Flush data cost=691 ms
2019-12-05 03:38:02 ERROR StateMaintainer - Send heartBeat request failed info[group=RaftNode00,term=1,code=200,local=n0,remote=n1,leader=n0]
org.apache.rocketmq.remoting.exception.RemotingConnectException: connect to 192.168.111.213:40911 failed
        at org.apache.rocketmq.remoting.netty.NettyRemotingClient.invokeAsync(NettyRemotingClient.java:531) ~[rocketmq-remoting-4.6.0.jar:4.6.0]
        at io.openmessaging.storage.dledger.DLedgerRpcNettyService.heartBeat(DLedgerRpcNettyService.java:118) ~[dledger-0.1.jar:na]
        at io.openmessaging.storage.dledger.DLedgerLeaderElector.sendHeartbeats(DLedgerLeaderElector.java:252) [dledger-0.1.jar:na]
        at io.openmessaging.storage.dledger.DLedgerLeaderElector.maintainAsLeader(DLedgerLeaderElector.java:320) [dledger-0.1.jar:na]
        at io.openmessaging.storage.dledger.DLedgerLeaderElector.maintainState(DLedgerLeaderElector.java:506) [dledger-0.1.jar:na]
        at io.openmessaging.storage.dledger.DLedgerLeaderElector.access$200(DLedgerLeaderElector.java:40) [dledger-0.1.jar:na]
        at io.openmessaging.storage.dledger.DLedgerLeaderElector$StateMaintainer.doWork(DLedgerLeaderElector.java:548) [dledger-0.1.jar:na]
        at io.openmessaging.storage.dledger.ShutdownAbleThread.run(ShutdownAbleThread.java:87) [dledger-0.1.jar:na]
2019-12-05 03:38:03 WARN EntryDispatcher-n0-n1 - [Push-n1]Retry to push entry at 29221072
2019-12-05 03:38:03 ERROR EntryDispatcher-n0-n1 - [Push-n1]Error in EntryDispatcher-n0-n1 writeIndex=29222072 compareIndex=-1
io.openmessaging.storage.dledger.exception.DLedgerException: [code=410,name=INDEX_OUT_OF_RANGE,desc=] 29221072 should between 300627707-313007409
        at io.openmessaging.storage.dledger.utils.PreConditions.check(PreConditions.java:41) ~[dledger-0.1.jar:na]
        at io.openmessaging.storage.dledger.store.file.DLedgerMmapFileStore.get(DLedgerMmapFileStore.java:479) ~[dledger-0.1.jar:na]
        at io.openmessaging.storage.dledger.DLedgerEntryPusher$EntryDispatcher.doAppendInner(DLedgerEntryPusher.java:389) ~[dledger-0.1.jar:na]
        at io.openmessaging.storage.dledger.DLedgerEntryPusher$EntryDispatcher.doCheckAppendResponse(DLedgerEntryPusher.java:434) ~[dledger-0.1.jar:na]
        at io.openmessaging.storage.dledger.DLedgerEntryPusher$EntryDispatcher.doAppend(DLedgerEntryPusher.java:461) ~[dledger-0.1.jar:na]
        at io.openmessaging.storage.dledger.DLedgerEntryPusher$EntryDispatcher.doWork(DLedgerEntryPusher.java:602) ~[dledger-0.1.jar:na]
        at io.openmessaging.storage.dledger.ShutdownAbleThread.run(ShutdownAbleThread.java:87) [dledger-0.1.jar:na]
2019-12-05 03:38:03 INFO QuorumAckChecker - [n0][LEADER] term=1 ledgerBegin=300627707 ledgerEnd=313007409 committed=313007409 watermarks={1:{"n0":313007409,"n1":29221071,"n2":313007409}}
2019-12-05 03:38:03 WARN EntryDispatcher-n0-n1 - [Push-n1]Retry to push entry at 29221072
2019-12-05 03:38:03 ERROR EntryDispatcher-n0-n1 - [Push-n1]Error in EntryDispatcher-n0-n1 writeIndex=29222072 compareIndex=-1
io.openmessaging.storage.dledger.exception.DLedgerException: [code=410,name=INDEX_OUT_OF_RANGE,desc=] 29221072 should between 300627707-313007431
        at io.openmessaging.storage.dledger.utils.PreConditions.check(PreConditions.java:41) ~[dledger-0.1.jar:na]
        at io.openmessaging.storage.dledger.store.file.DLedgerMmapFileStore.get(DLedgerMmapFileStore.java:479) ~[dledger-0.1.jar:na]
        at io.openmessaging.storage.dledger.DLedgerEntryPusher$EntryDispatcher.doAppendInner(DLedgerEntryPusher.java:389) ~[dledger-0.1.jar:na]
        at io.openmessaging.storage.dledger.DLedgerEntryPusher$EntryDispatcher.doCheckAppendResponse(DLedgerEntryPusher.java:434) ~[dledger-0.1.jar:na]
        at io.openmessaging.storage.dledger.DLedgerEntryPusher$EntryDispatcher.doAppend(DLedgerEntryPusher.java:461) ~[dledger-0.1.jar:na]
        at io.openmessaging.storage.dledger.DLedgerEntryPusher$EntryDispatcher.doWork(DLedgerEntryPusher.java:602) ~[dledger-0.1.jar:na]
        at io.openmessaging.storage.dledger.ShutdownAbleThread.run(ShutdownAbleThread.java:87) [dledger-0.1.jar:na]
2019-12-05 03:38:04 WARN EntryDispatcher-n0-n1 - [Push-n1]Retry to push entry at 29221072
2019-12-05 03:38:04 ERROR EntryDispatcher-n0-n1 - [Push-n1]Error in EntryDispatcher-n0-n1 writeIndex=29222072 compareIndex=-1
io.openmessaging.storage.dledger.exception.DLedgerException: [code=410,name=INDEX_OUT_OF_RANGE,desc=] 29221072 should between 300627707-313007473
        at io.openmessaging.storage.dledger.utils.PreConditions.check(PreConditions.java:41) ~[dledger-0.1.jar:na]
        at io.openmessaging.storage.dledger.store.file.DLedgerMmapFileStore.get(DLedgerMmapFileStore.java:479) ~[dledger-0.1.jar:na]
        at io.openmessaging.storage.dledger.DLedgerEntryPusher$EntryDispatcher.doAppendInner(DLedgerEntryPusher.java:389) ~[dledger-0.1.jar:na]
        at io.openmessaging.storage.dledger.DLedgerEntryPusher$EntryDispatcher.doCheckAppendResponse(DLedgerEntryPusher.java:434) ~[dledger-0.1.jar:na]
        at io.openmessaging.storage.dledger.DLedgerEntryPusher$EntryDispatcher.doAppend(DLedgerEntryPusher.java:461) ~[dledger-0.1.jar:na]
        at io.openmessaging.storage.dledger.DLedgerEntryPusher$EntryDispatcher.doWork(DLedgerEntryPusher.java:602) ~[dledger-0.1.jar:na]
        at io.openmessaging.storage.dledger.ShutdownAbleThread.run(ShutdownAbleThread.java:87) [dledger-0.1.jar:na]
2019-12-05 03:38:04 WARN EntryDispatcher-n0-n1 - [Push-n1]Retry to push entry at 29221072
2019-12-05 03:38:04 ERROR EntryDispatcher-n0-n1 - [Push-n1]Error in EntryDispatcher-n0-n1 writeIndex=29222072 compareIndex=-1
?ERROR    `

- What did you expect to see?

2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):
 磁盘使用率有可能达到85%
`
2019-12-04 17:29:44 INFO StoreScheduledThread1 - physic disk maybe full soon, so reclaim space, -1.0
2019-12-04 17:29:44 INFO StoreScheduledThread1 - begin to delete before 72 hours file. timeup: false spacefull: true manualDeleteFileSeveralTimes: 0 cleanAtOnce: false
2019-12-04 17:29:54 INFO StoreScheduledThread1 - physic disk maybe full soon, so reclaim space, -1.0
2019-12-04 17:29:54 INFO StoreScheduledThread1 - begin to delete before 72 hours file. timeup: false spacefull: true manualDeleteFileSeveralTimes: 0 cleanAtOnce: false
2019-12-04 17:30:04 INFO StoreScheduledThread1 - physic disk maybe full soon, so reclaim space, -1.0
2019-12-04 17:30:04 INFO StoreScheduledThread1 - begin to delete before 72 hours file. timeup: false spacefull: true manualDeleteFileSeveralTimes: 0 cleanAtOnce: false
2019-12-04 17:30:14 INFO StoreScheduledThread1 - physic disk maybe full soon, so reclaim space, -1.0
2019-12-04 17:30:14 INFO StoreScheduledThread1 - begin to delete before 72 hours file. timeup: false spacefull: true manualDeleteFileSeveralTimes: 0 cleanAtOnce: false
2019-12-04 17:30:24 INFO StoreScheduledThread1 - physic disk maybe full soon, so reclaim space, -1.0
2019-12-04 17:30:24 INFO StoreScheduledThread1 - begin to delete before 72 hours file. timeup: false spacefull: true manualDeleteFileSeveralTimes: 0 cleanAtOnce: false
2019-12-04 17:30:32 INFO StoreStatsService - [STORETPS] put_tps 0.0 get_found_tps 0.0 get_miss_tps 0.0 get_transfered_tps 0.0
2019-12-04 17:30:32 INFO StoreStatsService - [PAGECACHERT] TotalPut 0, PutMessageDistributeTime [<=0ms]:0 [0~10ms]:0 [10~50ms]:0 [50~100ms]:0 [100~200ms]:0 [200~500ms]:0 [500ms~1s]:0 [1~2s]:0 [2~3s]:0 [3~4s]:0 [4~5s]:0 [5~10s]:0 [10s~]:0 
2019-12-04 17:30:34 INFO StoreScheduledThread1 - physic disk maybe full soon, so reclaim space, -1.0
2019-12-04 17:30:34 INFO StoreScheduledThread1 - begin to delete before 72 hours file. timeup: false spacefull: true manualDeleteFileSeveralTimes: 0 cleanAtOnce: false
2019-12-04 17:30:44 INFO StoreScheduledThread1 - physic disk maybe full soon, so reclaim space, -1.0
2019-12-04 17:30:44 INFO StoreScheduledThread1 - begin to delete before 72 hours file. timeup: false spacefull: true manualDeleteFileSeveralTimes: 0 cleanAtOnce: false
2019-12-04 17:30:54 INFO StoreScheduledThread1 - physic disk maybe full soon, so reclaim space, -1.0
2019-12-04 17:30:54 INFO StoreScheduledThread1 - begin to delete before 72 hours file. timeup: false spacefull: true manualDeleteFileSeveralTimes: 0 cleanAtOnce: false
2019-12-04 17:31:04 INFO StoreScheduledThread1 - physic disk maybe full soon, so reclaim space, -1.0
2019-12-04 17:31:04 INFO StoreScheduledThread1 - begin to delete before 72 hours file. timeup: false spacefull: true manualDeleteFileSeveralTimes: 0 cleanAtOnce: false
2019-12-04 17:31:14 INFO StoreScheduledThread1 - physic disk maybe full soon, so reclaim space, -1.0
2019-12-04 17:31:14 INFO StoreScheduledThread1 - begin to delete before 72 hours file. timeup: false spacefull: true manualDeleteFileSeveralTimes: 0 cleanAtOnce: false
2019-12-04 17:31:24 INFO StoreScheduledThread1 - physic disk maybe full soon, so reclaim space, -1.0
2019-12-04 17:31:24 INFO StoreScheduledThread1 - begin to delete before 72 hours file. timeup: false spacefull: true manualDeleteFileSeveralTimes: 0 cleanAtOnce: false
2019-12-04 17:31:32 INFO StoreStatsService - [STORETPS] put_tps 0.0 get_found_tps 0.0 get_miss_tps 0.0 get_transfered_tps 0.0
2019-12-04 17:31:32 INFO StoreStatsService - [PAGECACHERT] TotalPut 0, PutMessageDistributeTime [<=0ms]:0 [0~10ms]:0 [10~50ms]:0 [50~100ms]:0 [100~200ms]:0 [200~500ms]:0 [500ms~1s]:0 [1~2s]:0 [2~3s]:0 [3~4s]:0 [4~5s]:0 [5~10s]:0 [10s~]:0 
2019-12-04 17:31:34 INFO StoreScheduledThread1 - physic disk maybe full soon, so reclaim space, -1.0
2019-12-04 17:31:34 INFO StoreScheduledThread1 - begin to delete before 72 hours file. timeup: false spacefull: true manualDeleteFileSeveralTimes: 0 cleanAtOnce: false
2019-12-04 17:31:44 INFO StoreScheduledThread1 - physic disk maybe full soon, so reclaim space, -1.0
2019-12-04 17:31:44 INFO StoreScheduledThread1 - begin to delete before 72 hours file. timeup: false spacefull: true manualDeleteFileSeveralTimes: 0 cleanAtOnce: false
2019-12-04 17:31:55 INFO StoreStatsService - StoreStatsService service end
2019-12-04 17:31:55 INFO ReputMessageService - ReputMessageService service end
2019-12-04 17:31:55 INFO FlushConsumeQueueService - FlushConsumeQueueService service end
2019-12-04 17:31:55 WARN AllocateMappedFileService - AllocateMappedFileService interrupted, possibly by shutdown.
2019-12-04 17:31:55 INFO AllocateMappedFileService - AllocateMappedFileService service end
2019-12-04 17:31:55 INFO ShutdownHook - /home/rocketmq/store/abort delete OK
`

**Comment by duhenglucky** [comment]
@henrypoter it seems that you used the dledger mode in your test environment, could you provide more information about your broker config?

**Comment by henrypoter** [comment]
> @henrypoter it seems that you used the dledger mode in your test environment, could you provide more information about your broker config?
We use the default config

`[rocketmq@y2zomq213 dledger]$ cat broker.conf 
brokerClusterName = RaftCluster
brokerName=RaftNode00
listenPort=30911
namesrvAddr=192.168.111.212:9876;192.168.111.213:9876;192.168.111.214:9876
enableDLegerCommitLog=true
dLegerGroup=RaftNode00
dLegerPeers=n0-192.168.111.212:40911;n1-192.168.111.213:40911;n2-192.168.111.214:40911
## must be unique
dLegerSelfId=n1
sendMessageThreadPoolNums=16`

the start cmd：
`rocketmq 103137 103133 11 Dec09 ?        04:45:32 /usr/local/jdk1.8.0_151/bin/java -server -Xms8g -Xmx8g -Xmn4g -XX:+UseG1GC -XX:G1HeapRegionSize=16m -XX:G1ReservePercent=25 -XX:InitiatingHeapOccupancyPercent=30 -XX:SoftRefLRUPolicyMSPerMB=0 -verbose:gc -Xloggc:/dev/shm/rmq_broker_gc_%p_%t.log -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCApplicationStoppedTime -XX:+PrintAdaptiveSizePolicy -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=5 -XX:GCLogFileSize=30m -XX:-OmitStackTraceInFastThrow -XX:+AlwaysPreTouch -XX:MaxDirectMemorySize=15g -XX:-UseLargePages -XX:-UseBiasedLocking -Djava.ext.dirs=/usr/local/jdk1.8.0_151/jre/lib/ext:/opt/rocketmq/bin/../lib -cp .:/opt/rocketmq/bin/../conf:.:/usr/local/jdk1.8.0_151/lib:/usr/local/jdk1.8.0_151/jre/lib:.:/usr/local/jdk1.8.0_151/lib:/usr/local/jdk1.8.0_151/jre/lib: org.apache.rocketmq.broker.BrokerStartup -c /opt/rocketmq/conf/dledger-hc/broker.conf`
