### ISSUE TITLE
An AclException was throwed when I used mqadmin command to updateTopic

### ISSUE THREAD

**Issue by a13707331174** [apache/rocketmq#1711]
我的rocketmq已经设置aclEnable, 并且我将管理员的accessKey从原来的rocketmq2改成了自定义的admin12345678, 当我用mqadmin命令执行updateTopic时,会报rocketmq2用户没有配置. 

> org.apache.rocketmq.acl.common.AclException:  No acl config for **rocketmq2,** 

这是为什么呢,? 或者怎么在updateTopic命令传入配置的管理员用户名和密码?
报错如下
```java
org.apache.rocketmq.tools.command.SubCommandException: UpdateTopicSubCommand command failed
	at org.apache.rocketmq.tools.command.topic.UpdateTopicSubCommand.execute(UpdateTopicSubCommand.java:185)
	at org.apache.rocketmq.tools.command.MQAdminStartup.main0(MQAdminStartup.java:139)
	at org.apache.rocketmq.tools.command.MQAdminStartup.main(MQAdminStartup.java:90)
Caused by: org.apache.rocketmq.client.exception.MQClientException: CODE: 1  DESC: org.apache.rocketmq.acl.common.AclException:  No acl config for rocketmq2, org.apache.rocketmq.acl.plain.PlainPermissionManager.validate(PlainPermissionManager.java:398)

```
配置文件如下:
```java
- accessKey: admin12345678
  secretKey: admin12345678
  whiteRemoteAddress:
  admin: true

```

when i set acl enabled and change the default admin  accessKey and then if I use mqadmin command to updateTopic , there would be an exception throwed.

**Comment by a13707331174** [comment]
Only if i change the accessKey of admin to the default, updateTopicCommand could work

**Comment by zongtanghu** [comment]
Which acl config file do you rewrite?Is the plain_acl.yml or tools.yml? @a13707331174

**Comment by a13707331174** [comment]
@zongtanghu Only plain_acl.yml. I have solved by add local host ip under _globalWhiteRemoteAddresses_ , thanks

**Comment by hppx5456** [comment]
我也遇到了同样的问题，按照你的方法并没有解决

**Comment by shengulong** [comment]
> 我也遇到了同样的问题，按照你的方法并没有解决

版本4.8.0

**Comment by lvyanru8200** [comment]
> > 我也遇到了同样的问题，按照你的方法并没有解决
> 
> 版本4.8.0
> 
> 1. 检查下配置conf / plain_acl.yml的正确性
> 2. mqadmin的授权配置在conf / tools.yml下，注意和上面配置的accessKey / secretKey的一致性

4.6.1没效果啊
