### ISSUE TITLE
CODE: 24  DESC: the consumer's group info not exist

### ISSUE THREAD

**Issue by debugsw** [apache/rocketmq#1871]
2020-03-19 16:33:02 WARN NettyClientPublicExecutor_1 - execute the pull request exception
org.apache.rocketmq.client.exception.MQBrokerException: CODE: 24  DESC: the consumer's group info not exist
See http://rocketmq.apache.org/docs/faq/ for further details.
 at org.apache.rocketmq.client.impl.MQClientAPIImpl.processPullResponse(MQClientAPIImpl.java:640)
 at org.apache.rocketmq.client.impl.MQClientAPIImpl.access$200(MQClientAPIImpl.java:155)
 at org.apache.rocketmq.client.impl.MQClientAPIImpl$2.operationComplete(MQClientAPIImpl.java:592)
 at org.apache.rocketmq.remoting.netty.ResponseFuture.executeInvokeCallback(ResponseFuture.java:51)
 at org.apache.rocketmq.remoting.netty.NettyRemotingAbstract$2.run(NettyRemotingAbstract.java:286)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 at java.lang.Thread.run(Thread.java:748)

Today, this exception has always occurred in the production environment, resulting in no consumption of the production environment messages, and all consumers are offline. Finally, restart rockermq directly and it will return to normal. What is the cause of this abnormality.

**Comment by xujianhai666** [comment]
@debugsw  broker does not hava group subcription and  not open autoCreateSubscription. pls check

**Comment by debugsw** [comment]
> @debugsw broker does not hava group subcription and not open autoCreateSubscription. pls check

broker does not hava group subcription and not open autoCreateSubscription. pls check . If this one is not enabled and configured, it has been running normally before. Only on that day did this problem suddenly occur. After the restart, this problem never occurred again. I don't know why. I don't know if the actual memory leak will cause this problem.

**Comment by wlliqipeng** [comment]
In the same consume group, this situation may happen, if different consumer instances have subscribed to different topics. so you should better the usage of RocketMQ.

**Comment by wlliqipeng** [comment]
Issues are generally used for bug reports and feature requests, so if you have any questions about     Apache  RocketMQ, it is recommended to discuss it on the mailing list first, the mailing list [address]    (https://rocketmq.apache.org/about/contact). I will close the Issue first, but please feel free to reopen it if you have any other issues.
