### ISSUE TITLE
start broker failed,the log shows NoSuchMethodError

### ISSUE THREAD

**Issue by landon30** [apache/rocketmq#1927]
# environment
   - jdk: 1.8.0_241
   - rocketmq: 4.7.0

# reproduce 
- nohup sh bin/mqbroker -n localhost:9876 &
-  [reference](https://rocketmq.apache.org/docs/quick-start/)

# error log: `java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer`
  ```
     2020-04-09 18:02:42 WARN brokerOutApi_thread_1 - registerBroker Exception, localhost:9876
org.apache.rocketmq.remoting.exception.RemotingSendRequestException: send request to <ocalhost/127.0.0.1:9876> failed
        at org.apache.rocketmq.remoting.netty.NettyRemotingAbstract.invokeSyncImpl(NettyRemotingAbstract.java:440) ~[rocketmq-remoting-4.7.0.jar:4.7.0]
        at org.apache.rocketmq.remoting.netty.NettyRemotingClient.invokeSync(NettyRemotingClient.java:373) ~[rocketmq-remoting-4.7.0.jar:4.7.0]
        at org.apache.rocketmq.broker.out.BrokerOuterAPI.registerBroker(BrokerOuterAPI.java:194) ~[rocketmq-broker-4.7.0.jar:4.7.0]
        at org.apache.rocketmq.broker.out.BrokerOuterAPI.access$000(BrokerOuterAPI.java:61) ~[rocketmq-broker-4.7.0.jar:4.7.0]
        at org.apache.rocketmq.broker.out.BrokerOuterAPI$1.run(BrokerOuterAPI.java:150) ~[rocketmq-broker-4.7.0.jar:4.7.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_241]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_241]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_241]
Caused by: io.netty.handler.codec.EncoderException: java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125) ~[netty-all-4.0.42.Final.jar:4.0.42.Final]
   ```

**Comment by landon30** [comment]
my temporary solution is change the netty version from 4.0.42 final to 4.0.43 final in the pom.xml.
it works.

**Comment by duhenglucky** [comment]
@landon30 could you tell me which JDK version you used? it seems that you used the JDK version > 1.8

**Comment by landon30** [comment]
@duhenglucky see the first comment: 1.8.0_241

**Comment by xiaozi0lei** [comment]
Meet the same issue.

Java Version:
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)

RocketMQ version:
rocketmq-4.7.1


Interesting things below:
```java
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140) ~[netty-all-4.0.42.Final.jar:4.0.42.Final]
        ... 1 common frames omitted
Caused by: java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
        at org.apache.rocketmq.remoting.protocol.RemotingCommand.encodeHeader(RemotingCommand.java:427) ~[rocketmq-remoting-4.7.1.jar:4.7.1]
        at org.apache.rocketmq.remoting.protocol.RemotingCommand.encodeHeader(RemotingCommand.java:400) ~[rocketmq-remoting-4.7.1.jar:4.7.1]
        at org.apache.rocketmq.remoting.netty.NettyEncoder.encode(NettyEncoder.java:38) ~[rocketmq-remoting-4.7.1.jar:4.7.1]
        at org.apache.rocketmq.remoting.netty.NettyEncoder.encode(NettyEncoder.java:30) ~[rocketmq-remoting-4.7.1.jar:4.7.1]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-all-4.0.42.Final.jar:4.0.42.Final]
        ... 19 common frames omitted
2020-07-15 15:40:06 INFO ShutdownHook - Try to shutdown service thread:FileWatchService started:false lastThread:Thread[FileWatchService,5,]
2020-07-15 15:40:06 INFO ShutdownHook - Try to shutdown service thread:TransactionalMessageCheckService started:true lastThread:Thread[TransactionalMessageCheckService,5,main]
2020-07-15 15:40:06 INFO ShutdownHook - shutdown thread TransactionalMessageCheckService interrupt false
2020-07-15 15:40:06 INFO ShutdownHook - join thread TransactionalMessageCheckService elapsed time(ms) 1 90000
2020-07-15 15:40:06 INFO ShutdownHook - Shutdown hook over, consuming total time(ms): 4585
2020-07-15 15:42:55 INFO main - rocketmqHome=/Users/xiaoneng/webserver/rocketmq-all-4.7.1-source-release/distribution/target/rocketmq-4.7.1/rocketmq-4.7.1
2020-07-15 15:42:55 INFO main - namesrvAddr=10.30.127.220:9876
2020-07-15 15:42:55 INFO main - brokerIP1=10.30.127.220
2020-07-15 15:42:55 INFO main - brokerIP2=10.30.127.220
2020-07-15 15:42:55 INFO main - brokerName=xiaonengdeMac-Pro.local
2020-07-15 15:42:55 INFO main - brokerClusterName=DefaultCluster
2020-07-15 15:42:55 INFO main - brokerId=0
```

After many Exceptions, the broker restart itself. **The important Thing** is that the broker register successfully and no Exception throws.
```java
2020-07-15 15:56:06 INFO brokerOutApi_thread_4 - register broker[0]to name server 10.30.127.220:9876 OK
2020-07-15 15:56:36 INFO brokerOutApi_thread_1 - register broker[0]to name server 10.30.127.220:9876 OK
2020-07-15 15:57:06 INFO BrokerControllerScheduledThread1 - dispatch behind commit log 0 bytes
2020-07-15 15:57:06 INFO BrokerControllerScheduledThread1 - Slave fall behind master: 0 bytes
2020-07-15 15:57:06 INFO brokerOutApi_thread_2 - register broker[0]to name server 10.30.127.220:9876 OK
2020-07-15 15:57:36 INFO brokerOutApi_thread_3 - register broker[0]to name server 10.30.127.220:9876 OK
2020-07-15 15:58:06 INFO BrokerControllerScheduledThread1 - dispatch behind commit log 0 bytes
2020-07-15 15:58:06 INFO BrokerControllerScheduledThread1 - Slave fall behind master: 0 bytes
2020-07-15 15:58:06 INFO brokerOutApi_thread_4 - register broker[0]to name server 10.30.127.220:9876 OK
2020-07-15 15:58:36 INFO brokerOutApi_thread_1 - register broker[0]to name server 10.30.127.220:9876 OK
```

**Comment by xiaofanTo** [comment]
I meet the same issue and how do you solve this problem。

**Comment by vnhim** [comment]
I had the same issue but it was because I was building the distribution with a java version > 8...

Hope this help

**Comment by ssi-anik** [comment]
@vnhim I have been trying to build the `rocketmq-console` from the external project for the last 4/5 days. Was building locally on Java 14, was using it in java 8 docker container. Why don't they just maintain a jar for the latest releases?! -_- -_-
