### ISSUE TITLE
windows下通过BrokerStartup#main启动broker，路径会被解析为换行符，导致文件找不到FileNotFoundException

### ISSUE THREAD

**Issue by AndrewRitchieTsai** [apache/rocketmq#1975]
开发者您好：
我在windows下启动rocketmq的store时候，会出现文件路径的FileNotFoundException错误，导致store无法启动。

问题复现：
windows下通过`BrokerStartup#main`启动broker，并且在启动前已经配置环境变量ROCKETMQ_HOME 为`D:\rocketmq-nameserver`，broker.conf中的所有路径信息配置成 诸如 `storePathRootDir= D:\rocketmq-nameserver\store` 这样的单斜杠

问题原因：
是因为第一个 ‘\r’  会被解析为换行符。导致配置文件出错。这不算是一个错误，我希望在此能给初学者提供帮助。如果可以，希望开发者能够添加更加严谨的路径解析规则。

临时解决办法：将所有路径配置为双斜杠。
例子：`storePathRootDir= D:\\rocketmq-nameserver\\store`

详细错误信息如下：
`2020-05-07 14:44:48 ERROR main - Failed to initialize
java.io.FileNotFoundException: D:
ocketmq-nameserverstore\lock (文件名、目录名或卷标语法不正确。)
	at java.io.RandomAccessFile.open0(Native Method) ~[na:1.8.0_191]
	at java.io.RandomAccessFile.open(RandomAccessFile.java:316) ~[na:1.8.0_191]
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243) ~[na:1.8.0_191]
	at org.apache.rocketmq.store.DefaultMessageStore.<init>(DefaultMessageStore.java:161) ~[classes/:na]
	at org.apache.rocketmq.broker.BrokerController.initialize(BrokerController.java:244) ~[classes/:na]
	at org.apache.rocketmq.broker.BrokerStartup.createBrokerController(BrokerStartup.java:222) [classes/:na]
	at org.apache.rocketmq.broker.BrokerStartup.main(BrokerStartup.java:58) [classes/:na]
2020-05-07 14:44:48 INFO main - Try to shutdown service thread:PullRequestHoldService started:false lastThread:null
2020-05-07 14:44:48 ERROR main - persist file D:
ocketmq-nameserverstore\config\consumerOffset.json exception
java.io.FileNotFoundException: D:
ocketmq-nameserverstore\config\consumerOffset.json.tmp (文件名、目录名或卷标语法不正确。)
	at java.io.FileOutputStream.open0(Native Method) ~[na:1.8.0_191]
	at java.io.FileOutputStream.open(FileOutputStream.java:270) ~[na:1.8.0_191]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213) ~[na:1.8.0_191]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162) ~[na:1.8.0_191]
	at java.io.FileWriter.<init>(FileWriter.java:90) ~[na:1.8.0_191]
	at org.apache.rocketmq.common.MixAll.string2FileNotSafe(MixAll.java:178) ~[classes/:na]
	at org.apache.rocketmq.common.MixAll.string2File(MixAll.java:154) ~[classes/:na]
	at org.apache.rocketmq.common.ConfigManager.persist(ConfigManager.java:75) ~[classes/:na]
	at org.apache.rocketmq.broker.BrokerController.shutdown(BrokerController.java:801) [classes/:na]
	at org.apache.rocketmq.broker.BrokerStartup.createBrokerController(BrokerStartup.java:224) [classes/:na]
	at org.apache.rocketmq.broker.BrokerStartup.main(BrokerStartup.java:58) [classes/:na]
2020-05-07 14:44:48 ERROR main - persist file D:
ocketmq-nameserverstore\config\consumerFilter.json exception`

**Comment by duhenglucky** [comment]
@AndrewRitchieTsai 非常赞的总结，如果能够补充到文档中就好了，可以提个PR。

**Comment by bearxsh** [comment]
我也遇到了 感谢

**Comment by duhenglucky** [comment]
> 我也遇到了 感谢

同学，可以整理下提个PR 到文档目录吗？https://github.com/apache/rocketmq/tree/master/docs/cn

**Comment by AndrewRitchieT** [comment]
尴尬，一直没有提是因为我不知道该往哪里提。。。

**Comment by AndrewRitchieT** [comment]
我觉得 应该提交在 https://github.com/apache/rocketmq/blob/master/docs/cn/Configuration_System.md 比较方便大家在windows下 避开这个问题。
