### ISSUE TITLE
SendMessageProcessor.handleRetryAndDLQ(SendMessageProcessor.java:271) NPE

### ISSUE THREAD

**Issue by powellsz** [apache/rocketmq#2055]
java.lang.NullPointerException: null
        at org.apache.rocketmq.broker.processor.SendMessageProcessor.handleRetryAndDLQ(SendMessageProcessor.java:271) ~[rocketmq-broker-4.6.1.jar:4.6.1]
        at org.apache.rocketmq.broker.processor.SendMessageProcessor.sendMessage(SendMessageProcessor.java:339) ~[rocketmq-broker-4.6.1.jar:4.6.1]
        at org.apache.rocketmq.broker.processor.SendMessageProcessor.processRequest(SendMessageProcessor.java:85) ~[rocketmq-broker-4.6.1.jar:4.6.1]
        at org.apache.rocketmq.remoting.netty.NettyRemotingAbstract$1.run(NettyRemotingAbstract.java:203) ~[rocketmq-remoting-4.6.1.jar:4.6.1]
        at org.apache.rocketmq.remoting.netty.RequestTask.run(RequestTask.java:80) [rocketmq-remoting-4.6.1.jar:4.6.1]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_231]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_231]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_231]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_231]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_231]

经过核对代码，4.7.0存在同样问题，问题代码如下，隐式转化带来的npe:

问题代码：

int maxReconsumeTimes = subscriptionGroupConfig.getRetryMaxTimes();
            if (request.getVersion() >= MQVersion.Version.V3_4_9.ordinal()) {
                maxReconsumeTimes = requestHeader.getMaxReconsumeTimes(); //存在隐式转换
            }

**Comment by maixiaohai** [comment]
@RealBar we meet the same problem. Could you fix your code style, I will help to merge.

**Comment by duhenglucky** [comment]
merged
