### ISSUE TITLE
When producer send batch messages, show me an exception. RocketMQ Cluster is dledger mode, What can I do

### ISSUE THREAD

**Issue by newlipeng** [apache/rocketmq#2139]
org.apache.rocketmq.client.exception.MQBrokerException: CODE: 13  DESC: the message is illegal, maybe msg body or properties length not matched. msg body length limit 128k, msg properties length limit 32k.
For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.processSendResponse(MQClientAPIImpl.java:709)
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessageSync(MQClientAPIImpl.java:505)
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessage(MQClientAPIImpl.java:487)
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessage(MQClientAPIImpl.java:431)

I test at 2m-2s-sync mode, this code works; at dledger conf (cluster mode), it got an exception.
code:
Message msg = new Message("TestTopic","TagA","order1", ("Hello RocketMQ " +i).getBytes());
msgs.add(msg);
SendResult sendResult = producer.send(msgs);

**Comment by henrypoter** [comment]
dledger mode do not support batch messages

**Comment by zcwease** [comment]
我也遇到过

**Comment by RongtongJin** [comment]
Fixed

**Comment by vongosling** [comment]
You could upgrade to version 4.8.0~
