### ISSUE TITLE
There are always errors in namesrv.log.

### ISSUE THREAD

**Issue by andyhewenhui** [apache/rocketmq#2164]
There are always errors in namesrv.log. We have not configured the underlying ip netty connection. Why is namesrv always connected incorrectly? see blow
2020-07-16 09:59:36 INFO NettyServerCodecThread_1 - NETTY SERVER PIPELINE: channelRegistered 100.122.104.66:38535
2020-07-16 09:59:36 INFO NettyServerCodecThread_1 - NETTY SERVER PIPELINE: channelActive, the channel[100.122.104.66:38535]
2020-07-16 09:59:36 WARN NettyServerCodecThread_1 - NETTY SERVER PIPELINE: exceptionCaught 100.122.104.66:38535
2020-07-16 09:59:36 WARN NettyServerCodecThread_1 - NETTY SERVER PIPELINE: exceptionCaught exception.
java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:1.8.0_252]
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:1.8.0_252]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_252]
        at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.8.0_252]
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:377) ~[na:1.8.0_252]
        at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:221) ~[netty-all-4.0.42.Final.jar:4.0.42.Final]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:899) ~[netty-all-4.0.42.Final.jar:4.0.42.Final]
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:275) ~[netty-all-4.0.42.Final.jar:4.0.42.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119) ~[netty-all-4.0.42.Final.jar:4.0.42.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:652) ~[netty-all-4.0.42.Final.jar:4.0.42.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:575) ~[netty-all-4.0.42.Final.jar:4.0.42.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:489) ~[netty-all-4.0.42.Final.jar:4.0.42.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:451) ~[netty-all-4.0.42.Final.jar:4.0.42.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140) [netty-all-4.0.42.Final.jar:4.0.42.Final]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_252]
2020-07-16 09:59:36 INFO NettyServerCodecThread_1 - NETTY SERVER PIPELINE: channelInactive, the channel[100.122.104.66:38535]
2020-07-16 09:59:36 INFO NettyServerCodecThread_1 - NETTY SERVER PIPELINE: channelUnregistered, the channel[100.122.104.66:38535]
2020-07-16 09:59:36 INFO NettyServerNIOSelector_3_3 - closeChannel: close the connection to remote address[100.122.104.66:38535] result: true

**Comment by andyhewenhui** [comment]
I did a load balancing in front of 2 namesrv. It's not because of this, is it?

**Comment by andyhewenhui** [comment]
Use Ali Cloud's load balancer to do tcp layer 4 switching namesrv
