### ISSUE TITLE
Failed to start RocketMQ push consumer because of com.alibaba.fastjson.JSONException

### ISSUE THREAD

**Issue by leyan95** [apache/rocketmq#2322]
## 本地offset.json文件n内容
![image](https://user-images.githubusercontent.com/35946000/94354810-8c6b8480-00b1-11eb-857a-c7fe4f109c9b.png)

## 报错位置
![image](https://user-images.githubusercontent.com/35946000/94354855-e5d3b380-00b1-11eb-8056-0bd39fef56c6.png)

## 异常栈信息
```java
11:10:35.591 ERROR [main] o.a.r.s.a.ListenerContainerConfiguration  --  Started container failed. DefaultRocketMQListenerContainer{consumerGroup='T-BisPersistence-Group', nameServer='172.0.66.110:9876', topic='T-BisPersistence', consumeMode=CONCURRENTLY, selectorType=TAG, selectorExpression='*', messageModel=BROADCASTING}
java.lang.IllegalStateException: Failed to start RocketMQ push consumer
	at org.apache.rocketmq.spring.support.DefaultRocketMQListenerContainer.start(DefaultRocketMQListenerContainer.java:281) ~[rocketmq-spring-boot-2.1.0.jar:2.1.0]
	at org.apache.rocketmq.spring.autoconfigure.ListenerContainerConfiguration.registerContainer(ListenerContainerConfiguration.java:120) ~[rocketmq-spring-boot-2.1.0.jar:2.1.0]
	at java.util.HashMap.forEach(HashMap.java:1289) ~[na:1.8.0_201]
	at org.apache.rocketmq.spring.autoconfigure.ListenerContainerConfiguration.afterSingletonsInstantiated(ListenerContainerConfiguration.java:79) ~[rocketmq-spring-boot-2.1.0.jar:2.1.0]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:776) ~[spring-beans-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867) ~[spring-context-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:548) ~[spring-context-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) ~[spring-boot-2.0.6.RELEASE.jar:2.0.6.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[spring-boot-2.0.6.RELEASE.jar:2.0.6.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:386) ~[spring-boot-2.0.6.RELEASE.jar:2.0.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307) ~[spring-boot-2.0.6.RELEASE.jar:2.0.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1242) ~[spring-boot-2.0.6.RELEASE.jar:2.0.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1230) ~[spring-boot-2.0.6.RELEASE.jar:2.0.6.RELEASE]
	at com.shinowx.bloodcollection.IntelligentBloodCollectionApplication.main(IntelligentBloodCollectionApplication.java:15) ~[classes/:na]
Caused by: org.apache.rocketmq.client.exception.MQClientException: readLocalOffset Exception, maybe fastjson version too low
See http://rocketmq.apache.org/docs/faq/ for further details.
	at org.apache.rocketmq.client.consumer.store.LocalFileOffsetStore.readLocalOffsetBak(LocalFileOffsetStore.java:221) ~[rocketmq-client-4.6.0.jar:4.6.0]
	at org.apache.rocketmq.client.consumer.store.LocalFileOffsetStore.readLocalOffset(LocalFileOffsetStore.java:199) ~[rocketmq-client-4.6.0.jar:4.6.0]
	at org.apache.rocketmq.client.consumer.store.LocalFileOffsetStore.load(LocalFileOffsetStore.java:63) ~[rocketmq-client-4.6.0.jar:4.6.0]
	at org.apache.rocketmq.client.impl.consumer.DefaultMQPushConsumerImpl.start(DefaultMQPushConsumerImpl.java:610) ~[rocketmq-client-4.6.0.jar:4.6.0]
	at org.apache.rocketmq.client.consumer.DefaultMQPushConsumer.start(DefaultMQPushConsumer.java:693) ~[rocketmq-client-4.6.0.jar:4.6.0]
	at org.apache.rocketmq.spring.support.DefaultRocketMQListenerContainer.start(DefaultRocketMQListenerContainer.java:279) ~[rocketmq-spring-boot-2.1.0.jar:2.1.0]
	... 13 common frames omitted
Caused by: com.alibaba.fastjson.JSONException: syntax error, expect {, actual EOF, pos 406, fastjson-version 1.2.61
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:489) ~[fastjson-1.2.61.jar:na]
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.parseRest(JavaBeanDeserializer.java:1539) ~[fastjson-1.2.61.jar:na]
	at com.alibaba.fastjson.parser.deserializer.FastjsonASMDeserializer_9_OffsetSerializeWrapper.deserialze(Unknown Source) ~[na:na]
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:284) ~[fastjson-1.2.61.jar:na]
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:682) ~[fastjson-1.2.61.jar:na]
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:383) ~[fastjson-1.2.61.jar:na]
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:287) ~[fastjson-1.2.61.jar:na]
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:560) ~[fastjson-1.2.61.jar:na]
	at org.apache.rocketmq.remoting.protocol.RemotingSerializable.fromJson(RemotingSerializable.java:43) ~[rocketmq-remoting-4.6.0.jar:4.6.0]
	at org.apache.rocketmq.client.consumer.store.LocalFileOffsetStore.readLocalOffsetBak(LocalFileOffsetStore.java:217) ~[rocketmq-client-4.6.0.jar:4.6.0]
	... 18 common frames omitted
```

**Comment by RongtongJin** [comment]
same issue #1498
