### ISSUE TITLE
load `org.apache.rocketmq.client.trace.TraceBean` class throw `Can not get local ip`

### ISSUE THREAD

**Issue by geektao** [apache/rocketmq#2374]
TraceBean has a constant field `LOCAL_ADDRESS` , initialize by static method `UtilAll.getIP()`。The static method’s implementation ignore some ip address  (like:  start with 254 ) by private method `UtilAll.ipCheck()`  。Finally ，when ip address started with 254 will lead to `Can not get local ip` Exception.

````
java.lang.ExceptionInInitializerError: null
	at org.apache.rocketmq.client.trace.hook.ConsumeMessageTraceHookImpl.consumeMessageBefore(ConsumeMessageTraceHookImpl.java:58)
	at org.apache.rocketmq.client.impl.consumer.DefaultMQPushConsumerImpl.executeHookBefore(DefaultMQPushConsumerImpl.java:140)
	at org.apache.rocketmq.client.impl.consumer.ConsumeMessageConcurrentlyService$ConsumeRequest.run(ConsumeMessageConcurrentlyService.java:400)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Can not get local ip
	at org.apache.rocketmq.common.UtilAll.getIP(UtilAll.java:562)
	at org.apache.rocketmq.client.trace.TraceBean.<clinit>(TraceBean.java:23)
	... 8 common frames omitted
Caused by: java.lang.RuntimeException: Can not get local ip
	at org.apache.rocketmq.common.UtilAll.getIP(UtilAll.java:559)
	... 9 common frames omitted
````

**Comment by vongosling** [comment]
It seems the ipCheck method has some problems. @geektao would you like to fix the error? @RongtongJin

**Comment by geektao** [comment]
I have no idea to fix ipCheck method. I just replace `LOCAL_ADDRESS` value  with the `RemotingUtil.getLocalAddress()` method. @vongosling

**Comment by zhangjidi2016** [comment]
[https://github.com/apache/rocketmq/pull/2376](url)
I have submitted a PR to fix this issue, please help to review it. @vongosling
