### ISSUE TITLE
BUG still exists ！！！！！！ Create reply message fail because property[CLUSTER] is null

### ISSUE THREAD

**Issue by allankin** [apache/rocketmq#2438]
my pom contains : 

> 		
		<dependency>
			<groupId>org.apache.rocketmq</groupId>
			<artifactId>rocketmq-spring-boot-starter</artifactId>
			<version>2.1.1</version>
		</dependency>
		 

pls tell me how can I fix this problem .... thanks very much !!!

error log:

ReplyMessageConsumer message: hello-1605766759845
2020-11-19 14:26:13.407 WARN 20320 --- [essageThread_15] a.r.s.s.DefaultRocketMQListenerContainer : consume message failed. messageExt:MessageExt [brokerName=broker-a, queueId=0, storeSize=524, queueOffset=123, sysFlag=0, bornTimestamp=1605766759846, bornHost=/172.16.27.28:63121, storeTimestamp=1605767173594, storeHost=/192.168.5.87:10911, msgId=C0A8055700002A9F000000000FAB8155, commitLogOffset=262898005, bodyCRC=1356135967, reconsumeTimes=5, preparedTransactionOffset=0, toString()=Message{topic='kim-test-topic', flag=0, properties={CONSUME_START_TIME=1605767173406, TTL=3000, MIN_OFFSET=0, REAL_TOPIC=%RETRY%greeting-group, REPLY_TO_CLIENT=172.16.27.28@1752, ORIGIN_MESSAGE_ID=C0A8055700002A9F000000000FAB0A49, RETRY_TOPIC=kim-test-topic, MAX_OFFSET=124, id=65a41aff-2fec-e790-edfb-0d2fb22be6ec, UNIQ_KEY=AC101B1C06D81F89AB835FC535A60009, WAIT=false, contentType=text/plain;charset=UTF-8, DELAY=7, TAGS=greeting, timestamp=1605766759845, CORRELATION_ID=83c8c44d-88b3-49a5-b983-293c01c0070f, REAL_QID=0}, body=[104, 101, 108, 108, 111, 45, 49, 54, 48, 53, 55, 54, 54, 55, 53, 57, 56, 52, 53], transactionId='null'}], error:{}

org.apache.rocketmq.client.exception.MQClientException: CODE: 10007 DESC: create reply message fail, requestMessage error, property[CLUSTER] is null.
For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
at org.apache.rocketmq.client.utils.MessageUtil.createReplyMessage(MessageUtil.java:46) ~[rocketmq-client-4.7.1.jar:4.7.1]
at org.apache.rocketmq.spring.support.DefaultRocketMQListenerContainer.handleMessage(DefaultRocketMQListenerContainer.java:399) ~[rocketmq-spring-boot-2.1.1.jar:2.1.1]
at org.apache.rocketmq.spring.support.DefaultRocketMQListenerContainer.access$100(DefaultRocketMQListenerContainer.java:70) ~[rocketmq-spring-boot-2.1.1.jar:2.1.1]
at org.apache.rocketmq.spring.support.DefaultRocketMQListenerContainer$DefaultMessageListenerConcurrently.consumeMessage(DefaultRocketMQListenerContainer.java:354) ~[rocketmq-spring-boot-2.1.1.jar:2.1.1]
at org.apache.rocketmq.client.impl.consumer.ConsumeMessageConcurrentlyService$ConsumeRequest.run(ConsumeMessageConcurrentlyService.java:412) ~[rocketmq-client-4.7.1.jar:4.7.1]
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

**Comment by allankin** [comment]
upgrade rocket server to 4.7.1 , soloved

**Comment by vongosling** [comment]
Please be aware of the consequences of the way you ask questions in the community.

**Comment by allankin** [comment]
> Please be aware of the consequences of the way you ask questions in the community.

so pls give me a favor to how to ask question?
