### ISSUE TITLE
try to load backup file com.alibaba.fastjson.JSONException: syntax error, expect {, actual EOF, pos 38, fastjson-version 1.2.61

### ISSUE THREAD

**Issue by Donaldhan** [apache/rocketmq#2531]
# OS
window 10
# rocketmq version
4.6.0
# problem
start the broker fail;
# operate step
1. start namesrv;
2. star broker;

then get follow error log
```
2020-12-29 22:43:11 INFO main - load C:\Users\Donald_Draper\store\config\subscriptionGroup.json OK
2020-12-29 22:43:11 INFO main - load C:\Users\Donald_Draper\store\config\consumerFilter.json OK
2020-12-29 22:43:11 INFO main - Try to start service thread:AllocateMappedFileService started:false lastThread:null
2020-12-29 22:43:11 ERROR main - load C:\Users\Donald_Draper\store\config\delayOffset.json failed, and try to load backup file
com.alibaba.fastjson.JSONException: syntax error, expect {, actual EOF, pos 38, fastjson-version 1.2.61
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:489) ~[fastjson-1.2.61.jar:na]
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.parseRest(JavaBeanDeserializer.java:1539) ~[fastjson-1.2.61.jar:na]
	at com.alibaba.fastjson.parser.deserializer.FastjsonASMDeserializer_7_DelayOffsetSerializeWrapper.deserialze(Unknown Source) ~[na:na]
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:284) ~[fastjson-1.2.61.jar:na]
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:682) ~[fastjson-1.2.61.jar:na]
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:383) ~[fastjson-1.2.61.jar:na]
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:287) ~[fastjson-1.2.61.jar:na]
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:560) ~[fastjson-1.2.61.jar:na]
	at org.apache.rocketmq.remoting.protocol.RemotingSerializable.fromJson(RemotingSerializable.java:43) ~[rocketmq-remoting-4.6.0.jar:4.6.0]
	at org.apache.rocketmq.store.schedule.ScheduleMessageService.decode(ScheduleMessageService.java:179) [rocketmq-store-4.6.0.jar:4.6.0]
	at org.apache.rocketmq.common.ConfigManager.load(ConfigManager.java:38) ~[rocketmq-common-4.6.0.jar:4.6.0]
	at org.apache.rocketmq.store.schedule.ScheduleMessageService.load(ScheduleMessageService.java:164) [rocketmq-store-4.6.0.jar:4.6.0]
	at org.apache.rocketmq.store.DefaultMessageStore.load(DefaultMessageStore.java:184) [rocketmq-store-4.6.0.jar:4.6.0]
	at org.apache.rocketmq.broker.BrokerController.initialize(BrokerController.java:261) [rocketmq-broker-4.6.0.jar:4.6.0]
	at org.apache.rocketmq.broker.BrokerStartup.createBrokerController(BrokerStartup.java:222) [rocketmq-broker-4.6.0.jar:4.6.0]
	at org.apache.rocketmq.broker.BrokerStartup.main(BrokerStartup.java:58) [rocketmq-broker-4.6.0.jar:4.6.0]
2020-12-29 22:43:11 ERROR main - load C:\Users\Donald_Draper\store\config\delayOffset.json Failed
```

when i open the file (C:\Users\Donald_Draper\store\config\delayOffset.json), is blank;
empty file , while deserializable error???

then delete the file . repeate start namesrv and broker, all is normal. what's the reason?

**Comment by maixiaohai** [comment]
You can check if there are different version of fastjson dependency, we met the same exception with gson before.
