### ISSUE TITLE
No topic route info in name server for the topic: TBW102

### ISSUE THREAD

**Issue by amwyyyy** [apache/rocketmq#2545]
Version: rocketmq-client:4.7.1

We use rocketmq-client to connect to aliyun RocketMQ(ONS), When upgrade from rocketmq-client:4.5.1 to rocketmq-client:4.7.1, the following error log appears: 
```
2021-01-04 15:20:19,019 WARN RocketmqClient - updateTopicRouteInfoFromNameServer Exception
org.apache.rocketmq.client.exception.MQClientException: CODE: 17  DESC: No topic route info in name server for the topic: TBW102
See http://rocketmq.apache.org/docs/faq/ for further details.
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.getTopicRouteInfoFromNameServer(MQClientAPIImpl.java:1383)
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.getTopicRouteInfoFromNameServer(MQClientAPIImpl.java:1353)
	at org.apache.rocketmq.client.impl.factory.MQClientInstance.updateTopicRouteInfoFromNameServer(MQClientInstance.java:622)
	at org.apache.rocketmq.client.impl.factory.MQClientInstance.updateTopicRouteInfoFromNameServer(MQClientInstance.java:509)
	at org.apache.rocketmq.client.impl.factory.MQClientInstance.updateTopicRouteInfoFromNameServer(MQClientInstance.java:358)
	at org.apache.rocketmq.client.impl.factory.MQClientInstance$3.run(MQClientInstance.java:275)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
![image](https://user-images.githubusercontent.com/8274512/103516312-43df1680-4eab-11eb-8610-7bab371b009a.png)
![image](https://user-images.githubusercontent.com/8274512/103516318-46da0700-4eab-11eb-8fbc-267220d7a0b1.png)
Comparing the code of the two versions, it is found that modified here.

What can I do to avoid printing warn logs?

**Comment by shenhui0509** [comment]
Is the property `autoCreateTopicEnable` of broker set to true?

**Comment by amwyyyy** [comment]
> Is the property `autoCreateTopicEnable` of broker set to true?

This is Aliyun MQ service

**Comment by Memode** [comment]
解决了吗 @amwyyyy

**Comment by amwyyyy** [comment]
> 解决了吗 @amwyyyy

换到4.6.1版本就没有打印，这个也不影响功能，不理也行。
