### ISSUE TITLE
 DESC: create mapped file failed, server is busy or broken. BROKER: xxx.xxx.x.x:10911

### ISSUE THREAD

**Issue by Cacle** [apache/rocketmq#2612]
rocketmq  is 4.8.0

**Comment by Cacle** [comment]
Exception in thread "main" org.apache.rocketmq.client.exception.MQClientException: Send [3] times, still failed, cost [867]ms, Topic: test, BrokersSent: [broker-a, broker-a, broker-a]
See http://rocketmq.apache.org/docs/faq/ for further details.
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendDefaultImpl(DefaultMQProducerImpl.java:665)
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1343)
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1289)
	at org.apache.rocketmq.client.producer.DefaultMQProducer.send(DefaultMQProducer.java:325)
	at org.example.simple.SyncProducer.main(SyncProducer.java:33)
Caused by: org.apache.rocketmq.client.exception.MQBrokerException: CODE: 1  DESC: create mapped file failed, server is busy or broken. BROKER: 192.168.130.62:10911
For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.processSendResponse(MQClientAPIImpl.java:666)
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessageSync(MQClientAPIImpl.java:505)
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessage(MQClientAPIImpl.java:487)
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessage(MQClientAPIImpl.java:431)
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendKernelImpl(DefaultMQProducerImpl.java:854)
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendDefaultImpl(DefaultMQProducerImpl.java:584)
	... 4 more

**Comment by duhenglucky** [comment]
@Cacle could you provide more information to the broker about this issue, such as store.log broker.log, etc.

**Comment by fengyiluo** [comment]
The following information can be filtered in the store.log ，such as create mapped file1 error , create mapped file2 error, etc. It is convenient to further confirm that the link is wrong

**Comment by duhenglucky** [comment]
@Cacle ping

**Comment by mingjunChan** [comment]
@fengyiluo 谢谢提醒，我遇到同样的问题，store.log提示是我映射文件创建错误了。现在问题解决了

**Comment by yang-o** [comment]
本地安装，默认在当前用户路径下面创建文件，没有对应的权限

**Comment by Tian90coder** [comment]
This can solve the problem
`cd ~/store`
`mkdir commitlog consumequeue`
