### ISSUE TITLE
Unit test throw NPE in DefaultMessageStoreShutDownTest#testDispatchBehindWhenShutdown.

### ISSUE THREAD

**Issue by horizonzy** [apache/rocketmq#2645]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
Execute the unit case, it will throw NPE.

The init method logic exist problem. it buildMessageStore, and then spy it. then load.
the load process should use original messageStore, not after spy messagaStore.

error stack:
```
Exception in thread "FlushConsumeQueueService" java.lang.NullPointerException
	at org.apache.rocketmq.store.DefaultMessageStore$FlushConsumeQueueService.doFlush(DefaultMessageStore.java:1852)
	at org.apache.rocketmq.store.DefaultMessageStore$FlushConsumeQueueService.run(DefaultMessageStore.java:1869)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by RongtongJin** [comment]
Merged
