### ISSUE TITLE
Caused by: org.apache.rocketmq.client.exception.MQBrokerException: CODE: 1  DESC: java.lang.NullPointerException, java.lang.String.startsWith(String.java:1405)

### ISSUE THREAD

**Issue by shaoyangdd** [apache/rocketmq#2669]
producer发消息的时候报空指针

Caused by: org.apache.rocketmq.client.exception.MQBrokerException: CODE: 1  DESC: java.lang.NullPointerException, java.lang.String.startsWith(String.java:1405)
For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.processSendResponse(MQClientAPIImpl.java:665)
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessageSync(MQClientAPIImpl.java:505)
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessage(MQClientAPIImpl.java:487)
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessage(MQClientAPIImpl.java:431)
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendKernelImpl(DefaultMQProducerImpl.java:854)
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendDefaultImpl(DefaultMQProducerImpl.java:584)

**Comment by shaoyangdd** [comment]
问题找到了，是没有加到白名单，但是不应该报空指针啊！

**Comment by vongosling** [comment]
Would you like to build patches to make warnings more self-explanatory? In addition, I would like to let you know that you do not post all exceptions when asking questions, which is not helpful for other guys to search for similar questions. Be smarter to ask questions :-) @RongtongJin @duhenglucky @duhengforever
