### ISSUE TITLE
ERROR main - Failed to create SSLContext for server

### ISSUE THREAD

**Issue by zhangchenzuo** [apache/rocketmq#2675]
By java 15, centos7.9.

when start Rocketmq, the error log is:
```
2021-02-18 00:15:34 ERROR main - Failed to create SSLContext for server
java.security.cert.CertificateException: No provider succeeded to generate a self-signed certificate. See debug log for the root cause.
        at io.netty.handler.ssl.util.SelfSignedCertificate.<init>(SelfSignedCertificate.java:157) ~[netty-all-4.0.42.Final.jar:4.0.42.Final]
        at io.netty.handler.ssl.util.SelfSignedCertificate.<init>(SelfSignedCertificate.java:110) ~[netty-all-4.0.42.Final.jar:4.0.42.Final]
        at io.netty.handler.ssl.util.SelfSignedCertificate.<init>(SelfSignedCertificate.java:88) ~[netty-all-4.0.42.Final.jar:4.0.42.Final]
        at io.netty.handler.ssl.util.SelfSignedCertificate.<init>(SelfSignedCertificate.java:79) ~[netty-all-4.0.42.Final.jar:4.0.42.Final]
        at org.apache.rocketmq.remoting.netty.TlsHelper.buildSslContext(TlsHelper.java:133) ~[rocketmq-remoting-4.8.0.jar:4.8.0]
        at org.apache.rocketmq.remoting.netty.NettyRemotingServer.loadSslContext(NettyRemotingServer.java:166) ~[rocketmq-remoting-4.8.0.jar:4.8.0]
        at org.apache.rocketmq.remoting.netty.NettyRemotingServer.<init>(NettyRemotingServer.java:157) ~[rocketmq-remoting-4.8.0.jar:4.8.0]
        at org.apache.rocketmq.namesrv.NamesrvController.initialize(NamesrvController.java:80) ~[rocketmq-namesrv-4.8.0.jar:4.8.0]
        at org.apache.rocketmq.namesrv.NamesrvStartup.start(NamesrvStartup.java:140) ~[rocketmq-namesrv-4.8.0.jar:4.8.0]
        at org.apache.rocketmq.namesrv.NamesrvStartup.main0(NamesrvStartup.java:58) ~[rocketmq-namesrv-4.8.0.jar:4.8.0]
        at org.apache.rocketmq.namesrv.NamesrvStartup.main(NamesrvStartup.java:51) ~[rocketmq-namesrv-4.8.0.jar:4.8.0]
2021-02-18 00:15:35 INFO main - Try to start service thread:FileWatchService started:false lastThread:null

```

Can you help analyzing this issue?

**Comment by duhenglucky** [comment]
@ShannonDing ping

**Comment by lizhiboo** [comment]
> By java 15, centos7.9.
> 
> when start Rocketmq, the error log is:
> 
> ```
> 2021-02-18 00:15:34 ERROR main - Failed to create SSLContext for server
> java.security.cert.CertificateException: No provider succeeded to generate a self-signed certificate. See debug log for the root cause.
>         at io.netty.handler.ssl.util.SelfSignedCertificate.<init>(SelfSignedCertificate.java:157) ~[netty-all-4.0.42.Final.jar:4.0.42.Final]
>         at io.netty.handler.ssl.util.SelfSignedCertificate.<init>(SelfSignedCertificate.java:110) ~[netty-all-4.0.42.Final.jar:4.0.42.Final]
>         at io.netty.handler.ssl.util.SelfSignedCertificate.<init>(SelfSignedCertificate.java:88) ~[netty-all-4.0.42.Final.jar:4.0.42.Final]
>         at io.netty.handler.ssl.util.SelfSignedCertificate.<init>(SelfSignedCertificate.java:79) ~[netty-all-4.0.42.Final.jar:4.0.42.Final]
>         at org.apache.rocketmq.remoting.netty.TlsHelper.buildSslContext(TlsHelper.java:133) ~[rocketmq-remoting-4.8.0.jar:4.8.0]
>         at org.apache.rocketmq.remoting.netty.NettyRemotingServer.loadSslContext(NettyRemotingServer.java:166) ~[rocketmq-remoting-4.8.0.jar:4.8.0]
>         at org.apache.rocketmq.remoting.netty.NettyRemotingServer.<init>(NettyRemotingServer.java:157) ~[rocketmq-remoting-4.8.0.jar:4.8.0]
>         at org.apache.rocketmq.namesrv.NamesrvController.initialize(NamesrvController.java:80) ~[rocketmq-namesrv-4.8.0.jar:4.8.0]
>         at org.apache.rocketmq.namesrv.NamesrvStartup.start(NamesrvStartup.java:140) ~[rocketmq-namesrv-4.8.0.jar:4.8.0]
>         at org.apache.rocketmq.namesrv.NamesrvStartup.main0(NamesrvStartup.java:58) ~[rocketmq-namesrv-4.8.0.jar:4.8.0]
>         at org.apache.rocketmq.namesrv.NamesrvStartup.main(NamesrvStartup.java:51) ~[rocketmq-namesrv-4.8.0.jar:4.8.0]
> 2021-02-18 00:15:35 INFO main - Try to start service thread:FileWatchService started:false lastThread:null
> ```
> 
> Can you help analyzing this issue?

IMO, it maybe jdk bug, u can refer to https://bugs.openjdk.java.net/browse/JDK-8241039
