### ISSUE TITLE
Heartbeat connection broker timeout in version 4.1.0

### ISSUE THREAD

**Issue by November22** [apache/rocketmq#2693]
RocketMQ日志（4.1.0-incubating版本发送异常的堆栈信息没有输出）：
2021-02-15 05:48:06 WARN MQClientFactoryScheduledThread - createChannel: connect remote host[****:20819] timeout 3000ms, DefaultChannelPromise@6838ce98(uncancellable)
2021-02-15 05:48:06 INFO MQClientFactoryScheduledThread - send heart beat to broker[broker-a 0 ****:20819] failed
可以确认Broker通信没有问题，因为其他应用的心跳发送正常，在发送心跳连接超时的服务器上发现Netty异常信息如下：
2021-02-20 00:00:01.800|7596535444064e98b80e3250ff73c398|NettyClientSelector_1|WARN |i.n.c.n.NioEventLoop-Unexpected exception in the selector loop.
io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
        at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:101)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.handleReadException(AbstractNioByteChannel.java:83)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:161)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
        at java.lang.Thread.run(Thread.java:748)
Netty依赖包： netty-3.10.6.Final.jar、netty-all-4.0.24.Final.jar
不确定是不是这个引起的发送异常。
解决方式：重启应用服务器，心跳发送正常。

**Comment by RongtongJin** [comment]
It is recommended to upgrade to the latest rocketmq version

**Comment by vongosling** [comment]
netty 3 and netty 4 are friendly co-located in your project. 4.1.0 is a very old version, at least 4 years ago. Would you like to update to version 4.5 above, this will give you better stability:-)
