### ISSUE TITLE
java.nio.BufferUnderflowException: null

### ISSUE THREAD

**Issue by newboy2004** [apache/rocketmq#284]
continously delete topic  occure below error：
java.nio.BufferUnderflowException: null
	at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:271) ~[na:1.8.0_161]
	at java.nio.ByteBuffer.get(ByteBuffer.java:715) ~[na:1.8.0_161]
	at org.apache.rocketmq.remoting.protocol.RemotingCommand.decode(RemotingCommand.java:150) ~[classes/:na]
	at org.apache.rocketmq.remoting.netty.NettyDecoder.decode(NettyDecoder.java:50) ~[classes/:na]
	at io.netty.handler.codec.LengthFieldBasedFrameDecoder.decode(LengthFieldBasedFrameDecoder.java:343) [netty-all-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411) [netty-all-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248) [netty-all-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367) [netty-all-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353) [netty-all-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346) [netty-all-4.0.42.Final.jar:4.0.42.Final]
	at org.apache.rocketmq.remoting.netty.NettyRemotingServer$HandshakeHandler.channelRead0(NettyRemotingServer.java:385) [classes/:na]
	at org.apache.rocketmq.remoting.netty.NettyRemotingServer$HandshakeHandler.channelRead0(NettyRemotingServer.java:327) [classes/:na]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [netty-all-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367) [netty-all-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:36) [netty-all-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:358) [netty-all-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:41) [netty-all-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140) [netty-all-4.0.42.Final.jar:4.0.42.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_161]
2018-04-12 05\:32\:01 INFO NettyServerNIOSelector_3_3 - closeChannel: close the connection to remote address[127.0.0.1:64537] result: true

**Comment by newboy2004** [comment]
MqAdminExt has bug???
