### ISSUE TITLE
DefaultMQProducer sendMsgTimeout It's not fully effective

### ISSUE THREAD

**Issue by biuabiu** [apache/rocketmq#2845]
1. Please describe the issue you observed:
I only set the timeout to 10 seconds, but when connecting to namesrv, the timeout results in the timeout of sending messages. I don't think this is a complete timeout of 10 seconds. Is this a bug

2. Please tell us about your environment:
mq version :4.8.0
os: windows 10

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):
`org.apache.rocketmq.remoting.exception.RemotingTimeoutException: wait response on the channel <127.0.0.1:9876> timeout, 3000(ms)
	at org.apache.rocketmq.remoting.netty.NettyRemotingAbstract.invokeSyncImpl(NettyRemotingAbstract.java:440) ~[classes/:na]
	at org.apache.rocketmq.remoting.netty.NettyRemotingClient.invokeSync(NettyRemotingClient.java:377) ~[classes/:na]
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.getTopicRouteInfoFromNameServer(MQClientAPIImpl.java:1367) ~[classes/:na]
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.getTopicRouteInfoFromNameServer(MQClientAPIImpl.java:1357) ~[classes/:na]
	at org.apache.rocketmq.client.impl.factory.MQClientInstance.updateTopicRouteInfoFromNameServer(MQClientInstance.java:622) ~[classes/:na]
	at org.apache.rocketmq.client.impl.factory.MQClientInstance.updateTopicRouteInfoFromNameServer(MQClientInstance.java:509) ~[classes/:na]
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.tryToFindTopicPublishInfo(DefaultMQProducerImpl.java:694) ~[classes/:na]
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendDefaultImpl(DefaultMQProducerImpl.java:557) ~[classes/:na]
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1344) ~[classes/:na]
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1290) ~[classes/:na]
	at org.apache.rocketmq.client.producer.DefaultMQProducer.send(DefaultMQProducer.java:326) ~[classes/:na]`

`topicRouteData = this.mQClientAPIImpl.getTopicRouteInfoFromNameServer(topic, 1000 * 3);`

**Comment by panzhi33** [comment]
This is caused by the failure to get topic route,when a timeout exception occurs, it will not be retried, and the exception will be thrown directly。The step of getting topic route is very important, this step failed, and the following process cannot continue.
