### ISSUE TITLE
Simple attack cause broker fail to start

### ISSUE THREAD

**Issue by yuz10** [apache/rocketmq#2935]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?

run code below, register a kv config , key is `null`
```
    public static void main(String[] args)
            throws MQClientException, RemotingException, MQBrokerException, InterruptedException {
        DefaultMQAdminExt defaultMQAdminExt = new DefaultMQAdminExt();
        defaultMQAdminExt.setNamesrvAddr("localhost:9876");
        defaultMQAdminExt.start();
        defaultMQAdminExt.createAndUpdateKvConfig("ORDER_TOPIC_CONFIG", null, "broker-a:8");
        defaultMQAdminExt.shutdown();
    }
```
and then restart broker

- What did you expect to see?
broker restart successfully

- What did you see instead?
 broker start fail: 
java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at org.apache.rocketmq.broker.topic.TopicConfigManager.updateOrderTopicConfig(TopicConfigManager.java:374)
	at org.apache.rocketmq.broker.BrokerController.doRegisterBrokerAll(BrokerController.java:979)
	at org.apache.rocketmq.broker.BrokerController.registerBrokerAll(BrokerController.java:951)
	at org.apache.rocketmq.broker.BrokerController.start(BrokerController.java:887)
	at org.apache.rocketmq.broker.BrokerStartup.start(BrokerStartup.java:64)
	at org.apache.rocketmq.broker.BrokerStartup.main(BrokerStartup.java:58)

2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**Comment by lizhimins** [comment]
It's really a problem

**Comment by vongosling** [comment]
@duhenglucky milestone tag may be attacheded on pr @RongtongJin only problem category on issue.
