### ISSUE TITLE
namesrv报java.io.IOException: Connection reset by peer

### ISSUE THREAD

**Issue by qianxiaojun8** [apache/rocketmq#2984]
2021-06-07 10:20:57 WARN NettyServerCodecThread_4 - NETTY SERVER PIPELINE: exceptionCaught 100.116.69.130:40077
2021-06-07 10:20:57 WARN NettyServerCodecThread_4 - NETTY SERVER PIPELINE: exceptionCaught exception.
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:1.8.0_292]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:1.8.0_292]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_292]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.8.0_292]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379) ~[na:1.8.0_292]
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:221) ~[netty-all-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:899) ~[netty-all-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:275) ~[netty-all-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119) ~[netty-all-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:652) ~[netty-all-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:575) ~[netty-all-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:489) ~[netty-all-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:451) ~[netty-all-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140) [netty-all-4.0.42.Final.jar:4.0.42.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_292]

想问下这个问题可以怎么解决。。

**Comment by panzhi33** [comment]
一般都是因为客户端关闭了链接，namesrv还在往客户端发送数据，后面namesrv也会关闭这个链接的，可以忽略这个

**Comment by qianxiaojun8** [comment]
> 一般都是因为客户端关闭了链接，namesrv还在往客户端发送数据，后面namesrv也会关闭这个链接的，可以忽略这个

好的。谢谢了  看到这个报错一直在报了几天。以为是什么问题了

**Comment by qianxiaojun8** [comment]
> 一般都是因为客户端关闭了链接，namesrv还在往客户端发送数据，后面namesrv也会关闭这个链接的，可以忽略这个

这个能找到是因为哪个客户端吗？？谢谢

**Comment by panzhi33** [comment]
> > 一般都是因为客户端关闭了链接，namesrv还在往客户端发送数据，后面namesrv也会关闭这个链接的，可以忽略这个
> 
> 这个能找到是因为哪个客户端吗？？谢谢

![image](https://user-images.githubusercontent.com/29321745/120976029-854e5780-c7a4-11eb-9289-83c041ef9118.png)
日志这里有提示的，根据ip来找

**Comment by qianxiaojun8** [comment]
> > > 一般都是因为客户端关闭了链接，namesrv还在往客户端发送数据，后面namesrv也会关闭这个链接的，可以忽略这个
> > 
> > 
> > 这个能找到是因为哪个客户端吗？？谢谢
> 
> ![image](https://user-images.githubusercontent.com/29321745/120976029-854e5780-c7a4-11eb-9289-83c041ef9118.png)
> 日志这里有提示的，根据ip来找

这个ip我都不知道是哪里的，不是我们自己的ip
