### ISSUE TITLE
Fail to send trace of last message before shutdown producer

### ISSUE THREAD

**Issue by yuz10** [apache/rocketmq#2988]
**BUG REPORT**

1. Please describe the issue you observed:
Fail to send trace of last message before shutdown producer

- What did you do (The steps to reproduce)?
send message and enable trace
```java
    public static void main(String[] args) throws MQClientException, InterruptedException, UnsupportedEncodingException, MQBrokerException, RemotingException {
        DefaultMQProducer producer = new DefaultMQProducer("ProducerGroupName", true);
        producer.setNamesrvAddr("localhost:9876");
        producer.start();

        Message msg = new Message("TopicTest", "TagA", "OrderID188",
                "Hello world".getBytes(RemotingHelper.DEFAULT_CHARSET));
        SendResult sendResult = producer.send(msg);
        System.out.printf("%s%n", sendResult);

        producer.shutdown();
    }
```
- What did you expect to see?
trace is sent sucessfully
- What did you see instead?
trace sent fail:
```
Exception in thread "MQ-AsyncTraceDispatcher-Thread-c2c2798a-6f33-449d-a62e-f3243429c979" java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@15bafbba rejected from java.util.concurrent.ThreadPoolExecutor@1b7d177d[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
	at org.apache.rocketmq.client.trace.AsyncTraceDispatcher$AsyncRunnable.run(AsyncTraceDispatcher.java:258)
	at java.lang.Thread.run(Thread.java:748)
```

2. Please tell us about your environment:
  
3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):
- Why this happens:

```java
    class AsyncRunnable implements Runnable {
        private boolean stopped;

        @Override
        public void run() {
            while (!stopped) {
                List<TraceContext> contexts = new ArrayList<TraceContext>(batchSize);
                for (int i = 0; i < batchSize; i++) {
                    TraceContext context = null;
                    try {
                        //get trace data element from blocking Queue - traceContextQueue
                        context = traceContextQueue.poll(5, TimeUnit.MILLISECONDS);
                    } catch (InterruptedException e) {
                    }
                    if (context != null) {
                        contexts.add(context);
                    } else {
                        break;
                    }
                }
                if (contexts.size() > 0) {
                    AsyncAppenderRequest request = new AsyncAppenderRequest(contexts);
                    traceExecutor.submit(request);
                } else if (AsyncTraceDispatcher.this.stopped) {
                    this.stopped = true;
                }
            }

        }
    }
```

  **In AsyncRunnable::run , traceContextQueue.poll use 5ms to get data in queue, during the 5ms, traceContextQueue is empty but data in queue is placed to contexts,   waiting for traceExecutor.submit.**

**so, if call traceExecutor.shutdown() in this 5ms, the data is lost, and exception is thrown.**

**Comment by francisoliverlee** [comment]
that's a checkpoint. and 
what's circumstances would call shutdown immediately after call send

**Comment by yuz10** [comment]
@francisoliverlee In demos, and sendMessage command.

**Comment by lizhimins** [comment]
yes, we need a grateful shutdown hook
