### ISSUE TITLE
NOT TRY ERROR

### ISSUE THREAD

**Issue by Hsiu-chu** [apache/rocketmq#3012]
rocketmq/client/src/main/java/org/apache/rocketmq/client/impl/producer/DefaultMQProducerImpl.java 
private SendResult sendKernelImpl(final Message msg,
        final MessageQueue mq,
        final CommunicationMode communicationMode,
        final SendCallback sendCallback,
        final TopicPublishInfo topicPublishInfo,
        final long timeout) throws MQClientException, RemotingException, MQBrokerException, InterruptedException {}
 MessageClientIDSetter.setUniqID(msg);
Error thrown when commons-validator-1.7.jar is Missing ,However, the error is not captured, so the SendResult cannot be returned.

java.lang.NoClassDefFoundError: org/apache/commons/validator/routines/InetAddressValidator
        at org.apache.rocketmq.common.UtilAll.ipV6Check(UtilAll.java:474)
        at org.apache.rocketmq.common.UtilAll.getIP(UtilAll.java:530)
        at org.apache.rocketmq.common.message.MessageClientIDSetter.<clinit>(MessageClientIDSetter.java:36)
        at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendKernelImpl(DefaultMQProducerImpl.java:709)

**Comment by odbozhou** [comment]
Please check in your application why this exception NoClassDefFoundError is thrown back

**Comment by Hsiu-chu** [comment]
I use rocketmq-flume, which introduces the client, but does not throw an exception, and is always waiting.
