### ISSUE TITLE
No accessKey is configured

### ISSUE THREAD

**Issue by ighack** [apache/rocketmq#3115]
1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
aclEnable=true

Server1:  nohup bin/mqbroker -c conf/2m-2s-sync/broker-a.properties &

when I "nohup bin/mqbroker -c conf/2m-2s-sync/broker-a-s.properties &" at Server2

in Server1: logs/rocketmqlogs/remoting.log
I get a error

```
ERROR AdminBrokerThread_12 - process request exception
org.apache.rocketmq.acl.common.AclException: No accessKey is configured
	at org.apache.rocketmq.acl.plain.PlainPermissionManager.validate(PlainPermissionManager.java:403) ~[rocketmq-acl-4.9.0.jar:4.9.0]
	at org.apache.rocketmq.acl.plain.PlainAccessValidator.validate(PlainAccessValidator.java:140) ~[rocketmq-acl-4.9.0.jar:4.9.0]
	at org.apache.rocketmq.broker.BrokerController$10.doBeforeRequest(BrokerController.java:524) ~[rocketmq-broker-4.9.0.jar:4.9.0]
	at org.apache.rocketmq.remoting.netty.NettyRemotingAbstract.doBeforeRpcHooks(NettyRemotingAbstract.java:172) ~[rocketmq-remoting-4.9.0.jar:4.9.0]
	at org.apache.rocketmq.remoting.netty.NettyRemotingAbstract$1.run(NettyRemotingAbstract.java:202) ~[rocketmq-remoting-4.9.0.jar:4.9.0]
	at org.apache.rocketmq.remoting.netty.RequestTask.run(RequestTask.java:80) [rocketmq-remoting-4.9.0.jar:4.9.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_271]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_271]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_271]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_271]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_271]
2021-07-01 10:21:31 ERROR AdminBrokerThread_12 - RemotingCommand [code=201, language=JAVA, version=393, opaque=134, flag(B)=0, remark=null, extFields=null, serializeTypeCurrentRPC=JSON]
```

2. Please tell us about your environment:
rocketmq 4.9.0

broker-a.properties
```
brokerClusterName=DefaultCluster
brokerName=broker-a
brokerId=0
deleteWhen=04
fileReservedTime=48
brokerRole=SYNC_MASTER
flushDiskType=ASYNC_FLUSH

namesrvAddr=xxxxxxxx
storePathRootDir=/hadoop/rocketmq-all-4.9.0-bin-release/store
storePathCommitLog=/hadoop/rocketmq-all-4.9.0-bin-release/store/commitlog
enablePropertyFilter=true
autoCreateTopicEnable=false
aclEnable=true
```

broker-a-s.properties
```
brokerClusterName=DefaultCluster
brokerName=broker-a
brokerId=1
deleteWhen=04
fileReservedTime=48
brokerRole=SLAVE
flushDiskType=ASYNC_FLUSH

namesrvAddr=xxxxxxxx
storePathRootDir=/hadoop/rocketmq-all-4.9.0-bin-release/store
storePathCommitLog=/hadoop/rocketmq-all-4.9.0-bin-release/store/commitlog
enablePropertyFilter=true
autoCreateTopicEnable=false
aclEnable=true
```

plain_acl.yml

```
globalWhiteRemoteAddresses:

accounts:
- accessKey: adminrocket
  secretKey: '12345678'
  whiteRemoteAddress: null
  admin: true

- accessKey: testRocketMQ
  secretKey: 12345678
  whiteRemoteAddress: null
  admin: false
  topicPerms:
  - test=PUB|SUB
  - testOrder=SUB
```

my java application is OK

**Comment by francisoliverlee** [comment]
@ighack 
too risk to export the public IP ADDRESS, and it seems plain_acl.yml not right

**Comment by ighack** [comment]
@francisoliverlee 
but my application is OK
rocketmq-console-ng is OK

**Comment by zhurunhua** [comment]
you need to config the globalWhiteRemoteAddresses. your application and console has used the accessKey to access rmq server.

**Comment by zhurunhua** [comment]
And I really want to speak Chinese

**Comment by githublaohu** [comment]
我直接说中文吧。 日志信息太少看。目前猜测是broker-a-s 不在broker-a的授权里面，同时没有看到broker-a-s 配置的ak与sk。

**Comment by zhurunhua** [comment]
RocketMQ开启ACL之后，客户端通过accessKey和secretKey进行认证，但是集群的节点之间是不能配置accessKey和secretKey，只能通过配置全局ip白名单的方式来访问，也就是配置plain_acl.yml中的globalWhiteRemoteAddresses，可以这篇文章：https://blog.csdn.net/sinat_14840559/article/details/116302400

**Comment by ighack** [comment]
@zhurunhua 
说中文吧。大家看的都轻松

**Comment by githublaohu** [comment]
解决了吗？   
clietn请求broker， 可以debug，看下acl的RPCHook实现。
如果是console请求broker或者broker请求主broker，请把console，主从的ip地址设为全局免校验：globalWhiteRemoteAddresses

**Comment by ighack** [comment]
这些时重点还没在这上面。我有时间看一下

**Comment by gongxulei** [comment]
大写的无语
