### ISSUE TITLE
MQBrokerException: CODE: 4  DESC: not set any response code

### ISSUE THREAD

**Issue by jnliao** [apache/rocketmq#3139]
BUG REPORT

（1）sometimes cause:
com.aliyun.openservices.shade.com.alibaba.rocketmq.client.exception.MQBrokerException: CODE: 4  DESC: not set any response code

（2）Please tell us about your environment:
 rocketmq-all  4.3

    <groupId>com.aliyun.openservices</groupId>
    <artifactId>ons-client</artifactId>
    <version>1.8.4.Final</version>

（3）Other information:
detail error information
`Caused by: com.aliyun.openservices.shade.com.alibaba.rocketmq.client.exception.MQBrokerException: CODE: 4  DESC: not set any response code
For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
	at com.aliyun.openservices.shade.com.alibaba.rocketmq.client.impl.MQClientAPIImpl.processSendResponse(MQClientAPIImpl.java:630)
	at com.aliyun.openservices.shade.com.alibaba.rocketmq.client.impl.MQClientAPIImpl.sendMessageSync(MQClientAPIImpl.java:421)
	at com.aliyun.openservices.shade.com.alibaba.rocketmq.client.impl.MQClientAPIImpl.sendMessage$original$CZzmgDgt(MQClientAPIImpl.java:403)
	at com.aliyun.openservices.shade.com.alibaba.rocketmq.client.impl.MQClientAPIImpl.sendMessage$original$CZzmgDgt$accessor$GvtY7Pji(MQClientAPIImpl.java)
	at com.aliyun.openservices.shade.com.alibaba.rocketmq.client.impl.MQClientAPIImpl$auxiliary$W1Qc4gl8.call(Unknown Source)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:86)
	at com.aliyun.openservices.shade.com.alibaba.rocketmq.client.impl.MQClientAPIImpl.sendMessage(MQClientAPIImpl.java)
	at com.aliyun.openservices.shade.com.alibaba.rocketmq.client.impl.MQClientAPIImpl.sendMessage(MQClientAPIImpl.java:366)
	at com.aliyun.openservices.shade.com.alibaba.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendKernelImpl(DefaultMQProducerImpl.java:752)
	at com.aliyun.openservices.shade.com.alibaba.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendDefaultImpl(DefaultMQProducerImpl.java:484)
	at com.aliyun.openservices.shade.com.alibaba.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1137)
	at com.aliyun.openservices.shade.com.alibaba.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1091)
	at com.aliyun.openservices.shade.com.alibaba.rocketmq.client.producer.DefaultMQProducer.send(DefaultMQProducer.java:257)
	at com.aliyun.openservices.ons.api.impl.rocketmq.ProducerImpl.send(ProducerImpl.java:127)`

**Comment by caigy** [comment]
Did you use ons-client to access Apache RocketMQ? ons-client is not maintained by Apache RocketMQ, so you'd better submmit a ticket to Alibaba Cloud.
