### ISSUE TITLE
RocketmqClient - removeMessage exception,java.lang.InterruptedException

### ISSUE THREAD

**Issue by simonHome** [apache/rocketmq#3140]
Bug Report

2021-07-13 14:24:13,013 ERROR RocketmqClient - removeMessage exception
java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(AbstractQueuedSynchronizer.java:1220)
	at java.util.concurrent.locks.ReentrantReadWriteLock$WriteLock.lockInterruptibly(ReentrantReadWriteLock.java:998)
	at org.apache.rocketmq.client.impl.consumer.ProcessQueue.removeMessage(ProcessQueue.java:246)
	at org.apache.rocketmq.client.impl.consumer.ConsumeMessageConcurrentlyService.processConsumeResult(ConsumeMessageConcurrentlyService.java:309)
	at org.apache.rocketmq.client.impl.consumer.ConsumeMessageConcurrentlyService$ConsumeRequest.run(ConsumeMessageConcurrentlyService.java:460)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.alibaba.ttl.TtlRunnable.run(TtlRunnable.java:59)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
_______________________________________________________________________________________________________

this exception to slow consume message，I don't know where to start,I would like to find about the causes，Please take help  look ！！！

**Comment by ni-ze** [comment]
how to Repeated this error?

**Comment by caigy** [comment]
@simonHome Please provide more information about this bug, including your client and server version, what type of message, subscription mode, etc,  especially how to reproduce it.
