### ISSUE TITLE
updateAclConfig cause broker fail to start

### ISSUE THREAD

**Issue by yuz10** [apache/rocketmq#3175]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
`mqadmin  updateAclConfig -c RaftCluster -a aaaaaaaaaak `

and then restart broker

- What did you expect to see?
restart success 

- What did you see instead?
broker start failed
```
java.lang.ClassCastException: java.lang.Class cannot be cast to org.apache.rocketmq.acl.AccessValidator
	at org.apache.rocketmq.broker.BrokerController.initialAcl(BrokerController.java:516)
	at org.apache.rocketmq.broker.BrokerController.initialize(BrokerController.java:483)
	at org.apache.rocketmq.broker.BrokerStartup.createBrokerController(BrokerStartup.java:222)
	at org.apache.rocketmq.broker.BrokerStartup.main(BrokerStartup.java:58)
```

2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**Comment by odbozhou** [comment]
Please tell us about your environment and mq version ？

**Comment by yuz10** [comment]
> Please tell us about your environment and mq version ？

The problem is caused by secretKey is null. I will submit a pull request later

**Comment by duhenglucky** [comment]
merged
