### ISSUE TITLE
springboot集成log4j2 appender 日志发送失败

### ISSUE THREAD

**Issue by JerryZ521** [apache/rocketmq#3268]
应用启动后，第一次可以正常发送日志，再次发送时报如下异常：
20210816 16:02:09.339 [main] INFO  org.springframework.boot.actuate.endpoint.web.EndpointLinksResolver 58 - Exposing 1 endpoint(s) beneath base path ''
2021-08-16 16:02:09,478 main WARN SerializedLayout is deprecated due to the inherent security weakness in Java Serialization, see https://www.owasp.org/index.php/Deserialization_of_untrusted_data Consider using another layout, e.g. JsonLayout
20210816 16:02:09.495 [NettyClientSelector_1] INFO  RocketmqRemoting 95 - closeChannel: close the connection to remote address[10.158.158.19:10911] result: true
2021-08-16 16:02:09,496 NettyClientSelector_1 ERROR Could not send message in RocketmqLog4j2Appender [rocketmqAppender].Message is : 2021-08-16 16:02:09,495 [INFO] RocketmqRemoting closeChannel: close the connection to remote address[10.158.158.19:10911] result: true
 org.apache.rocketmq.client.exception.MQClientException: The producer service state not OK, SHUTDOWN_ALREADY
See http://rocketmq.apache.org/docs/faq/ for further details.
        at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.makeSureStateOK(DefaultMQProducerImpl.java:442)
        at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendDefaultImpl(DefaultMQProducerImpl.java:560)
        at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendOneway(DefaultMQProducerImpl.java:1014)
        at org.apache.rocketmq.client.producer.DefaultMQProducer.sendOneway(DefaultMQProducer.java:403)
        at org.apache.rocketmq.logappender.log4j2.RocketmqLog4j2Appender.append(RocketmqLog4j2Appender.java:106)
        at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84)

**Comment by RongtongJin** [comment]
日志显示producer已经shutdown了，所以不能再发送了

**Comment by JerryZ521** [comment]
这个问题解决了。
原因描述：ProducerInstancer每次获取producer都是同一个实例，而我们的场景需要动态更新log4j2配置，重新初始化上下文时关闭了producer，现在改成每次获取新对象，stop方法改成每次调用关闭当前appender中的producer对象。

**Comment by duhenglucky** [comment]
> 这个问题解决了。
> 原因描述：ProducerInstancer每次获取producer都是同一个实例，而我们的场景需要动态更新log4j2配置，重新初始化上下文时关闭了producer，现在改成每次获取新对象，stop方法改成每次调用关闭当前appender中的producer对象。

为这种有始有终的issue 点赞，提出问题，并且能够在问题解决后特意回到社区说明原因以及解决办法。
