### ISSUE TITLE
com.alibaba.rocketmq.client.exception.MQBrokerException: CODE: 24  DESC:

### ISSUE THREAD

**Issue by gyjx** [apache/rocketmq#339]
com.alibaba.rocketmq.client.exception.MQBrokerException: CODE: 24  DESC: the consumer's subscription not exist
See https://github.com/alibaba/RocketMQ/issues/46 for further details.
        at com.alibaba.rocketmq.client.impl.MQClientAPIImpl.processPullResponse(MQClientAPIImpl.java:545)
        at com.alibaba.rocketmq.client.impl.MQClientAPIImpl.access$3(MQClientAPIImpl.java:528)
        at com.alibaba.rocketmq.client.impl.MQClientAPIImpl$2.operationComplete(MQClientAPIImpl.java:498)
        at com.alibaba.rocketmq.remoting.netty.ResponseFuture.executeInvokeCallback(ResponseFuture.java:58)
        at com.alibaba.rocketmq.remoting.netty.NettyRemotingAbstract$2.run(NettyRemotingAbstract.java:204)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**https://github.com/alibaba/RocketMQ/issues/46**

where is  it ?

**Comment by lizhanhui** [comment]
The link is obsolete and scheduled be fixed in next release.

**Comment by gyjx** [comment]
thank you !
Now we have a problem，The actual existence of topic ， But it's been a mistake.
Can  you  help me ?

**Comment by gyjx** [comment]
![image](https://user-images.githubusercontent.com/20329819/41389632-6ce881d8-6fc4-11e8-9723-69bdb36569ea.png)

Is this the bug of RocketMQ3.5.8?

**Comment by vongosling** [comment]
No, if you have any question, welcome to email to our user email list, http://rocketmq.apache.org/about/contact/.
