### ISSUE TITLE
queryMsgById which  not return the message

### ISSUE THREAD

**Issue by huhu-jin** [apache/rocketmq#341]
the command likes this
```
mqadmin queryMsgById -i D0D069A8191818B4AAC25FF6BB8603B0 
```
even if   I add other optional args, RocketMq returns likes this 
```
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0
org.apache.rocketmq.tools.command.SubCommandException: QueryMsgByIdSubCommand command failed
        at org.apache.rocketmq.tools.command.message.QueryMsgByIdSubCommand.execute(QueryMsgByIdSubCommand.java:258)
        at org.apache.rocketmq.tools.command.MQAdminStartup.main0(MQAdminStartup.java:130)
        at org.apache.rocketmq.tools.command.MQAdminStartup.main(MQAdminStartup.java:81)
Caused by: org.apache.rocketmq.client.exception.MQClientException: CODE: 208  DESC: query message by id finished, but no message.
For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
        at org.apache.rocketmq.client.impl.MQAdminImpl.viewMessage(MQAdminImpl.java:250)
        at org.apache.rocketmq.tools.admin.DefaultMQAdminExtImpl.viewMessage(DefaultMQAdminExtImpl.java:958)
        at org.apache.rocketmq.tools.admin.DefaultMQAdminExt.viewMessage(DefaultMQAdminExt.java:124)
        at org.apache.rocketmq.tools.command.message.QueryMsgByIdSubCommand.queryById(QueryMsgByIdSubCommand.java:47)
        at org.apache.rocketmq.tools.command.message.QueryMsgByIdSubCommand.execute(QueryMsgByIdSubCommand.java:252)
        ... 2 more
```
but in RocketMq-console-ng i can find the message. 

Do  i misunderstand anything?.

**Comment by XiaoZYang** [comment]
@huhu-jin Would you mind providing more detail about how you produce the message and get the msgId `D0D069A8191818B4AAC25FF6BB8603B0 `?
And there may be some possible causes:
1. Would you mind ensuring that what you used is the value of `msgId` rather than `offsetMsgId` ?
2. Do you **export the environment variable** `NAMESRV_ADDR` and the command `mqadmin` use the right value of `NAMESRV_ADDR`?

**Comment by vongosling** [comment]
I will close the issue@huhu-jin. If you confirm it is a bug or suspected bug, welcome to comment on here.
