### ISSUE TITLE
connect to 192.168.100.102:10911 failed

### ISSUE THREAD

**Issue by CN-Jane** [apache/rocketmq#3440]
My English is not good,Let me describe my probleam.
first：
use command: nohup sh mqnamesrv -n xxx:9876 > /usr/local/logs/rocketmqlogs/mqnamesrv.log 2>&1 &
next : vim conf/broker.conf, add config： 
namesrvAddr=xxx:9876
brokerIP1=xxx
xxx is Internet address and the port is already open 
next: nohup sh mqbroker -n xxx:9876 -c ../conf/broker.conf  > /usr/local/logs/rocketmqlogs/broker.log 2>&1 &

This error occurs when a message is sent：
org.apache.rocketmq.client.exception.MQClientException: Send [3] times, still failed, cost [6013]ms, Topic: basic, BrokersSent: [broker-a, broker-a, broker-a]
Caused by: org.apache.rocketmq.remoting.exception.RemotingConnectException: connect to 192.168.100.102:10911 failed

**Comment by CN-Jane** [comment]
1.[root@izualbf3those4z bin]# sh mqadmin clusterList -n 39.66.145.152:9876
RocketMQLog:WARN No appenders could be found for logger (io.netty.util.internal.InternalThreadLocalMap).
RocketMQLog:WARN Please initialize the logger system properly.
#Cluster Name     #Broker Name            #BID  #Addr                  #Version                #InTPS(LOAD)       #OutTPS(LOAD) #PCWait(ms) #Hour #SPACE
org.apache.rocketmq.remoting.exception.RemotingConnectException: connect to 192.168.100.102:10911 failed
        at org.apache.rocketmq.remoting.netty.NettyRemotingClient.invokeSync(NettyRemotingClient.java:394)
        at org.apache.rocketmq.client.impl.MQClientAPIImpl.getBrokerRuntimeInfo(MQClientAPIImpl.java:1274)
        at org.apache.rocketmq.tools.admin.DefaultMQAdminExtImpl.fetchBrokerRuntimeStats(DefaultMQAdminExtImpl.java:266)
        at org.apache.rocketmq.tools.admin.DefaultMQAdminExt.fetchBrokerRuntimeStats(DefaultMQAdminExt.java:237)
        at org.apache.rocketmq.tools.command.cluster.ClusterListSubCommand.printClusterBaseInfo(ClusterListSubCommand.java:212)
        at org.apache.rocketmq.tools.command.cluster.ClusterListSubCommand.execute(ClusterListSubCommand.java:88)
        at org.apache.rocketmq.tools.command.MQAdminStartup.main0(MQAdminStartup.java:140)
        at org.apache.rocketmq.tools.command.MQAdminStartup.main(MQAdminStartup.java:91)
DefaultCluster    broker-a                0     192.168.100.102:10911                             0.00(,ms)           0.00(,ms)             0.00 0.0000

2.The contents of mqnamesrv.log is : 
Java HotSpot(TM) 64-Bit Server VM warning: Using the DefNew young collector with the CMS collector is deprecated and will likely be removed in a future release
Java HotSpot(TM) 64-Bit Server VM warning: UseCMSCompactAtFullCollection is deprecated and will likely be removed in a future release.
The Name Server boot success. serializeType=JSON

The contents of broker.log is 
The broker[broker-a, 39.66.145.152:10911] boot success. serializeType=JSON and name server is 39.66.145.152:9876

**Comment by Jason918** [comment]
It seems that `brokerIP1` was updated to "192.168.100.102" after startup.
You can check if there is a log containing "updateBrokerConfig".

**Comment by CN-Jane** [comment]
I checked broker.log、broker_default.log、namesrv.log、namesrv_default.log、rocketmq_client.log、stats.log、store.log，
"updateBrokerConfig" was not found in the contents of log file.
So I don't know why after startup, the brokerIP1 becomes 192.168.100.102。

**Comment by CN-Jane** [comment]
@Jason918 Now I don't know what caused this problem? How to continue to check the problem

**Comment by Jason918** [comment]
Is it reproducible? Can you show the whole log file in broker.log?

**Comment by CN-Jane** [comment]
it is so big.i can provide a download address.
https://pan.baidu.com/s/1ypgP6U5v8d_sV9KM57pMjQ 
r77t

Thank you very much for your help.
