### ISSUE TITLE
sendMessageInTransaction EOF:null  bug

### ISSUE THREAD

**Issue by baiyuechu-123** [apache/rocketmq#3520]
we can send order message bug send transaction error

2021-11-22 16:13:18.555  INFO [,f65794a19aa740cc,f65794a19aa740cc,true] 1 --- [nio-6001-exec-1] c.j.c.m.c.CrmCusBatchController          : testNormalTopicTransaction
SendResult [sendStatus=SEND_OK, msgId=7F000001000141CF53F96FA0A3650000, offsetMsgId=null, messageQueue=MessageQueue [topic=normal_topic, brokerName=broker-0, queueId=11], queueOffset=8080]
2021-11-22 16:13:18.575 DEBUG [,f65794a19aa740cc,f65794a19aa740cc,true] 1 --- [nio-6001-exec-1] o.s.web.servlet.DispatcherServlet        : Completed 200 OK
2021-11-22 16:13:18.587 DEBUG [,,,] 1 --- [nio-6001-exec-1] o.a.tomcat.util.net.SocketWrapperBase    : Socket: [org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper@24bcf340:org.apache.tomcat.util.net.NioChannel@61be69b3:java.nio.channels.SocketChannel[connected local=localhost/127.0.0.1:6001 remote=/127.0.0.1:39812]], Read from buffer: [0]
2021-11-22 16:13:18.588 DEBUG [,,,] 1 --- [nio-6001-exec-1] o.apache.coyote.http11.Http11Processor   : Error parsing HTTP request header

java.io.EOFException: null
	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.fillReadBuffer(NioEndpoint.java:1230)
	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.read(NioEndpoint.java:1140)
	at org.apache.coyote.http11.Http11InputBuffer.fill(Http11InputBuffer.java:780)
	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:356)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:260)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1589)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

2021-11-22 16:13:18.588 DEBUG [,,,] 1 --- [nio-6001-exec-1] o.apache.coyote.http11.Http11Processor   : Socket: [org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper@24bcf340:org.apache.tomcat.util.net.NioChannel@61be69b3:java.nio.channels.SocketChannel[connected local=localhost/127.0.0.1:6001 remote=/127.0.0.1:39812]], Status in: [OPEN_READ], State out: [CLOSED]

**Comment by Git-Yang** [comment]
The error may have nothing to do with rocketmq, it should be tomcat debugging information.
I have seen a related discussion, you can refer to it. https://stackoverflow.com/questions/51501360/springboot-error-parsing-http-request-header-oauth2-https-endpoints

**Comment by vongosling** [comment]
What operations are you running when you see this, is the real case like StackOverflow said?
