### ISSUE TITLE
code: 25 desc: the consumer's subscription not latest

### ISSUE THREAD

**Issue by yuxuanxinchen** [apache/rocketmq#370]
2018-07-18 10:26:55.0926 WARN - NettyClientPublicExecutor_2 | RocketmqClient.onException-384  execute the pull request exception org.apache.rocketmq.client.exception.MQBrokerException: CODE: 25  DESC: the consumer's subscription not latest
For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.processPullResponse(MQClientAPIImpl.java:640) ~[rocketmq-client-4.2.0.jar:4.2.0]
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.access$200(MQClientAPIImpl.java:155) ~[rocketmq-client-4.2.0.jar:4.2.0]
	at org.apache.rocketmq.client.impl.MQClientAPIImpl$2.operationComplete(MQClientAPIImpl.java:592) [rocketmq-client-4.2.0.jar:4.2.0]
	at org.apache.rocketmq.remoting.netty.ResponseFuture.executeInvokeCallback(ResponseFuture.java:51) [rocketmq-remoting-4.2.0.jar:4.2.0]
	at org.apache.rocketmq.remoting.netty.NettyRemotingAbstract$2.run(NettyRemotingAbstract.java:286) [rocketmq-remoting-4.2.0.jar:4.2.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_112]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_112]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_112]

请问这个是什么问题呢

**Comment by xingfudeshi** [comment]
please provide further details,like how does it happen?when does it happen?
the details can help us to locate the problem quickly.
thanks!!

**Comment by xingfudeshi** [comment]
please provide your system environment too.thanks!

**Comment by yuxuanxinchen** [comment]
操作系统版本为 centos7.2  rocketmq版本为4.2   该问题主要是在consumer启动一段时间后就会抛这个异常，启动三个consumer，关掉其中一个，其他两个也会抛这个异常，底层response返回的是25

**Comment by dominicqi** [comment]
看起来像是这个问题  https://github.com/apache/rocketmq/issues/363#issuecomment-405515530

**Comment by xingfudeshi** [comment]
@dominicqi yes,it's same problem.

**Comment by yuanlai59** [comment]
same warning
[WARN ][2018-07-25 13:04:15] org.apache.rocketmq.client.impl.consumer.DefaultMQPushConsumerImpl$1.onException(DefaultMQPushConsumerImpl.java:384) 
execute the pull request exception
org.apache.rocketmq.client.exception.MQBrokerException: CODE: 25  DESC: the consumer's subscription not latest
For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.processPullResponse(MQClientAPIImpl.java:640)
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.access$200(MQClientAPIImpl.java:155)
	at org.apache.rocketmq.client.impl.MQClientAPIImpl$2.operationComplete(MQClientAPIImpl.java:592)
	at org.apache.rocketmq.remoting.netty.ResponseFuture.executeInvokeCallback(ResponseFuture.java:51)
	at org.apache.rocketmq.remoting.netty.NettyRemotingAbstract$2.run(NettyRemotingAbstract.java:286)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

**Comment by vongosling** [comment]
@yuxuanxinchen 请用最新版本验证，如果还有问题，发邮件到rocketmq user列表里，感谢你的支持。
