### ISSUE TITLE
dledger parameter value format problem

### ISSUE THREAD

**Issue by xhsky** [apache/rocketmq#3701]
**BUG REPORT**

1. Please describe the issue you observed:
Does the dLegerSelfId parameter value have to be two bytes and contain letters and numbers?  I tried it, only in this case can it start normally

- What did you do (The steps to reproduce)?
```
# cat conf/dledger.conf 
brokerClusterName = mq_cluster
brokerName=node
listenPort=30911
namesrvAddr=mq1:9876;mq2:9876;mq3:9876
storePathRootDir=/tmp/rmqstore/node00
storePathCommitLog=/tmp/rmqstore/node00/commitlog
enableDLegerCommitLog=true
dLegerGroup=node
dLegerPeers=node1-mq1:40911;node2-mq2:40912;node3-mq3:40913
## must be unique
dLegerSelfId=node1
sendMessageThreadPoolNums=16


./bin/mqbroker -c conf/dledger.conf 
java.lang.NumberFormatException: For input string: "ode1"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.valueOf(Integer.java:766)
        at org.apache.rocketmq.store.dledger.DLedgerCommitLog.<init>(DLedgerCommitLog.java:98)
        at org.apache.rocketmq.store.DefaultMessageStore.<init>(DefaultMessageStore.java:129)
        at org.apache.rocketmq.broker.BrokerController.initialize(BrokerController.java:243)
        at org.apache.rocketmq.broker.BrokerStartup.createBrokerController(BrokerStartup.java:222)
        at org.apache.rocketmq.broker.BrokerStartup.main(BrokerStartup.java:58)

```

2. Please tell us about your environment:
os version: Centos7
jdk version: jdk-8u251-linux-x64.tar.gz
mq version: rocketmq-all-4.8.0-bin-release.zip

**Comment by Git-Yang** [comment]
The second byte must be an integer, such as n0, n1, n2.

**Comment by Git-Yang** [comment]
> > The second byte must be an integer, such as n0, n1, n2.
> 
> Why define it this way? @Git-Yang

![image](https://user-images.githubusercontent.com/30995057/148875054-07e06555-f9b4-4797-bf70-2084cc2d649c.png)
The broker role id is parsed according to dLegerSelfId
