### ISSUE TITLE
DefaultLitePullConsumer seek(MessageQueue,Offset) report   An error occurred in pull message process.

### ISSUE THREAD

**Issue by bxvs888** [apache/rocketmq#3853]
code 

		DefaultLitePullConsumer consumer =new DefaultLitePullConsumer("abc","testConsumer", null);
		consumer.setNamesrvAddr("192.168.64.7:9876");
		consumer.start();
		consumer.setAutoCommit(true);

            Collection<MessageQueue> messageQueue2 =  consumer.fetchMessageQueues("topic");

	consumer.assign(list);
		for(MessageQueue mq:list){
			consumer.seek(mq,0);
			System.out.println(mq);
		}

		while (true){
			List<MessageExt> messageExtList =consumer.poll();
			System.out.println(messageExtList.size()); 
            }

report error:

22-02-15 18:13:05,976 INFO RocketmqRemoting - createChannel: begin to connect remote host[192.168.64.7:9876] asynchronously
2022-02-15 18:13:05,984 INFO RocketmqRemoting - NETTY CLIENT PIPELINE: CONNECT  UNKNOWN => 192.168.64.7:9876
2022-02-15 18:13:05,986 INFO RocketmqRemoting - createChannel: connect remote host[192.168.64.7:9876] success, AbstractBootstrap$PendingRegistrationPromise@68ad99fe(success)
2022-02-15 18:13:05,992 DEBUG io.netty.util.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@78f76823
2022-02-15 18:13:05,992 DEBUG io.netty.util.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@78f76823
2022-02-15 18:13:05,992 DEBUG io.netty.util.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@78f76823
2022-02-15 18:13:06,060 INFO RocketmqClient - the topic[TBW102] route info changed, old[null] ,new[TopicRouteData [orderTopicConf=null, queueDatas=[QueueData [brokerName=rocketmq, readQueueNums=8, writeQueueNums=8, perm=7, topicSysFlag=0]], brokerDatas=[BrokerData [brokerName=rocketmq, brokerAddrs={0=192.168.64.7:10911}]], filterServerTable={}]]
2022-02-15 18:13:06,060 INFO RocketmqClient - updateTopicPublishInfo prev is not null, TopicPublishInfo [orderTopic=false, messageQueueList=[], sendWhichQueue=ThreadLocalIndex{threadLocalIndex=null}, haveTopicRouterInfo=false]
2022-02-15 18:13:06,060 INFO RocketmqClient - topicRouteTable.put. Topic = TBW102, TopicRouteData[TopicRouteData [orderTopicConf=null, queueDatas=[QueueData [brokerName=rocketmq, readQueueNums=8, writeQueueNums=8, perm=7, topicSysFlag=0]], brokerDatas=[BrokerData [brokerName=rocketmq, brokerAddrs={0=192.168.64.7:10911}]], filterServerTable={}]]
2022-02-15 18:13:06,149 INFO RocketmqRemoting - createChannel: begin to connect remote host[192.168.64.7:10911] asynchronously
2022-02-15 18:13:06,149 INFO RocketmqRemoting - NETTY CLIENT PIPELINE: CONNECT  UNKNOWN => 192.168.64.7:10911
2022-02-15 18:13:06,150 INFO RocketmqRemoting - createChannel: connect remote host[192.168.64.7:10911] success, AbstractBootstrap$PendingRegistrationPromise@1752d4ed(success)
2022-02-15 18:13:06,150 INFO RocketmqRemoting - createChannel: connect remote host[192.168.64.7:10911] success, AbstractBootstrap$PendingRegistrationPromise@1752d4ed(success)
2022-02-15 18:13:06,150 INFO RocketmqRemoting - createChannel: connect remote host[192.168.64.7:10911] success, AbstractBootstrap$PendingRegistrationPromise@1752d4ed(success)
2022-02-15 18:13:06,150 INFO RocketmqRemoting - createChannel: connect remote host[192.168.64.7:10911] success, AbstractBootstrap$PendingRegistrationPromise@1752d4ed(success)
2022-02-15 18:13:06,150 INFO RocketmqRemoting - createChannel: connect remote host[192.168.64.7:10911] success, AbstractBootstrap$PendingRegistrationPromise@1752d4ed(success)
2022-02-15 18:13:06,150 INFO RocketmqRemoting - createChannel: connect remote host[192.168.64.7:10911] success, AbstractBootstrap$PendingRegistrationPromise@1752d4ed(success)
2022-02-15 18:13:06,150 INFO RocketmqRemoting - createChannel: connect remote host[192.168.64.7:10911] success, AbstractBootstrap$PendingRegistrationPromise@1752d4ed(success)
2022-02-15 18:13:06,150 INFO RocketmqRemoting - createChannel: connect remote host[192.168.64.7:10911] success, AbstractBootstrap$PendingRegistrationPromise@1752d4ed(success)
2022-02-15 18:13:06,150 INFO RocketmqRemoting - createChannel: connect remote host[192.168.64.7:10911] success, AbstractBootstrap$PendingRegistrationPromise@1752d4ed(success)
2022-02-15 18:13:06,150 INFO RocketmqRemoting - createChannel: connect remote host[192.168.64.7:10911] success, AbstractBootstrap$PendingRegistrationPromise@1752d4ed(success)
2022-02-15 18:13:06,150 INFO RocketmqRemoting - createChannel: connect remote host[192.168.64.7:10911] success, AbstractBootstrap$PendingRegistrationPromise@1752d4ed(success)
2022-02-15 18:13:06,150 INFO RocketmqRemoting - createChannel: connect remote host[192.168.64.7:10911] success, AbstractBootstrap$PendingRegistrationPromise@1752d4ed(success)
2022-02-15 18:13:06,150 INFO RocketmqRemoting - createChannel: connect remote host[192.168.64.7:10911] success, AbstractBootstrap$PendingRegistrationPromise@1752d4ed(success)
2022-02-15 18:13:06,151 INFO RocketmqRemoting - createChannel: connect remote host[192.168.64.7:10911] success, AbstractBootstrap$PendingRegistrationPromise@1752d4ed(success)
2022-02-15 18:13:06,151 INFO RocketmqRemoting - createChannel: connect remote host[192.168.64.7:10911] success, AbstractBootstrap$PendingRegistrationPromise@1752d4ed(success)
2022-02-15 18:13:06,151 INFO RocketmqRemoting - createChannel: connect remote host[192.168.64.7:10911] success, AbstractBootstrap$PendingRegistrationPromise@1752d4ed(success)
2022-02-15 18:13:06,151 INFO RocketmqRemoting - createChannel: connect remote host[192.168.64.7:10911] success, AbstractBootstrap$PendingRegistrationPromise@1752d4ed(success)
2022-02-15 18:13:06,151 INFO RocketmqRemoting - createChannel: connect remote host[192.168.64.7:10911] success, AbstractBootstrap$PendingRegistrationPromise@1752d4ed(success)
2022-02-15 18:13:06,151 INFO RocketmqRemoting - createChannel: connect remote host[192.168.64.7:10911] success, AbstractBootstrap$PendingRegistrationPromise@1752d4ed(success)
2022-02-15 18:13:06,151 INFO RocketmqRemoting - createChannel: connect remote host[192.168.64.7:10911] success, AbstractBootstrap$PendingRegistrationPromise@1752d4ed(success)
2022-02-15 18:13:06,151 INFO RocketmqRemoting - createChannel: connect remote host[192.168.64.7:10911] success, AbstractBootstrap$PendingRegistrationPromise@1752d4ed(success)
2022-02-15 18:13:06,162 ERROR RocketmqClient - An error occurred in pull message process.
java.lang.InterruptedException
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1081)
	at java.base/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:276)
	at org.apache.rocketmq.remoting.netty.ResponseFuture.waitResponse(ResponseFuture.java:71)
	at org.apache.rocketmq.remoting.netty.NettyRemotingAbstract.invokeSyncImpl(NettyRemotingAbstract.java:434)
	at org.apache.rocketmq.remoting.netty.NettyRemotingClient.invokeSync(NettyRemotingClient.java:377)
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.pullMessageSync(MQClientAPIImpl.java:772)
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.pullMessage(MQClientAPIImpl.java:726)
	at org.apache.rocketmq.client.impl.consumer.PullAPIWrapper.pullKernelImpl(PullAPIWrapper.java:200)
	at org.apache.rocketmq.client.impl.consumer.DefaultLitePullConsumerImpl.pullSyncImpl(DefaultLitePullConsumerImpl.java:910)
	at org.apache.rocketmq.client.impl.consumer.DefaultLitePullConsumerImpl.pull(DefaultLitePullConsumerImpl.java:885)
	at org.apache.rocketmq.client.impl.consumer.DefaultLitePullConsumerImpl.pull(DefaultLitePullConsumerImpl.java:880)
	at org.apache.rocketmq.client.impl.consumer.DefaultLitePullConsumerImpl.access$1400(DefaultLitePullConsumerImpl.java:77)
	at org.apache.rocketmq.client.impl.consumer.DefaultLitePullConsumerImpl$PullTaskImpl.run(DefaultLitePullConsumerImpl.java:831)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

2022-02-15 18:13:06,162 WARN RocketmqClient - The Pull Task is cancelled after doPullTask, MessageQueue [topic=abc%4131412277592745308, brokerName=rocketmq, queueId=3]
2022-02-15 18:13:06,165 ERROR RocketmqClient - An error occurred in pull message process.

**Comment by ni-ze** [comment]
consumer.seek(mq,0) will interrupt polling thread starting at  consumer.start(); 
It is just an error log, not an exception.
This log maybe ignored in DefaultLitePullConsumer.
