### ISSUE TITLE
ACL feature request

### ISSUE THREAD

**Issue by duhengforever** [apache/rocketmq#403]
**FEATURE REQUEST**
In the production environment, since RocketMQ lacks permission control for the topic，that lead to it is often encountered that the wrong topic is sent and the wrong topic is subscribed. Therefore, I think RocketMQ should support the ACL feature.

**Comment by FunriLy** [comment]
### 第一组解决方案
我们可以考虑在RPC交互中添加一个用户的概念来增加ACL模块。
我们的Producer集群会在向Broker集群写入数据时，附带上userId与password进行身份验证。而我们的Consumer集群在向Broker集群发起订阅动作，将会附带上用户userId进行对于Topic的身份验证。
![](https://s1.ax1x.com/2018/08/14/PgqFc6.png)

在BrokerMaster上维护一个关于"topic-group-user-operation"的关系映射表，通过Broker之间主备节点异步更新映射表。由于slave节点是定时向master节点同步信息，所以集群内只保证数据最终一致性。该映射关系表将用于对订阅用户userId进行身份验证。
关于关系映射表，我们考虑设计如图为：我们希望能够快速定位某个Topic下拥有某种操作权限的用户群体(暂时分为 Read、Write、Owner 三种操作，可后续扩展 Update、Delete 等)。
![](https://s1.ax1x.com/2018/08/14/PgqVBD.png)

最终，在客户端对Topic进行操作时都将进行一次身份验证，已确定对应的客户端拥有确定的权限。

其他问题：
1、考虑过加一个APPID对应用进行区分，但是考虑到如果有一个可能性的话：与第三方ACL权限系统对接，将以用户为主导角色，所以采用userId与password作为一个标识属性。
2、关于主备节点间消息同步问题，我们考虑将userId与Topic的映射关系通过TopicConfig同步到整个Broker集群。

**Comment by linhu93** [comment]
# 第二组，为RocketMQ添加ACL功能
 
## Goal

为RocketMQ添加权限控制，使得某个用户对某个topic有写权限，某个group的某个consumer对某个topic有读权限。

## Design

在NameServer中添加RocketMQ的权限控制表
含义	       rocketmq.client.name	主题	               权限
属性名	instanceName	                topic         	operation
取值		 “name”                         “topicName”         r/w
RocketMQ可以使用CLI admin tools实现管理。在bash mqadmin列表中添加对ACL的操作，并将权限控制表推送到NameServer上，实现对权限控制表的读写操作(其他操作后续可以扩展)。
目前操作主要包含权限读写两类，其RequestCode分别为ACL_WRITE_CONFIG = 323和ACL_READ_CONFIG = 324。
写入权限控制项
bash mqadmin aclWrite -i “instanceName” -t “topic” -o “operation”
其中operation为“r”或“w”表示读写权限
读取权限控制项
bash mqadmin aclRead -i “instanceName” -t “topic” -r “r”

## Impl

Add adminTool impl, RpcHook impl and NameServer communication protocol.

## Test

UnitTest for most functions.

## Verification

Verified,compile succeed.

## Future work

NameServer listener implementation to improve cache,  namesrv act table persistence store.

[PR addr](https://github.com/apache/rocketmq/pull/415)

**Comment by dongeforever** [comment]
The community is developing the acl on branch "feature_acl"

**Comment by jayden88** [comment]
@dongeforever 咨询个问题，ACL特性什么时候会合入主干

**Comment by zongtanghu** [comment]
@jayden88 The feature acl have already been merged.You can see the codes in the 4.4.0 version of RocketMQ.

**Comment by manpure** [comment]
@zongtanghu 官方文档中怎么没有acl的相关介绍？

**Comment by zongtanghu** [comment]
please look at the develop branch of rocketmq,the acl doc is at the doc fold.https://github.com/apache/rocketmq/tree/develop/docs/cn/acl 



huzongtang@cmss.chinamobile.com
 
From: manpure
Date: 2019-02-15 17:04
To: apache/rocketmq
CC: Hu Zongtang; Mention
Subject: Re: [apache/rocketmq] ACL feature request (#403)
@zongtanghu 官方文档中怎么没有acl的相关介绍？

**Comment by haoforliu** [comment]
@dongeforever 你好！ 提个问题：
我在开启ACL后，使用如下方式发送消息：
SessionCredentials sc = new SessionCredentials("accessKey", "secretKey");
RPCHook hook = new AclClientRPCHook(sc);
DefaultMQProducer producer = new DefaultMQProducer("producer_group", hook);
结果会出现这样的异常：
org.apache.rocketmq.client.exception.MQClientException: Send [3] times, still failed, cost [864]ms, Topic: test_filter, BrokersSent: [broker-a, broker-b, broker-a]
See http://rocketmq.apache.org/docs/faq/ for further details.
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendDefaultImpl(DefaultMQProducerImpl.java:632)
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1279)
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1225)
	at org.apache.rocketmq.client.producer.DefaultMQProducer.send(DefaultMQProducer.java:283)
	at test_rockemq.TestFilter.produce(TestFilter.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:39)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.Iterator.forEachRemaining(Unknown Source)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:79)
	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:70)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:170)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:154)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
Caused by: org.apache.rocketmq.client.exception.MQBrokerException: CODE: 1  DESC: org.apache.rocketmq.acl.common.AclException: [10015:signature-failed] unable to calculate a request signature. error=[10015:signature-failed] unable to calculate a request signature. error=Algorithm HmacSHA1 not available, org.apache.rocketmq.acl.common.AclSigner.signAndBase64Encode(AclSigner.java:84)
For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.processSendResponse(MQClientAPIImpl.java:556)
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessageSync(MQClientAPIImpl.java:358)
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessage(MQClientAPIImpl.java:340)
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessage(MQClientAPIImpl.java:294)
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendKernelImpl(DefaultMQProducerImpl.java:807)
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendDefaultImpl(DefaultMQProducerImpl.java:551)
	... 45 more

请问是Algorithm HmacSHA1不可用的原因是什么？
PS: rocketmq的版本是4.4.0

**Comment by zongtanghu** [comment]
You can refer to AclClient demo which is in the example module.Thanks!



huzongtang@cmss.chinamobile.com
 
From: haoforliu
Date: 2019-03-13 18:51
To: apache/rocketmq
CC: Hu Zongtang; Mention
Subject: Re: [apache/rocketmq] ACL feature request (#403)
@dongeforever 你好！ 提个问题：
我在开启ACL后，使用如下方式发送消息：
SessionCredentials sc = new SessionCredentials("accessKey", "secretKey");
RPCHook hook = new AclClientRPCHook(sc);
DefaultMQProducer producer = new DefaultMQProducer("producer_group", hook);
结果会出现这样的异常：
org.apache.rocketmq.client.exception.MQClientException: Send [3] times, still failed, cost [864]ms, Topic: test_filter, BrokersSent: [broker-a, broker-b, broker-a]
See http://rocketmq.apache.org/docs/faq/ for further details.
at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendDefaultImpl(DefaultMQProducerImpl.java:632)
at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1279)
at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1225)
at org.apache.rocketmq.client.producer.DefaultMQProducer.send(DefaultMQProducer.java:283)
at test_rockemq.TestFilter.produce(TestFilter.java:39)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:39)
at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
at java.util.Iterator.forEachRemaining(Unknown Source)
at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
at java.util.stream.ReferencePipeline.forEach(Unknown Source)
at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:79)
at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:70)
at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:170)
at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:154)
at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:86)
at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
Caused by: org.apache.rocketmq.client.exception.MQBrokerException: CODE: 1 DESC: org.apache.rocketmq.acl.common.AclException: [10015:signature-failed] unable to calculate a request signature. error=[10015:signature-failed] unable to calculate a request signature. error=Algorithm HmacSHA1 not available, org.apache.rocketmq.acl.common.AclSigner.signAndBase64Encode(AclSigner.java:84)
For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
at org.apache.rocketmq.client.impl.MQClientAPIImpl.processSendResponse(MQClientAPIImpl.java:556)
at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessageSync(MQClientAPIImpl.java:358)
at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessage(MQClientAPIImpl.java:340)
at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessage(MQClientAPIImpl.java:294)
at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendKernelImpl(DefaultMQProducerImpl.java:807)
at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendDefaultImpl(DefaultMQProducerImpl.java:551)
... 45 more
请问是Algorithm HmacSHA1不可用的原因是什么？
PS: rocketmq的版本是4.4.0

**Comment by haoforliu** [comment]
@duhengforever 
我的写法就是参照AclClient demo的，而且我刚刚修改demo里的参数，运行还是报同样的错啊。
以下是代码：
public static void producer() throws MQClientException {
        DefaultMQProducer producer = new DefaultMQProducer("ProducerGroupName", getAclRPCHook());
        producer.setNamesrvAddr(ADDR);
        producer.start();

        for (int i = 0; i < 128; i++)
            try {
                {
                    Message msg = new Message("TopicTest",
                        "TagA",
                        "OrderID188",
                        "Hello world".getBytes(RemotingHelper.DEFAULT_CHARSET));
                    SendResult sendResult = producer.send(msg);
                    System.out.printf("%s%n", sendResult);
                }

            } catch (Exception e) {
                e.printStackTrace();
            }

        producer.shutdown();
}

static RPCHook getAclRPCHook() {
        return new AclClientRPCHook(new SessionCredentials(ACL_ACCESS_KEY,ACL_SECRET_KEY));
    }

**Comment by zongtanghu** [comment]
@haoforliu You can check you jdk version.From your content of log info,I think it may be your jdk version problem.

**Comment by overflow0503** [comment]
@haoforliu 请问解决这个问题了吗，我也出现这个问题了

**Comment by haoforliu** [comment]
> @haoforliu 请问解决这个问题了吗，我也出现这个问题了

建议先查看下相关的日志，看看异常的具体原因。

**Comment by xh800** [comment]
有人解决了吗

**Comment by FansinZhao** [comment]
> @dongeforever 你好！ 提个问题：
> 我在开启ACL后，使用如下方式发送消息：
> SessionCredentials sc = new SessionCredentials("accessKey", "secretKey");
> RPCHook hook = new AclClientRPCHook(sc);
> DefaultMQProducer producer = new DefaultMQProducer("producer_group", hook);
> 结果会出现这样的异常：
> org.apache.rocketmq.client.exception.MQClientException: Send [3] times, still failed, cost [864]ms, Topic: test_filter, BrokersSent: [broker-a, broker-b, broker-a]
> See http://rocketmq.apache.org/docs/faq/ for further details.
> at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendDefaultImpl(DefaultMQProducerImpl.java:632)
> at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1279)
> at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1225)
> at org.apache.rocketmq.client.producer.DefaultMQProducer.send(DefaultMQProducer.java:283)
> at test_rockemq.TestFilter.produce(TestFilter.java:39)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> at java.lang.reflect.Method.invoke(Unknown Source)
> at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
> at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
> at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
> at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
> at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
> at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
> at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
> at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
> at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
> at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
> at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
> at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
> at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
> at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
> at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
> at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:39)
> at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
> at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
> at java.util.Iterator.forEachRemaining(Unknown Source)
> at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
> at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
> at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
> at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
> at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
> at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
> at java.util.stream.ReferencePipeline.forEach(Unknown Source)
> at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:79)
> at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:70)
> at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:170)
> at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:154)
> at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
> at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:86)
> at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
> at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
> at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
> at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
> at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
> Caused by: org.apache.rocketmq.client.exception.MQBrokerException: CODE: 1 DESC: org.apache.rocketmq.acl.common.AclException: [10015:signature-failed] unable to calculate a request signature. error=[10015:signature-failed] unable to calculate a request signature. error=Algorithm HmacSHA1 not available, org.apache.rocketmq.acl.common.AclSigner.signAndBase64Encode(AclSigner.java:84)
> For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
> at org.apache.rocketmq.client.impl.MQClientAPIImpl.processSendResponse(MQClientAPIImpl.java:556)
> at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessageSync(MQClientAPIImpl.java:358)
> at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessage(MQClientAPIImpl.java:340)
> at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessage(MQClientAPIImpl.java:294)
> at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendKernelImpl(DefaultMQProducerImpl.java:807)
> at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendDefaultImpl(DefaultMQProducerImpl.java:551)
> ... 45 more
> 
> 请问是Algorithm HmacSHA1不可用的原因是什么？
> PS: rocketmq的版本是4.4.0

我解决了这个问题，问题在于Algorithm HmacSHA1这个算法是在${JAVA_HOME}/jre/lib/ext文件夹下的sunjce_provider.jar,所以需要将此目录增加到CLASSPATH中，注意如果启动脚本使用`-Djava.ext.dirs`，这个参数会将默认的ext覆盖掉，如果使用这个参数，注意将${JAVA_HOME}/jre/lib/ext追加到后面。

**Comment by xh800** [comment]
大佬解决这个问题的思路是啥，膜拜

**Comment by FansinZhao** [comment]
> 大佬解决这个问题的思路是啥，膜拜

公司使用的rocketmq 3.X，需要增加一个鉴权功能，然后参考4.4+版本，给3.x版本增加了acl功能，目前已经做好了，中间踩了坑，这个是其中一个坑。出现问题了，就看异常，搜索，思考，排查，定位，修改，解决，常规套路。
