### ISSUE TITLE
The official website's 'order example' exec failed

### ISSUE THREAD

**Issue by Oliverwqcwrw** [apache/rocketmq#4043]
**BUG REPORT**

1. Please describe the issue you observed:

The official website's order example is executing failed  [https://rocketmq.apache.org/docs/order-example/](https://rocketmq.apache.org/docs/order-example/)

- What did you do (The steps to reproduce)?

- What is expected to see?

It can send message normally

- What did you see instead?

> Exception in thread "main" java.lang.IllegalStateException: org.apache.rocketmq.remoting.exception.RemotingConnectException: connect to null failed
	at org.apache.rocketmq.client.impl.factory.MQClientInstance.updateTopicRouteInfoFromNameServer(MQClientInstance.java:680)
	at org.apache.rocketmq.client.impl.factory.MQClientInstance.updateTopicRouteInfoFromNameServer(MQClientInstance.java:510)
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.tryToFindTopicPublishInfo(DefaultMQProducerImpl.java:683)
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendSelectImpl(DefaultMQProducerImpl.java:1128)
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1114)
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1109)
	at org.apache.rocketmq.client.producer.DefaultMQProducer.send(DefaultMQProducer.java:518)
	at com.aolifu.producer.OrderedProducer.main(OrderedProducer.java:25)
Caused by: org.apache.rocketmq.remoting.exception.RemotingConnectException: connect to null failed
	at org.apache.rocketmq.remoting.netty.NettyRemotingClient.invokeSync(NettyRemotingClient.java:407)
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.getTopicRouteInfoFromNameServer(MQClientAPIImpl.java:1379)
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.getTopicRouteInfoFromNameServer(MQClientAPIImpl.java:1369)
	at org.apache.rocketmq.client.impl.factory.MQClientInstance.updateTopicRouteInfoFromNameServer(MQClientInstance.java:623)
	... 7 more

3. Please tell us about your environment:

Mac OS 12.3
rocketMQ 4.9.3

**Comment by Oliverwqcwrw** [comment]
The `com.aolifu.consumer.OrderedConsumer` also start failed,and error message is same

**Comment by RongtongJin** [comment]
看起来是连接nameserver失败了，看下是否正确设置了nameserveer，以及producer与nameserver网络是否连通

**Comment by Oliverwqcwrw** [comment]
The problem is that `nameserver` is not set, I think the example need to optimize, Do you think?

**Comment by HScarb** [comment]
When `nameserver` not set for client, it will get environment variable `NAMESRV_ADDR` as name server address by default.

**Comment by Oliverwqcwrw** [comment]
Thank you your reply
