### ISSUE TITLE
MQClientException: No route info of this topic

### ISSUE THREAD

**Issue by jeffchanjunwei** [apache/rocketmq#4359]
1. Please describe the issue you observed:

- What did you see instead?

```
Send Failed.
org.apache.rocketmq.client.exception.MQClientException: No route info of this topic, EW_RFLOW_NOTIFY_RESULT
See http://rocketmq.apache.org/docs/faq/ for further details.
        at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendDefaultImpl(DefaultMQProducerImpl.java:564)
        at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1069)
        at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1023)
        at org.apache.rocketmq.client.producer.DefaultMQProducer.send(DefaultMQProducer.java:214)
```

2. Please tell us about your environment:

nameserver and broker : v4.8.0 & 2 master + 4slave dledger-mode & netty version 4.0.42.Final；
client: v4.2.0 & netty version 4.0.54.Final；

3. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):

broker's autoCreateTopic is setted to false. We can see the topic is created manual in the two namesrv's log as follow 

```
2022-05-18 11:09:58 INFO RemotingExecutorThread_2 - new topic registered, EW_RFLOW_NOTIFY_RESULT QueueData [brokerName=broker-b, readQueueNums=8, writeQueueNums=8, perm=6, topicSynFlag=0]
```

alse in the two broker's log as follow:

```
2022-05-18 11:09:57 INFO AdminBrokerThread_15 - create new topic [TopicConfig [topicName=EW_RFLOW_NOTIFY_RESULT, readQueueNums=8, writeQueueNums=8, perm=RW-, topicFilterType=SINGLE_TAG, topicSysFlag=0, order=false]]
```

but we cannot find the related log of the producer client group registed to the broker and namesrv, and find a lot of other consumer client log as follow :

```
2022-05-18 18:48:58 WARN PullMessageThread_8 - The broker's subscription is not latest, group: cb-ew-entry|EW_RFLOW_NOTIFY_RESULT|EW_RFLOW_NOTIFY_ENTRY_REFUND|RefundReviewResultListener EW_RFLOW_NOTIFY_ENTRY_REFUND
2022-05-18 18:48:58 WARN PullMessageThread_17 - The broker's subscription is not latest, group: cb-ew-entry|EW_RFLOW_NOTIFY_RESULT|EW_RFLOW_NOTIFY_ENTRY_REFUND|RefundReviewResultListener EW_RFLOW_NOTIFY_ENTRY_REFUND
2022-05-18 18:48:58 WARN PullMessageThread_24 - The broker's subscription is not latest, group: cb-ew-entry|EW_RFLOW_NOTIFY_RESULT|EW_RFLOW_NOTIFY_ENTRY_REFUND|RefundReviewResultListener EW_RFLOW_NOTIFY_ENTRY_REFUND
2022-05-18 18:48:58 WARN PullMessageThread_3 - The broker's subscription is not latest, group: cb-ew-entry|EW_RFLOW_NOTIFY_RESULT|EW_RFLOW_NOTIFY_ENTRY_REFUND|RefundReviewResultListener EW_RFLOW_NOTIFY_ENTRY_REFUND
2022-05-18 18:48:58 WARN PullMessageThread_9 - The broker's subscription is not latest, group: cb-ew-entry|EW_RFLOW_NOTIFY_RESULT|EW_RFLOW_NOTIFY_ENTRY_REFUND|RefundReviewResultListener EW_RFLOW_NOTIFY_ENTRY_REFUND
2022-05-18 18:48:58 WARN PullMessageThread_2 - The broker's subscription is not latest, group: cb-ew-entry|EW_RFLOW_NOTIFY_RESULT|EW_RFLOW_NOTIFY_ENTRY_REFUND|RefundReviewResultListener EW_RFLOW_NOTIFY_ENTRY_REFUND
2022-05-18 18:48:58 WARN PullMessageThread_7 - The broker's subscription is not latest, group: cb-ew-entry|EW_RFLOW_NOTIFY_RESULT|EW_RFLOW_NOTIFY_ENTRY_REFUND|RefundReviewResultListener EW_RFLOW_NOTIFY_ENTRY_REFUND
2022-05-18 18:48:58 WARN PullMessageThread_23 - The broker's subscription is not latest, group: cb-ew-entry|EW_RFLOW_NOTIFY_RESULT|EW_RFLOW_NOTIFY_ENTRY_REFUND|RefundReviewResultListener EW_RFLOW_NOTIFY_ENTRY_REFUND
```

**Comment by jeffchanjunwei** [comment]
fix. It's the problem of namesrv config.
