### ISSUE TITLE
Deleger 高可用集群模式导致cpu 偏高

### ISSUE THREAD

**Issue by sydcph** [apache/rocketmq#4415]
rocketmq 版本：4.9.3 
集群模式：deleger  1master  2slave

问题现象：
再三台机器都正常的情况下，master所在的机器 会一直有两个broker 线程占用 100% CPU，将master kill 后，重新选举出来的master同样会出现这个问题，kill 2个slave 节点 ，master 上的此问题消失

jstack  分析得出的问题代码 ：

java.lang.Thread.State: RUNNABLE
at java.lang.Thread.yield(Native Method)
at io.openmessaging.storage.dledger.DLedgerEntryPusher$EntryDispatcher.doWork(DLedgerEntryPusher.java:742)
at io.openmessaging.storage.dledger.ShutdownAbleThread.run(ShutdownAbleThread.java:86)

百度问题后，有人说是deleger模式是主从复制是由Master发起，主动向每个从节点同步消息，因此导致此问题，但提到V4.8.0版本后已优化。但目前消息量还没有多大，感觉消息量增大后会发生服务down 掉的问题。

请问针对此问题，有没有有效的优化方案？

![image](https://user-images.githubusercontent.com/37522802/172061437-dd42eef1-f3ec-4244-b33e-70a812647457.png)

**Comment by sydcph** [comment]
图中是百度出的deleger模式优化方案，但为找到具体的优化信息

**Comment by sydcph** [comment]
> 这个问题会在下一个版本中修复，可以参考[openmessaging/dledger#123](https://github.com/openmessaging/dledger/pull/123) ，或者升级一下dledger的版本到最新0.2.6后编译打包也可以解决。

问一下，下个版本预计什么时间
