### ISSUE TITLE
RocketMQClient java.lang.StackOverflowError

### ISSUE THREAD

**Issue by zhangle910522** [apache/rocketmq#4431]
Springboot 2.0.6 starting exception

Caused by: java.lang.StackOverflowError
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_151]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_151]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_151]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[?:1.8.0_151]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[?:1.8.0_151]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[?:1.8.0_151]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[?:1.8.0_151]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_151]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[?:1.8.0_151]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_151]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335) ~[?:1.8.0_151]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_151]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_151]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_151]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_151]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[?:1.8.0_151]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[?:1.8.0_151]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[?:1.8.0_151]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[?:1.8.0_151]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_151]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[?:1.8.0_151]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_151]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335) ~[?:1.8.0_151]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_151]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_151]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_151]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_151]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[?:1.8.0_151]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[?:1.8.0_151]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[?:1.8.0_151]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[?:1.8.0_151]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_151]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[?:1.8.0_151]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_151]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335) ~[?:1.8.0_151]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_151]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_151]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_151]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_151]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[?:1.8.0_151]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[?:1.8.0_151]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[?:1.8.0_151]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[?:1.8.0_151]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_151]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[?:1.8.0_151]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_151]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335) ~[?:1.8.0_151]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_151]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_151]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_151]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_151]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[?:1.8.0_151]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[?:1.8.0_151]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[?:1.8.0_151]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[?:1.8.0_151]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_151]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[?:1.8.0_151]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_151]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335) ~[?:1.8.0_151]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_151]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_151]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_151]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_151]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[?:1.8.0_151]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[?:1.8.0_151]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[?:1.8.0_151]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[?:1.8.0_151]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_151]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[?:1.8.0_151]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_151]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335) ~[?:1.8.0_151]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_151]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_151]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_151]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_151]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[?:1.8.0_151]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[?:1.8.0_151]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[?:1.8.0_151]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[?:1.8.0_151]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_151]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[?:1.8.0_151]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_151]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335) ~[?:1.8.0_151]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_151]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_151]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_151]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_151]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[?:1.8.0_151]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[?:1.8.0_151]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[?:1.8.0_151]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[?:1.8.0_151]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_151]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[?:1.8.0_151]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_151]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335) ~[?:1.8.0_151]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_151]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_151]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_151]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_151]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[?:1.8.0_151]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[?:1.8.0_151]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[?:1.8.0_151]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[?:1.8.0_151]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_151]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[?:1.8.0_151]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_151]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335) ~[?:1.8.0_151]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_151]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_151]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_151]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_151]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[?:1.8.0_151]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[?:1.8.0_151]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[?:1.8.0_151]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[?:1.8.0_151]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_151]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[?:1.8.0_151]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_151]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335) ~[?:1.8.0_151]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_151]
	at io.netty.channel.nio.NioEventLoop.newTaskQueue(NioEventLoop.java:252) ~[netty-all-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.<init>(SingleThreadEventExecutor.java:165) ~[netty-all-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.SingleThreadEventLoop.<init>(SingleThreadEventLoop.java:58) ~[netty-all-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:135) ~[netty-all-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:127) ~[netty-all-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:36) ~[netty-all-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84) ~[netty-all-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58) ~[netty-all-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47) ~[netty-all-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:59) ~[netty-all-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:77) ~[netty-all-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:72) ~[netty-all-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:59) ~[netty-all-4.1.29.Final.jar:4.1.29.Final]
	at org.apache.rocketmq.remoting.netty.NettyRemotingClient.<init>(NettyRemotingClient.java:122) ~[rocketmq-remoting-4.6.0.jar:4.6.0]
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.<init>(MQClientAPIImpl.java:188) ~[rocketmq-client-4.6.0.jar:4.6.0]
	at org.apache.rocketmq.client.impl.factory.MQClientInstance.<init>(MQClientInstance.java:135) ~[rocketmq-client-4.6.0.jar:4.6.0]
	at org.apache.rocketmq.client.impl.MQClientManager.getOrCreateMQClientInstance(MQClientManager.java:53) ~[rocketmq-client-4.6.0.jar:4.6.0]
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.start(DefaultMQProducerImpl.java:189) ~[rocketmq-client-4.6.0.jar:4.6.0]
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.start(DefaultMQProducerImpl.java:175) ~[rocketmq-client-4.6.0.jar:4.6.0]
	at org.apache.rocketmq.client.producer.DefaultMQProducer.start(DefaultMQProducer.java:271) ~[rocketmq-client-4.6.0.jar:4.6.0]
	at org.apache.rocketmq.client.producer.TransactionMQProducer.start(TransactionMQProducer.java:57) ~[rocketmq-client-4.6.0.jar:4.6.0]

**Comment by panzhi33** [comment]
can look at your jvm configuration

**Comment by djl394922860** [comment]
it seem always repeat loadClass lead to stack over flow , check same agent config or bytecode enhancements ?
