### ISSUE TITLE
RocketMQ Error sending asynchronous message. However, the synchronization message is normal

### ISSUE THREAD

**Issue by xmzhao71** [apache/rocketmq#4517]
RemotingConnectException: connect to xxx:10911 failed

**Comment by shy-share** [comment]
You need to describe the specific scenario, not just provide a bug @xmzhao71

**Comment by tsunghanjacktsai** [comment]
Hi @xmzhao71 ,

Would you mind reproducing your problem for us? It's kinda hard to understand the details simply through your issue description :-)

**Comment by xmzhao71** [comment]
> You need to describe the specific scenario, not just provide a bug @xmzhao71

Sending messages synchronously can be successful, but sending messages asynchronously can be problematic 
Below is the error log

org.apache.rocketmq.remoting.exception.RemotingConnectException: connect to 192.66.90.151:10911 failed
	at org.apache.rocketmq.remoting.netty.NettyRemotingClient.invokeAsync(NettyRemotingClient.java:548)
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessageAsync(MQClientAPIImpl.java:535)
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.onExceptionImpl(MQClientAPIImpl.java:628)
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessageAsync(MQClientAPIImpl.java:597)
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.onExceptionImpl(MQClientAPIImpl.java:628)
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessageAsync(MQClientAPIImpl.java:597)
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessage(MQClientAPIImpl.java:490)
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendKernelImpl(DefaultMQProducerImpl.java:824)
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendDefaultImpl(DefaultMQProducerImpl.java:580)
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.access$300(DefaultMQProducerImpl.java:96)
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl$3.run(DefaultMQProducerImpl.java:507)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

**Comment by xmzhao71** [comment]
I know the reason for my mistake

**Comment by lizhiboo** [comment]
@xmzhao71 i will close issue, if have any other question, u can creat a new issue, thanks.
