### ISSUE TITLE
配置tls时，出现错误，请问有文档吗？

### ISSUE THREAD

**Issue by jiangxingang** [apache/rocketmq#453]
配置tls时，出现错误，请问有文档吗？
按https://segmentfault.com/a/1190000010040134自签证书。
然后转成pem格式:
pkcs8 -topk8 -in server.key -out server.pem -nocrypt
pkcs8 -topk8 -in client.key -out client.pem -nocrypt

报private key错误。

Caused by: java.lang.IllegalArgumentException: Input stream does not contain valid private key.
	at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:278) ~[netty-all-4.0.42.Final.jar:4.0.42.Final]
	at org.apache.rocketmq.remoting.netty.TlsHelper.buildSslContext(TlsHelper.java:124) ~[rocketmq-remoting-4.2.0.jar:4.2.0]
	at org.apache.rocketmq.remoting.netty.NettyRemotingClient.<init>(NettyRemotingClient.java:134) ~[rocketmq-remoting-4.2.0.jar:4.2.0]
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.<init>(MQClientAPIImpl.java:176) ~[rocketmq-client-4.2.0.jar:4.2.0]
	at org.apache.rocketmq.client.impl.factory.MQClientInstance.<init>(MQClientInstance.java:132) ~[rocketmq-client-4.2.0.jar:4.2.0]
	at org.apache.rocketmq.client.impl.MQClientManager.getAndCreateMQClientInstance(MQClientManager.java:51) ~[rocketmq-client-4.2.0.jar:4.2.0]
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.start(DefaultMQProducerImpl.java:152) ~[rocketmq-client-4.2.0.jar:4.2.0]
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.start(DefaultMQProducerImpl.java:138) ~[rocketmq-client-4.2.0.jar:4.2.0]
	at org.apache.rocketmq.client.producer.DefaultMQProducer.start(DefaultMQProducer.java:172) ~[rocketmq-client-4.2.0.jar:4.2.0]
	at com.dmsoft.hato.cloud.dai.config.MqConfig.defaultMQProducer(MqConfig.java:33) ~[classes/:na]
	at com.dmsoft.hato.cloud.dai.config.MqConfig$$EnhancerBySpringCGLIB$$9f000672.CGLIB$defaultMQProducer$0(<generated>) ~[classes/:na]
	at com.dmsoft.hato.cloud.dai.config.MqConfig$$EnhancerBySpringCGLIB$$9f000672$$FastClassBySpringCGLIB$$76c0769c.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:358) ~[spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at com.dmsoft.hato.cloud.dai.config.MqConfig$$EnhancerBySpringCGLIB$$9f000672.defaultMQProducer(<generated>) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_65]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_65]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_65]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_65]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	... 32 common frames omitted
Caused by: java.io.IOException: overrun, bytes = 612
	at javax.crypto.EncryptedPrivateKeyInfo.<init>(EncryptedPrivateKeyInfo.java:92) ~[na:1.8.0_60]
	at io.netty.handler.ssl.SslContext.generateKeySpec(SslContext.java:907) ~[netty-all-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.handler.ssl.SslContext.getPrivateKeyFromByteBuffer(SslContext.java:963) ~[netty-all-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.handler.ssl.SslContext.toPrivateKey(SslContext.java:953) ~[netty-all-4.0.42.Final.jar:4.0.42.Final]
	at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:276) ~[netty-all-4.0.42.Final.jar:4.0.42.Final]
	... 51 common frames omitted

请问老大怎么解决？

**Comment by jiangxingang** [comment]
是我证书问题，打扰

**Comment by Yarollingstone** [comment]
> 是我证书问题，打扰
大佬，你最终解决了吗？

**Comment by Gred01** [comment]
请问下证书怎么配置，我按照你给的配置连接也不行

**Comment by Sleepingbug** [comment]
How to configure SSL certificate on the nameserver and broker ?

**Comment by vongosling** [comment]
@ShannonDing Is it possible for us to provide some documentation? There are some holes in ssl configuration. @duhenglucky @duhengforever @RongtongJin

**Comment by chris-joys** [comment]
> @ShannonDing Is it possible for us to provide some documentation? There are some holes in ssl configuration. @duhenglucky @duhengforever @RongtongJin

Hi,现在有可以参考的文档了么？我也出现了同样的问题，但是并没有找到有效的解决方法。

**Comment by ShannonDing** [comment]
https://github.com/apache/rocketmq/blob/develop/remoting/src/test/java/org/apache/rocketmq/remoting/TlsTest.java

**Comment by tjq857** [comment]
> How to configure SSL certificate on the nameserver and broker ?

I really want to know too

**Comment by lizhanhui** [comment]
@tjq857 I would create a wiki page, configuring TLS step by step.

**Comment by tjq857** [comment]
> @tjq857 I would create a wiki page, configuring TLS step by step.

That's will be very useful！

**Comment by lizhanhui** [comment]
Here is the [Work-In-Progress Guide](https://github.com/apache/rocketmq/wiki/How-to-Configure-TLS)

**Comment by echooymxq** [comment]
> Here is the [Work-In-Progress Guide](https://github.com/apache/rocketmq/wiki/How-to-Configure-TLS)

The [Configuration_TLS](https://github.com/apache/rocketmq/blob/develop/docs/en/Configuration_TLS.md) will be replaced?

**Comment by lizhanhui** [comment]
@echooymxq No... I thought there was no such a document...Let's combine their content and enhance its readability.

**Comment by echooymxq** [comment]
> @echooymxq No... I thought there was no such a document...Let's combine their content and enhance its readability.

@lizhanhui That would be great. In fact, i wish the document was more detailed. such as, the `tlsTestModeEnable` property it's a blur for me. as i know, when many cloud vendors  use the ssl feature, the just need customers use one line code.
> producer.setUseTLS(true)

i was wondering think that whether they have abused this property. Usually, we should configure `tls.client.trustCertPath` first isn't it?  so, i'm a bit confused about it name(test mode...).
Hope you help me understand it. 🙏

**Comment by chris-joys** [comment]
> > @tjq857 I would create a wiki page, configuring TLS step by step.
> 
> That's will be very useful！

Hi did you get any error or exception when you configure it following this document in the sysytem. Here is the document:
https://github.com/apache/rocketmq/blob/develop/docs/en/Configuration_TLS.md

if you get errors, you can paste it here.
