### ISSUE TITLE
The admin tool sendMsgStatus add description with brokerName

### ISSUE THREAD

**Issue by Oliverwqcwrw** [apache/rocketmq#4650]
**BUG REPORT**

1. Please describe the issue you observed:

when I exec `./bin/mqadmin sendMsgStatus -n 192.168.137.73:9876 -b 192.168.137.73:10911`

then return 

> 
             org.apache.rocketmq.tools.command.SubCommandException: SendMsgStatusCommand command failed
                at org.apache.rocketmq.tools.command.broker.SendMsgStatusCommand.execute(SendMsgStatusCommand.java:91)
                at org.apache.rocketmq.tools.command.MQAdminStartup.main0(MQAdminStartup.java:149)
                at org.apache.rocketmq.tools.command.MQAdminStartup.main(MQAdminStartup.java:100)
        Caused by: org.apache.rocketmq.client.exception.MQClientException: The specified topic[192.168.137.73:10911] contains illegal characters, allowing only ^[%|a-zA-Z0-9_-]+$
        For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
                at org.apache.rocketmq.client.Validators.checkTopic(Validators.java:90)
                at org.apache.rocketmq.client.Validators.checkMessage(Validators.java:61)
                at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendDefaultImpl(DefaultMQProducerImpl.java:543)
                at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1363)
                at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1307)
                at org.apache.rocketmq.client.producer.DefaultMQProducer.send(DefaultMQProducer.java:333)
                at org.apache.rocketmq.tools.command.broker.SendMsgStatusCommand.execute(SendMsgStatusCommand.java:83)
                ... 2 more

- What did you do (The steps to reproduce)?

- What is expected to see?

It can exec normally

- What did you see instead?

it can not exec

3. Please tell us about your environment:

4.9.4

5. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):

I will submit a pr to fix it

**Comment by lizhiboo** [comment]
@Oliverwqcwrw -b means brokerName, you can set it as cluster1_broker1001 this format.

**Comment by Oliverwqcwrw** [comment]
I get it ,i will add some description about brokerName
