### ISSUE TITLE
NumberFormatException exception

### ISSUE THREAD

**Issue by freedom-all** [apache/rocketmq#4689]
Caused by: org.apache.rocketmq.client.exception.MQBrokerException: CODE: 1  DESC: java.lang.NumberFormatException: For input string: "3sw81-NzMzMjYwYTliYWViNGNiZmE1MTNkNzBhMGFkNWJiMjEuMTM3LjE2NTg3MzI0MTE1MDUwMDMz-NzMzMjYwYTliYWViNGNiZmE1MTNkNzBhMGFkNWJiMjEuMTM3LjE2NTg3MzI0MTE1MDUwMDMy-3-aGlob25vcmFwaS1kZXY=-aGlob25vcmFwaS1kZXYtNjhjOWY0NDRjZC12bWtwYg==-e0dFVH0vZGVtby9kZXY=-MTAuMTIwLjEuMTI5Ojk4NzY=", java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) BROKER: 10.120.1.129:10911
For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.processSendResponse(MQClientAPIImpl.java:668) ~[rocketmq-client-4.9.2.jar!/:4.9.2]
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessageSync(MQClientAPIImpl.java:507) ~[rocketmq-client-4.9.2.jar!/:4.9.2]
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessage$original$1r6gufJZ(MQClientAPIImpl.java:489) ~[rocketmq-client-4.9.2.jar!/:4.9.2]

rocketmq version  4.9.2 

全局搜索了4.9.2的源码没发现这个异常信息，疑问这里在哪里输出的。

**Comment by Oliverwqcwrw** [comment]
please check broker.log

**Comment by freedom-all** [comment]
broker.log not found error log
通过日志应该是发送延时消息的时候转换错误，这个问题很怪异。
 Message message = new Message("u-delay-test", "helloworld".getBytes(StandardCharsets.UTF_8));
            message.setDelayTimeLevel(3);
            producer.send(message, 3000);

问题不是必选，我现在想跟踪代码也找不到.

**Comment by Jean-Jacques-Nuoan** [comment]
请问这个问题解决了么

**Comment by Jean-Jacques-Nuoan** [comment]
messageId后面会跟着添加乱码msgId=7F000001000127EEDB643FF7579E0010sw81-NTIzODkzZDE3YTc1NDYxZWExZGM1ODM2NGUzZjAyN2QuMTcwLjE2ODY2MjE5Njk1ODgwMDQx-NjM3MmYxZDZhZDE3NDk0ZDk5MmRhZGU5ZWYzYzRlM2YuNDAuMTY4NjYyMTk3NDQxNDAwMjI=-4-ZWhjLXNlcnZlcg==-MjQwMDhkYjNkYTFmNDE1ODg4ZTkwN2JhMjZhMDY2MWFAMTAuNDIuMi4zNw==-e1BPU1R9L2FwaS9tZXNzYWdlL3NlbmQ=-MTAuMTEwLjEuOTI6OTg3NjsxMC4xMTAuMS45Mjo5ODc2

**Comment by Jean-Jacques-Nuoan** [comment]
> messageId后面会跟着添加乱码msgId=7F000001000127EEDB643FF7579E0010sw81-NTIzODkzZDE3YTc1NDYxZWExZGM1ODM2NGUzZjAyN2QuMTcwLjE2ODY2MjE5Njk1ODgwMDQx-NjM3MmYxZDZhZDE3NDk0ZDk5MmRhZGU5ZWYzYzRlM2YuNDAuMTY4NjYyMTk3NDQxNDAwMjI=-4-ZWhjLXNlcnZlcg==-MjQwMDhkYjNkYTFmNDE1ODg4ZTkwN2JhMjZhMDY2MWFAMTAuNDIuMi4zNw==-e1BPU1R9L2FwaS9tZXNzYWdlL3NlbmQ=-MTAuMTEwLjEuOTI6OTg3NjsxMC4xMTAuMS45Mjo5ODc2

解决了，跟skywalking冲突了，去掉skywalking的配置就好了

**Comment by ArchimondeLi** [comment]
> > messageId后面会跟着添加乱码msgId=7F000001000127EEDB643FF7579E0010sw81-NTIzODkzZDE3YTc1NDYxZWExZGM1ODM2NGUzZjAyN2QuMTcwLjE2ODY2MjE5Njk1ODgwMDQx-NjM3MmYxZDZhZDE3NDk0ZDk5MmRhZGU5ZWYzYzRlM2YuNDAuMTY4NjYyMTk3NDQxNDAwMjI=-4-ZWhjLXNlcnZlcg==-MjQwMDhkYjNkYTFmNDE1ODg4ZTkwN2JhMjZhMDY2MWFAMTAuNDIuMi4zNw==-e1BPU1R9L2FwaS9tZXNzYWdlL3NlbmQ=-MTAuMTEwLjEuOTI6OTg3NjsxMC4xMTAuMS45Mjo5ODc2
> 
> 解决了，跟skywalking冲突了，去掉skywalking的配置就好了

请问是怎么定位到是skywalking的？

**Comment by Jean-Jacques-Nuoan** [comment]
> > > messageId后面会跟着添加乱码msgId=7F000001000127EEDB643FF7579E0010sw81-NTIzODkzZDE3YTc1NDYxZWExZGM1ODM2NGUzZjAyN2QuMTcwLjE2ODY2MjE5Njk1ODgwMDQx-NjM3MmYxZDZhZDE3NDk0ZDk5MmRhZGU5ZWYzYzRlM2YuNDAuMTY4NjYyMTk3NDQxNDAwMjI=-4-ZWhjLXNlcnZlcg==-MjQwMDhkYjNkYTFmNDE1ODg4ZTkwN2JhMjZhMDY2MWFAMTAuNDIuMi4zNw==-e1BPU1R9L2FwaS9tZXNzYWdlL3NlbmQ=-MTAuMTEwLjEuOTI6OTg3NjsxMC4xMTAuMS45Mjo5ODc2
> > 
> > 
> > 解决了，跟skywalking冲突了，去掉skywalking的配置就好了
> 
> 请问是怎么定位到是skywalking的？

我们有套环境没有skywalking的相关agent的jvm参数配置，是正常的
