### ISSUE TITLE
create mapped file raise io exception, but the file is indeed created succ on the disk.

### ISSUE THREAD

**Issue by reachfish** [apache/rocketmq#486]
hi,  i have a problem in creating a new mapfile. it raise an io exception and retry 30 times,  but all failed with an io exception .  but i found the mapfile is indeed created succ on the disk,  and its file size is right.
would you help me ?

below is the exception stack.

> 2018-10-09 01:14:50 WARN ReputMessageService - [BUG]put commit log position info to BenchmarkTest:304 265047020213 failed, retry 2 times
2018-10-09 01:14:51 ERROR ReputMessageService - map file /data/services/rocketmq-all-4.2.0/data/store/consumequeue/BenchmarkTest/304/00000000000040200000 Failed. 
java.io.IOException: Map failed
        at sun.nio.ch.FileChannelImpl.map(FileChannelImpl.java:940) ~[na:1.8.0_121]
        at org.apache.rocketmq.store.MappedFile.init(MappedFile.java:164) [rocketmq-store-4.2.0.jar:4.2.0]
        at org.apache.rocketmq.store.MappedFile.<init>(MappedFile.java:73) [rocketmq-store-4.2.0.jar:4.2.0]
        at org.apache.rocketmq.store.MappedFileQueue.getLastMappedFile(MappedFileQueue.java:217) [rocketmq-store-4.2.0.jar:4.2.0]
        at org.apache.rocketmq.store.MappedFileQueue.getLastMappedFile(MappedFileQueue.java:237) [rocketmq-store-4.2.0.jar:4.2.0]
        at org.apache.rocketmq.store.ConsumeQueue.putMessagePositionInfo(ConsumeQueue.java:435) [rocketmq-store-4.2.0.jar:4.2.0]
        at org.apache.rocketmq.store.ConsumeQueue.putMessagePositionInfoWrapper(ConsumeQueue.java:397) [rocketmq-store-4.2.0.jar:4.2.0]
        at org.apache.rocketmq.store.DefaultMessageStore.putMessagePositionInfo(DefaultMessageStore.java:1371) [rocketmq-store-4.2.0.jar:4.2.0]
        at org.apache.rocketmq.store.DefaultMessageStore$CommitLogDispatcherBuildConsumeQueue.dispatch(DefaultMessageStore.java:1418) [rocketmq-store-4.2.0.jar:4.2.0]
        at org.apache.rocketmq.store.DefaultMessageStore.doDispatch(DefaultMessageStore.java:1365) [rocketmq-store-4.2.0.jar:4.2.0]
        at org.apache.rocketmq.store.DefaultMessageStore$ReputMessageService.doReput(DefaultMessageStore.java:1763) [rocketmq-store-4.2.0.jar:4.2.0]   
        at org.apache.rocketmq.store.DefaultMessageStore$ReputMessageService.run(DefaultMessageStore.java:1818) [rocketmq-store-4.2.0.jar:4.2.0]       
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
Caused by: java.lang.OutOfMemoryError: Map failed
        at sun.nio.ch.FileChannelImpl.map0(Native Method) ~[na:1.8.0_121]
        at sun.nio.ch.FileChannelImpl.map(FileChannelImpl.java:937) ~[na:1.8.0_121]
        ... 12 common frames omitted

**Comment by duhengforever** [comment]
@reachfish It seems an OutOfMemoryError occurred when mapping a file into memory，and it seems you are running a benchmark case in your environment, so please run rocketmq in a 64-bit server and check the mapped file whether reached the limit of your server setting, such as file-max or max_map_count(cat /proc/sys/vm/max_map_count), and check your runbroker.sh JVM config.
and if your have no idea about this, you can search these words:  "FileChannelImpl 
 java.lang.OutOfMemoryError: Map failed  " in google.

**Comment by reachfish** [comment]
@duhengforever  max_map_count is 65530 on my server.  there are total 6.5w+ mappfile in dir commit log + consume queue.  so maybe it's the answer !!  

i had set mapedFileSizeConsumeQueue=300000 in the broker config, which result in 6.5w+ consume queue mapfiles.   i will set this value bigger and retry again.

thank you so much ~~~

**Comment by vongosling** [comment]
I would like to appreciate your @reachfish engagement in the community if you could raise your question in the user email list. Issue is not the correct place for your request, please read the issue template, looking forward to your question in the email list :-)
