### ISSUE TITLE
BROADCASTING mode in windows, create rocketmq_offsets file failed

### ISSUE THREAD

**Issue by yanghaifeng5461** [apache/rocketmq#4872]
BROADCASTING mode in windows, create rocketmq_offsets file failed.
It’s not allowed to write ‘:’ characters when creating folders under windows

error log:
java.io.FileNotFoundException: 
C:\Users\.rocketmq_offsets\IP:9876@testConsumer\testConsumer\offsets.json.tmp
at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at java.io.FileWriter.<init>(FileWriter.java:90)
	at org.apache.rocketmq.common.MixAll.string2FileNotSafe(MixAll.java:166)
	at org.apache.rocketmq.common.MixAll.string2File(MixAll.java:142)
	at org.apache.rocketmq.client.consumer.store.LocalFileOffsetStore.persistAll(LocalFileOffsetStore.java:147)
	at org.apache.rocketmq.client.impl.consumer.DefaultMQPushConsumerImpl.persistConsumerOffset(DefaultMQPushConsumerImpl.java:1024)
	at org.apache.rocketmq.client.impl.consumer.DefaultMQPushConsumerImpl.shutdown(DefaultMQPushConsumerImpl.java:560)
	at org.apache.rocketmq.client.consumer.DefaultMQPushConsumer.shutdown(DefaultMQPushConsumer.java:721)
	at org.apache.rocketmq.spring.support.DefaultRocketMQListenerContainer.stop(DefaultRocketMQListenerContainer.java:297)
	at org.apache.rocketmq.spring.support.DefaultRocketMQListenerContainer.stop(DefaultRocketMQListenerContainer.java:273)
	at org.springframework.context.support.DefaultLifecycleProcessor.doStop(DefaultLifecycleProcessor.java:234)
	at org.springframework.context.support.DefaultLifecycleProcessor.access$300(DefaultLifecycleProcessor.java:54)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.stop(DefaultLifecycleProcessor.java:373)
	at org.springframework.context.support.DefaultLifecycleProcessor.stopBeans(DefaultLifecycleProcessor.java:206)
	at org.springframework.context.support.DefaultLifecycleProcessor.onClose(DefaultLifecycleProcessor.java:129)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1067)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.doClose(ServletWebServerApplicationContext.java:172)
	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:1021)
	at org.springframework.boot.SpringApplicationShutdownHook.closeAndWait(SpringApplicationShutdownHook.java:137)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.springframework.boot.SpringApplicationShutdownHook.run(SpringApplicationShutdownHook.java:106)
	at java.lang.Thread.run(Thread.java:748)

**Comment by YangJodie** [comment]
If you need reliable continuation consumption when restart, please use cluster mode.

**Comment by yanghaifeng5461** [comment]
thank u
