### ISSUE TITLE
FlakyTest:OffsetNotFoundIT

### ISSUE THREAD

**Issue by lizhanhui** [apache/rocketmq#4971]
1) testConsumeStopAndResume(org.apache.rocketmq.test.offset.OffsetNotFoundIT)
java.lang.AssertionError: expected:<10> but was:<0>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at org.apache.rocketmq.test.offset.OffsetNotFoundIT.testConsumeStopAndResume(OffsetNotFoundIT.java:100)

FAILURES!!!
Tests run: 2,  Failures: 1

**Comment by complone** [comment]
looks interesting i want to try

**Comment by complone** [comment]
This problem is because rpcHook delays triggering when the consumer calls waitForMessageConsume. Maybe we should use a semaphore or countDownlatch to control the listener callback.

**Comment by lizhanhui** [comment]
@complone Welcome to submit a patch to fix it.

**Comment by complone** [comment]
> @complone欢迎提交补丁来修复它。

@lizhanhui  I'm trying, maybe it's taking a long time
