### ISSUE TITLE
 ERROR AcceptSocketService service has exception. java.io.IOException

### ISSUE THREAD

**Issue by Liberxue** [apache/rocketmq#506]
The issue tracker is **ONLY** used for bug report and feature request. Keep in mind, please check whether there is an existing same report before your raise a new one.

Alternately (especially if your communication is not a bug report), you can send mail to our [mailing lists](http://rocketmq.apache.org/about/contact/). We welcome any friendly suggestions, bug fixes, collaboration and other improvements.

Please ensure that your bug report is clear and that it is complete. Otherwise, we may be unable to understand it or to reproduce it, either of which would prevent us from fixing the bug. We strongly recommend the report(bug report or feature request) could include some hints as the following:

**BUG REPORT**

1. Please describe the issue you observed:
#### store.log
```shell
2018-10-30 15:52:23 ERROR AcceptSocketService - AcceptSocketService service has exception.
java.io.IOException: Too many open files
	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method) ~[na:1.8.0_181]
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422) ~[na:1.8.0_181]
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250) ~[na:1.8.0_181]
	at org.apache.rocketmq.store.ha.HAService$AcceptSocketService.run(HAService.java:211) ~[rocketmq-store-4.3.0.jar:4.3.0]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
2018-10-30 15:52:23 ERROR AcceptSocketService - AcceptSocketService service has exception.
java.io.IOException: Too many open files
	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method) ~[na:1.8.0_181]
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422) ~[na:1.8.0_181]
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250) ~[na:1.8.0_181]
	at org.apache.rocketmq.store.ha.HAService$AcceptSocketService.run(HAService.java:211) ~[rocketmq-store-4.3.0.jar:4.3.0]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
2018-10-30 15:52:23 ERROR AcceptSocketService - AcceptSocketService service has exception.
java.io.IOException: Too many open files
	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method) ~[na:1.8.0_181]
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422) ~[na:1.8.0_181]
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250) ~[na:1.8.0_181]
	at org.apache.rocketmq.store.ha.HAService$AcceptSocketService.run(HAService.java:211) ~[rocketmq-store-4.3.0.jar:4.3.0]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
2018-10-30 15:52:23 ERROR AcceptSocketService - AcceptSocketService service has exception.
java.io.IOException: Too many open files
	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method) ~[na:1.8.0_181]
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422) ~[na:1.8.0_181]
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250) ~[na:1.8.0_181]
	at org.apache.rocketmq.store.ha.HAService$AcceptSocketService.run(HAService.java:211) ~[rocketmq-store-4.3.0.jar:4.3.0]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
2018-10-30 15:52:23 ERROR AcceptSocketService - AcceptSocketService service has exception.
java.io.IOException: Too many open files
	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method) ~[na:1.8.0_181]
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422) ~[na:1.8.0_181]
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250) ~[na:1.8.0_181]
	at org.apache.rocketmq.store.ha.HAService$AcceptSocketService.run(HAService.java:211) ~[rocketmq-store-4.3.0.jar:4.3.0]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
2018-10-30 15:52:23 ERROR AcceptSocketService - AcceptSocketService service has exception.
java.io.IOException: Too many open files
	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method) ~[na:1.8.0_181]
```
#### remoting.log
```
2018-10-30 16:11:35 WARN AcceptSocketService - Open ePoll Selector for linux platform exception
java.io.IOException: Too many open files
	at sun.nio.ch.IOUtil.makePipe(Native Method) ~[na:1.8.0_181]
	at sun.nio.ch.EPollSelectorImpl.<init>(EPollSelectorImpl.java:65) ~[na:1.8.0_181]
	at sun.nio.ch.EPollSelectorProvider.openSelector(EPollSelectorProvider.java:36) ~[na:1.8.0_181]
	at org.apache.rocketmq.remoting.common.RemotingUtil.openSelector(RemotingUtil.java:71) ~[rocketmq-remoting-4.3.0.jar:4.3.0]
	at org.apache.rocketmq.store.ha.HAConnection$WriteSocketService.<init>(HAConnection.java:205) [rocketmq-store-4.3.0.jar:4.3.0]
	at org.apache.rocketmq.store.ha.HAConnection.<init>(HAConnection.java:51) [rocketmq-store-4.3.0.jar:4.3.0]
	at org.apache.rocketmq.store.ha.HAService$AcceptSocketService.run(HAService.java:218) [rocketmq-store-4.3.0.jar:4.3.0]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
```
##### broker.log
```shell 
2018-10-30 14:45:17 ERROR BrokerControllerScheduledThread1 - persist file /opt/mq430/store/config/consumerOffset.json exception
java.io.FileNotFoundException: /opt/mq430/store/config/consumerOffset.json.tmp (Too many open files)
	at java.io.FileOutputStream.open0(Native Method) ~[na:1.8.0_181]
	at java.io.FileOutputStream.open(FileOutputStream.java:270) ~[na:1.8.0_181]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213) ~[na:1.8.0_181]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162) ~[na:1.8.0_181]
	at java.io.FileWriter.<init>(FileWriter.java:90) ~[na:1.8.0_181]
	at org.apache.rocketmq.common.MixAll.string2FileNotSafe(MixAll.java:172) ~[rocketmq-common-4.3.0.jar:4.3.0]
	at org.apache.rocketmq.common.MixAll.string2File(MixAll.java:148) ~[rocketmq-common-4.3.0.jar:4.3.0]
	at org.apache.rocketmq.common.ConfigManager.persist(ConfigManager.java:75) ~[rocketmq-common-4.3.0.jar:4.3.0]
	at org.apache.rocketmq.broker.BrokerController$2.run(BrokerController.java:318) [rocketmq-broker-4.3.0.jar:4.3.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_181]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_181]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_181]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
```

- What did you do (The steps to reproduce)?

```shell
sh benchmark/producer.sh -n "x" - w 1020
```

- What did you expect to see?

- What did you see instead?

2. Please tell us about your environment:
```shell
gcc version 4.9.2 20150212 (Red Hat 4.9.2-6
```
```shell
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
```
3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by duhengforever** [comment]
@Liberxue  it
 seems that you opened  too many files in your server, and you can change the ulimit setting of your operation system.

**Comment by Liberxue** [comment]
@duhengforever  Yes, seeing the error is a ulimit problem, but the strange thing is that I only used 1024....😅
