### ISSUE TITLE
AutoSwitchRoleIntegrationTest not stable

### ISSUE THREAD

**Issue by lizhanhui** [apache/rocketmq#5113]
Running org.apache.rocketmq.test.autoswitchrole.AutoSwitchRoleIntegrationTest
01:41:15,065 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback-test.xml] at [file:/home/runner/work/rocketmq/rocketmq/test/target/test-classes/logback-test.xml]
01:41:15,147 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
01:41:15,148 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
01:41:15,163 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [DefaultAppender]
01:41:15,176 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@22:17 - no applicable action for [append], current ElementPath  is [[configuration][appender][append]]
01:41:15,180 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
01:41:15,234 |-INFO in ch.qos.logback.classic.joran.action.LevelAction - ROOT level set to ERROR
01:41:15,234 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [DefaultAppender] to Logger[ROOT]
01:41:15,235 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
01:41:15,236 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@5e840abf - Registering current configuration as safe fallback point

2022-09-19 09:41:17 ERROR main - Failed to register broker to controller
org.apache.rocketmq.client.exception.MQBrokerException: CODE: 2007  DESC: Controller leader was changed
For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
	at org.apache.rocketmq.broker.out.BrokerOuterAPI.registerBrokerToController(BrokerOuterAPI.java:1152)
	at org.apache.rocketmq.broker.controller.ReplicasManager.registerBrokerToController(ReplicasManager.java:293)
	at org.apache.rocketmq.broker.controller.ReplicasManager.startBasicService(ReplicasManager.java:142)
	at org.apache.rocketmq.broker.controller.ReplicasManager.start(ReplicasManager.java:111)
	at org.apache.rocketmq.broker.BrokerController.startBasicService(BrokerController.java:1427)
	at org.apache.rocketmq.broker.BrokerController.start(BrokerController.java:1521)
	at org.apache.rocketmq.test.autoswitchrole.AutoSwitchRoleBase.startBroker(AutoSwitchRoleBase.java:120)
	at org.apache.rocketmq.test.autoswitchrole.AutoSwitchRoleIntegrationTest.init(AutoSwitchRoleIntegrationTest.java:90)
	at org.apache.rocketmq.test.autoswitchrole.AutoSwitchRoleIntegrationTest.testAddBroker(AutoSwitchRoleIntegrationTest.java:181)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
2022-09-19 09:41:17 ERROR main - Failed to start replicasManager
Tests run: 2, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 3.923 sec <<< FAILURE! - in org.apache.rocketmq.test.autoswitchrole.AutoSwitchRoleIntegrationTest
testAddBroker(org.apache.rocketmq.test.autoswitchrole.AutoSwitchRoleIntegrationTest)  Time elapsed: 3.812 sec  <<< FAILURE!
java.lang.AssertionError
	at org.apache.rocketmq.test.autoswitchrole.AutoSwitchRoleIntegrationTest.init(AutoSwitchRoleIntegrationTest.java:90)
	at org.apache.rocketmq.test.autoswitchrole.AutoSwitchRoleIntegrationTest.testAddBroker(AutoSwitchRoleIntegrationTest.java:181)

Running org.apache.rocketmq.test.lmq.TestBenchLmqStore
Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0 sec - in org.apache.rocketmq.test.lmq.TestBenchLmqStore
Running org.apache.rocketmq.test.schema.SchemaTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.001 sec - in org.apache.rocketmq.test.schema.SchemaTest

Results :

Failed tests: 
  AutoSwitchRoleIntegrationTest.testAddBroker:181->init:90->AutoSwitchRoleBase.startBroker:125

**Comment by complone** [comment]
Hello, flaky-tests like this have appeared in previous issues. I would like to ask if it is a case of frequent failures, and I would like to know if it is because of the impact after my last fix
