### ISSUE TITLE
AutoSwitchRoleIntegrationTest is flaky

### ISSUE THREAD

**Issue by lizhanhui** [apache/rocketmq#5203]
Tests run: 4, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 98.747 sec <<< FAILURE! - in org.apache.rocketmq.test.autoswitchrole.AutoSwitchRoleIntegrationTest
testTruncateEpochLogAndChangeMaster(org.apache.rocketmq.test.autoswitchrole.AutoSwitchRoleIntegrationTest)  Time elapsed: 7.408 sec  <<< FAILURE!
java.lang.AssertionError: expected:<FOUND> but was:<OFFSET_OVERFLOW_ONE>
	at org.apache.rocketmq.test.autoswitchrole.AutoSwitchRoleIntegrationTest.testTruncateEpochLogAndChangeMaster(AutoSwitchRoleIntegrationTest.java:203)

2022-09-28 12:21:48 ERROR pool-1-thread-1 - 
java.lang.NullPointerException: null
	at org.apache.rocketmq.test.lmq.benchmark.BenchLmqStore.lambda$doSend$1(BenchLmqStore.java:176)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by azhsmesos** [comment]
> 
This problem which i haven’t found
