### ISSUE TITLE
No route info of this topic 异常， 偶发

### ISSUE THREAD

**Issue by hezhijie** [apache/rocketmq#5252]
client version 4.6.0
server version 4.5.0

应用环境： 同一个docker镜像部署了多个pod ，同一个局域网，同样的环境变量
重启应用时 总是出现其中一个到多个pod出现 "No route info of this topic" 异常， 偶发
以下为部分报错信息

2022-10-09 07:30:55.573 [epollEventLoopGroup-11-2] ERROR org.apache.rocketmq.spring.core.RocketMQTemplate [RocketMQTemplate.java:533] [98ecbf9a] [U086235729292970610] - syncSend failed. destination:xxtopic:xxTag message:GenericMessage [payload=RocketMqMessage(content=xxxx, msgKey=xxx, producerTopic=xxtopic, producerGroup=null, producerTag=xxtag), headers={KEYS=xxx, id=8878d19b-c773-20cb-4e82-xxx, timestamp=1665286255570}] 
2022-10-09 07:30:55.574 [epollEventLoopGroup-11-2] ERROR xxx.rocketmq.RocketMqService [RocketMqService.java:56] [98ecbf9a] [U086235729292970610] - destination:xxtopic:xxTag
org.springframework.messaging.MessagingException: No route info of this topic: xxtopic
See http://rocketmq.apache.org/docs/faq/ for further details.; nested exception is org.apache.rocketmq.client.exception.MQClientException: No route info of this topic: xxtopic
See http://rocketmq.apache.org/docs/faq/ for further details.
        at org.apache.rocketmq.spring.core.RocketMQTemplate.syncSend(RocketMQTemplate.java:534)
        at org.apache.rocketmq.spring.core.RocketMQTemplate.syncSend(RocketMQTemplate.java:466)
        at org.apache.rocketmq.spring.core.RocketMQTemplate.syncSend(RocketMQTemplate.java:454)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at xxxxchannelRead(xxxx.java:154)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:108)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:328)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:302)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1421)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:794)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:424)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:326)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.rocketmq.client.exception.MQClientException: No route info of this topic: xxTopic
See http://rocketmq.apache.org/docs/faq/ for further details.
        at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendDefaultImpl(DefaultMQProducerImpl.java:684)
        at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1342)
        at org.apache.rocketmq.client.producer.DefaultMQProducer.send(DefaultMQProducer.java:343)
        at org.apache.rocketmq.spring.core.RocketMQTemplate.syncSend(RocketMQTemplate.java:526)
        ... 42 common frames omitted

**Comment by duhenglucky** [comment]
有几个nameserver？ 建议通过topicroute 命令查看对应topic在不同nameserver 上的路由信息是否一致，执行该命令时分别-n 指定不同nameserver 就可以了

**Comment by hezhijie** [comment]
> 

多谢提醒，确实是有人近期增加了一台nameserver, 有没有broker不重启，动态修改nameserver地址的方式呢

**Comment by duhenglucky** [comment]
> 

不客气，最新的版本已经增加了动态修改nameserver 的能力了，4.9.4 LTS 版本
