### ISSUE TITLE
Unable to register with namesever when topic quantity is 6w 

### ISSUE THREAD

**Issue by Cczzzz** [apache/rocketmq#5296]
Because the request body is too large

nameserver error 

2022-10-12 19:37:44 ERROR NettyServerCodecThread_5 - decode exception, 10.110.124.125:39326
io.netty.handler.codec.TooLongFrameException: Adjusted frame length exceeds 16777216: 16777397 - discarded
        at io.netty.handler.codec.LengthFieldBasedFrameDecoder.fail(LengthFieldBasedFrameDecoder.java:503) ~[netty-all-4.1.65.Final.jar:4.1.65.Final]
        at io.netty.handler.codec.LengthFieldBasedFrameDecoder.failIfNecessary(LengthFieldBasedFrameDecoder.java:489) ~[netty-all-4.1.65.Final.jar:4.1.65.Final]
        at io.netty.handler.codec.LengthFieldBasedFrameDecoder.exceededFrameLength(LengthFieldBasedFrameDecoder.java:376) ~[netty-all-4.1.65.Final.jar:4.1.65.Final]
        at io.netty.handler.codec.LengthFieldBasedFrameDecoder.decode(LengthFieldBasedFrameDecoder.java:419) ~[netty-all-4.1.65.Final.jar:4.1.65.Final]
        at org.apache.rocketmq.remoting.netty.NettyDecoder.decode(NettyDecoder.java:43) ~[rocketmq-remoting-4.9.1.jar:4.9.1]
        at io.netty.handler.codec.LengthFieldBasedFrameDecoder.decode(LengthFieldBasedFrameDecoder.java:332) ~[netty-all-4.1.65.Final.jar:4.1.65.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507) ~[netty-all-4.1.65.Final.jar:4.1.65.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446) ~[netty-all-4.1.65.Final.jar:4.1.65.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[netty-all-4.1.65.Final.jar:4.1.65.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-all-4.1.65.Final.jar:4.1.65.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-all-4.1.65.Final.jar:4.1.65.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-all-4.1.65.Final.jar:4.1.65.Final]
        at org.apache.rocketmq.remoting.netty.NettyRemotingServer$HandshakeHandler.channelRead0(NettyRemotingServer.java:411) ~[rocketmq-remoting-4.9.1.jar:4.9.1]
        at org.apache.rocketmq.remoting.netty.NettyRemotingServer$HandshakeHandler.channelRead0(NettyRemotingServer.java:352) ~[rocketmq-remoting-4.9.1.jar:4.9.1]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[netty-all-4.1.65.Final.jar:4.1.65.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-all-4.1.65.Final.jar:4.1.65.Final]
        at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:61) ~[netty-all-4.1.65.Final.jar:4.1.65.Final]
        at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:370) ~[netty-all-4.1.65.Final.jar:4.1.65.Final]
        at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66) ~[netty-all-4.1.65.Final.jar:4.1.65.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-all-4.1.65.Final.jar:4.1.65.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-all-4.1.65.Final.jar:4.1.65.Final]
        at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

**Comment by Cczzzz** [comment]
Will be restored after deleting some topics

**Comment by lizhimins** [comment]
The serialized topic config length will exceed the netty frame length limit when broker has too much topic.
u can delete unused retry q and dead letter q from the broker to reduce the content length.

Periodic registration with ns consumes a lot of resources and traffic.
It's time to discuss how to optimize the service discovery in broker and nameserver

**Comment by Stupid-Dird** [comment]
@lizhimins If the theme cannot be reduced,You can try to add System.setProperty("com.rocketmq.remoting.frameMaxLength", String.valueOf(Integer.MAX_VALUE)) to main method.

**Comment by Stupid-Dird** [comment]
@Cczzzz If the theme cannot be reduced,You can try to add System.setProperty("com.rocketmq.remoting.frameMaxLength", String.valueOf(Integer.MAX_VALUE)) to main method.

**Comment by zhouxinyu** [comment]
> @Cczzzz If the theme cannot be reduced,You can try to add System.setProperty("com.rocketmq.remoting.frameMaxLength", String.valueOf(Integer.MAX_VALUE)) to main method.

Right partially, setting this property could resolve this issue, but please note:
1. Use -D to set this property rather than using hard code.
2. Don't set a too large value, limit this value on demand to avoid potential security issues.

**Comment by Stupid-Dird** [comment]
> > @Cczzzz If the theme cannot be reduced,You can try to add System.setProperty("com.rocketmq.remoting.frameMaxLength", String.valueOf(Integer.MAX_VALUE)) to main method.
> 
> Right partially, setting this property could resolve this issue, but please note:
> 
> 1. Use -D to set this property rather than using hard code.
> 2. Don't set a too large value, limit this value on demand to avoid potential security issues.

Your is right,This right use way.

**Comment by Stupid-Dird** [comment]
> > @Cczzzz If the theme cannot be reduced,You can try to add System.setProperty("com.rocketmq.remoting.frameMaxLength", String.valueOf(Integer.MAX_VALUE)) to main method.
> 
> Right partially, setting this property could resolve this issue, but please note:
> 
> 1. Use -D to set this property rather than using hard code.
> 2. Don't set a too large value, limit this value on demand to avoid potential security issues.

You're right,the above methods are better.

**Comment by zhouxinyu** [comment]
Feel free to reopen this issue if you have further questions. @Cczzzz
