### ISSUE TITLE
NormalMsgDelayIT is flaky

### ISSUE THREAD

**Issue by lizhanhui** [apache/rocketmq#5309]
There was 1 failure:
1) testDelayLevel3(org.apache.rocketmq.test.delay.NormalMsgDelayIT)
java.lang.AssertionError: Timer is not correct expected:<true> but was:<false>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:120)
	at org.apache.rocketmq.test.delay.NormalMsgDelayIT.testDelayLevel3(NormalMsgDelayIT.java:96)

See full CI log: https://github.com/apache/rocketmq/actions/runs/3235189115/jobs/5299272721

**Comment by ShadowySpirits** [comment]
Please assign it to me.
