### ISSUE TITLE
The dashboard1.0.0 cannot connect to the 5.0.0 nameserver

### ISSUE THREAD

**Issue by Oliverwqcwrw** [apache/rocketmq#5384]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?

Failed to access dashborad after starting nameserver and broker

- What is expected to see?

No error is reported when you access the dashboard

- What did you see instead?

> 

      java.lang.NoClassDefFoundError: Could not initialize class io.netty.util.internal.PlatformDependent0
	at io.netty.util.internal.PlatformDependent.getSystemClassLoader(PlatformDependent.java:694)
	at io.netty.channel.nio.NioEventLoop$4.run(NioEventLoop.java:171)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:167)
	at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:149)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:102)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:64)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:49)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:70)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:65)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:56)
	at org.apache.rocketmq.remoting.netty.NettyRemotingClient.<init>(NettyRemotingClient.java:122)
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.<init>(MQClientAPIImpl.java:188)
	at org.apache.rocketmq.client.impl.factory.MQClientInstance.<init>(MQClientInstance.java:133)
	at org.apache.rocketmq.client.impl.MQClientManager.getOrCreateMQClientInstance(MQClientManager.java:53)
	at org.apache.rocketmq.tools.admin.DefaultMQAdminExtImpl.start(DefaultMQAdminExtImpl.java:120)
	at org.apache.rocketmq.tools.admin.DefaultMQAdminExt.start(DefaultMQAdminExt.java:145)
	at org.apache.rocketmq.dashboard.admin.MQAdminFactory.getInstance(MQAdminFactory.java:53)
	at org.apache.rocketmq.dashboard.admin.MQAdminPooledObjectFactory.makeObject(MQAdminPooledObjectFactory.java:35)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:888)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:432)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:361)
	at org.apache.rocketmq.dashboard.service.client.MQAdminInstance.createMQAdmin(MQAdminInstance.java:56)
	at org.apache.rocketmq.dashboard.aspect.admin.MQAdminAspect.aroundMQAdminMethod(MQAdminAspect.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at org.apache.rocketmq.dashboard.service.client.MQAdminExtImpl$$EnhancerBySpringCGLIB$$24e3b91d.fetchAllTopicList(<generated>)
	at org.apache.rocketmq.dashboard.task.DashboardCollectTask.collectTopic(DashboardCollectTask.java:79)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
[2022-10-24 09:34:00.027] ERROR Unexpected error occurred in scheduled task
java.lang.NoClassDefFoundError: Could not initialize class io.netty.util.internal.PlatformDependent0
	at io.netty.util.internal.PlatformDependent.getSystemClassLoader(PlatformDependent.java:694)
	at io.netty.channel.nio.NioEventLoop$4.run(NioEventLoop.java:171)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:167)
	at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:149)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:102)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:64)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:49)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:70)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:65)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:56)
	at org.apache.rocketmq.remoting.netty.NettyRemotingClient.<init>(NettyRemotingClient.java:122)
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.<init>(MQClientAPIImpl.java:188)

2. Please tell us about your environment:

nameserver 5.0.0
broker 5.0.0
dashboard 1.0.0

4. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):

The latest master code can connect to 5.0.0 nameserver normally. Can we release a new version so that users can download the latest dashboard version and access 5.0.0

**Comment by RongtongJin** [comment]
`java.lang.NoClassDefFoundError: Could not initialize class io.netty.util.internal.PlatformDependent0`
The error seems to have nothing to do with connecting to RocketMQ 5.0 nameserver.

**Comment by Oliverwqcwrw** [comment]
Hello @RongtongJin ,Thx for your reply

What I said before was a little inaccurate, not when I was connecting to nameserver, but when I was checking information. For example, cluster information, consumer information and so on

<img width="1286" alt="image" src="https://user-images.githubusercontent.com/31796988/197654680-5e930e46-e177-4aa0-9f6c-3ab0dee1bd8b.png">


<img width="1328" alt="image" src="https://user-images.githubusercontent.com/31796988/197654378-7dceb96c-66ca-4e69-bc5b-4af424accb07.png">

**Comment by xiaoyifang** [comment]
https://github.com/netty/netty/issues/12737
