### ISSUE TITLE
An SubscriptionGroup that has been deleted leads to a pile of messages 

### ISSUE THREAD

**Issue by ccctask** [apache/rocketmq#5400]
##  Rocketmq Version
V4_5_0

### topic  status 
```bash
bash-4.4# ./mqadmin statsAll -n 10.10.110.154:9876 10.10.120.98:9876  -t sms-engine-whevt-push-sms
OpenJDK 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0
#Topic                            #Consumer Group                  #Accumulation      #InTPS     #OutTPS   #InMsg24Hour  #OutMsg24Hour
sms-engine-whevt-push-sms         sms-engine-whevt-push-sms-yunpian         1674        0.00        0.00             19              0
sms-engine-whevt-push-sms         sms-engine-whevt-push-sms                   0        0.00        0.00             19             19
```

> I already deleted the   SubGroup  sms-engine-whevt-push-sms-yunpian 

![image](https://user-images.githubusercontent.com/33889129/197716005-7730ec7c-a102-462a-b512-d8820e4dcae6.png)

### consumerStatus
```bash
bash-4.4# ./mqadmin consumerStatus -n 10.10.110.154:9876 10.10.120.98:9876  -g sms-engine-whevt-push-sms-yunpian
OpenJDK 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0
org.apache.rocketmq.tools.command.SubCommandException: ConsumerStatusSubCommand command failed
	at org.apache.rocketmq.tools.command.consumer.ConsumerStatusSubCommand.execute(ConsumerStatusSubCommand.java:134)
	at org.apache.rocketmq.tools.command.MQAdminStartup.main0(MQAdminStartup.java:135)
	at org.apache.rocketmq.tools.command.MQAdminStartup.main(MQAdminStartup.java:86)
Caused by: org.apache.rocketmq.client.exception.MQBrokerException: CODE: 206  DESC: the consumer group[sms-engine-whevt-push-sms-yunpian] not online
For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.getConsumerConnectionList(MQClientAPIImpl.java:1113)
	at org.apache.rocketmq.tools.admin.DefaultMQAdminExtImpl.examineConsumerConnectionInfo(DefaultMQAdminExtImpl.java:308)
	at org.apache.rocketmq.tools.admin.DefaultMQAdminExt.examineConsumerConnectionInfo(DefaultMQAdminExt.java:235)
	at org.apache.rocketmq.tools.command.consumer.ConsumerStatusSubCommand.execute(ConsumerStatusSubCommand.java:79)
	... 2 more
```

how can i delete  group sms-engine-whevt-push-sms-yunpian  form topic sms-engine-whevt-push-sms

**Comment by codersfarm** [comment]
The master's node maybe more than 1, and you only delete 1 in your cluster.

**Comment by ccctask** [comment]
when i delete the  SubGroup , cluster repot that  i have delete  SubGroup from all the master node 

```bash
bash-4.4# ./mqadmin deleteSubGroup -n 10.10.110.154:9876 10.10.120.98:9876 -c broker -g sms-engine-whevt-push-sms
OpenJDK 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0
delete subscription group [sms-engine-whevt-push-sms] from broker [10.10.120.102:10911] in cluster [broker] success.
delete subscription group [sms-engine-whevt-push-sms] from broker [10.10.120.106:10911] in cluster [broker] success.
delete subscription group [sms-engine-whevt-push-sms] from broker [10.10.120.99:10911] in cluster [broker] success.
delete topic [%RETRY%sms-engine-whevt-push-sms] from cluster [broker] success.
delete topic [%RETRY%sms-engine-whevt-push-sms] from NameServer success.
delete topic [%DLQ%sms-engine-whevt-push-sms] from cluster [broker] success.
delete topic [%DLQ%sms-engine-whevt-push-sms] from NameServer success.
```

**Comment by ShadowySpirits** [comment]
@ccctask You can try to add `-r true` to deleteSubGroup command. In this way, broker will clean the offset table.
