### ISSUE TITLE
Rpc hook npe in rocketmq test

### ISSUE THREAD

**Issue by lizhimins** [apache/rocketmq#5443]
Rpc hook npe in rocketmq test

![image](https://user-images.githubusercontent.com/22487634/199187735-10af7881-2d22-46ec-8d83-12f3285d1e64.png)

2022-11-01 16:03:21 ERROR main - Error occurred when looking for resource file META-INF/service/org.apache.rocketmq.remoting.RPCHook
java.lang.NullPointerException: null
	at java.io.Reader.<init>(Reader.java:78)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:113)
	at org.apache.rocketmq.common.utils.ServiceProvider.load(ServiceProvider.java:111)
	at org.apache.rocketmq.broker.BrokerController.initialRpcHooks(BrokerController.java:956)
	at org.apache.rocketmq.broker.BrokerController.initialize(BrokerController.java:803)
	at org.apache.rocketmq.test.base.IntegrationTestBase.createAndStartBroker(IntegrationTestBase.java:155)
	at org.apache.rocketmq.test.base.IntegrationTestBase.createAndStartBroker(IntegrationTestBase.java:145)
        ...

**Comment by RongtongJin** [comment]
Hi @lizhimins, this does not affect loading, but such error logs do mislead users. I have submitted a PR to fix this issue, PTAL~
