### ISSUE TITLE
Can I switch back to the master-slave cluster from the DLeger cluster mode？

### ISSUE THREAD

**Issue by ahcjz** [apache/rocketmq#5469]
Deleger集群时长出现重新选主，导致集群不可写。是否可以从Deleger集群模式切换回Master-Slave集群？切换后，历史数据是否有影响？版本4.8.0

**Comment by zhouxinyu** [comment]
具体耗费了多少时间进行选主？有排查到原因吗？

**Comment by ahcjz** [comment]
> 具体耗费了多少时间进行选主？有排查到原因吗？

从日志看原因是broker之间3次心跳超时，看源码是不可以设置心跳超时时间的是么？

**Comment by RongtongJin** [comment]
> Deleger集群时长出现重新选主，导致集群不可写。是否可以从Deleger集群模式切换回Master-Slave集群？切换后，历史数据是否有影响？版本4.8.0

没有办法切换回去，因为数据格式有变化。如果有多组Broker，可以考虑滚动禁写下线清空数据重新上线来切回去。
是否有相关的日志排查一下原因

**Comment by ahcjz** [comment]
> > Deleger集群时长出现重新选主，导致集群不可写。是否可以从Deleger集群模式切换回Master-Slave集群？切换后，历史数据是否有影响？版本4.8.0
> 
> 没有办法切换回去，因为数据格式有变化。如果有多组Broker，可以考虑滚动禁写下线清空数据重新上线来切回去。 是否有相关的日志排查一下原因

2022-11-05 21:29:46 INFO QuorumAckChecker-n0 - [n0][FOLLOWER] term=115 ledgerBegin=561124490 ledgerEnd=590274995 committed=590274995 watermarks={114:{"n0":578832166,"n1":578832165,"n2":578832165}}
2022-11-05 21:29:49 INFO QuorumAckChecker-n0 - [n0][FOLLOWER] term=115 ledgerBegin=561124490 ledgerEnd=590274995 committed=590274995 watermarks={114:{"n0":578832166,"n1":578832165,"n2":578832165}}
2022-11-05 21:29:51 INFO StateMaintainer - [n0][HeartBeatTimeOut] lastLeaderHeartBeatTime: 2022-11-05 21:29:45.416 heartBeatTimeIntervalMs: 2000 lastLeader=n1
2022-11-05 21:29:51 INFO StateMaintainer - [n0] [ChangeRoleToCandidate] from term: 115 and currTerm: 115
2022-11-05 21:29:51 INFO StateMaintainer - n0_[INCREASE_TERM] from 115 to 116
2022-11-05 21:29:51 INFO StateMaintainer - [n0][GetVoteResponse] {"code":200,"group":"RaftNode00","leaderId":"n0","remoteId":"n0","term":116,"voteResult":"ACCEPT"}
2022-11-05 21:29:51 INFO NettyClientPublicExecutor_2 - [n0][GetVoteResponse] {"code":200,"group":"RaftNode00","leaderId":"n0","remoteId":"n2","term":116,"voteResult":"REJECT_ALREADY_VOTED"}
2022-11-05 21:29:52 INFO QuorumAckChecker-n0 - [n0][CANDIDATE] term=116 ledgerBegin=561124490 ledgerEnd=590274995 committed=590274995 watermarks={114:{"n0":578832166,"n1":578832165,"n2":578832165}}
2022-11-05 21:29:53 INFO StateMaintainer - [n0] [PARSE_VOTE_RESULT] cost=2358 term=116 memberNum=3 allNum=2 acceptedNum=1 notReadyTermNum=0 biggerLedgerNum=0 alreadyHasLeader=false maxTerm=116 result=WAIT
_TO_VOTE_NEXT
2022-11-05 21:29:54 INFO StateMaintainer - n0_[INCREASE_TERM] from 116 to 117
2022-11-05 21:29:54 INFO StateMaintainer - [n0][GetVoteResponse] {"code":200,"group":"RaftNode00","leaderId":"n0","remoteId":"n0","term":117,"voteResult":"ACCEPT"}
2022-11-05 21:29:54 INFO NettyClientPublicExecutor_8 - [n0][GetVoteResponse] {"code":200,"group":"RaftNode00","leaderId":"n0","remoteId":"n2","term":116,"voteResult":"REJECT_TERM_NOT_READY"}
2022-11-05 21:29:54 INFO StateMaintainer - [n0] [PARSE_VOTE_RESULT] cost=4 term=117 memberNum=3 allNum=2 acceptedNum=1 notReadyTermNum=1 biggerLedgerNum=0 alreadyHasLeader=false maxTerm=117 result=REVOTE_
IMMEDIATELY
2022-11-05 21:29:54 INFO StateMaintainer - [n0][GetVoteResponse] {"code":200,"group":"RaftNode00","leaderId":"n0","remoteId":"n0","term":117,"voteResult":"ACCEPT"}
2022-11-05 21:29:54 INFO NettyClientPublicExecutor_1 - [n0][GetVoteResponse] {"code":200,"group":"RaftNode00","leaderId":"n0","remoteId":"n2","term":117,"voteResult":"ACCEPT"}
2022-11-05 21:29:54 INFO StateMaintainer - [n0] [PARSE_VOTE_RESULT] cost=2 term=117 memberNum=3 allNum=2 acceptedNum=2 notReadyTermNum=0 biggerLedgerNum=0 alreadyHasLeader=false maxTerm=117 result=PASSED
2022-11-05 21:29:54 INFO StateMaintainer - [n0] [VOTE_RESULT] has been elected to be the leader in term 117
2022-11-05 21:29:54 INFO StateMaintainer - [n0] [ChangeRoleToLeader] from term: 117 and currTerm: 117
2022-11-05 21:29:54 INFO EntryDispatcher-n0-n2 - [Push-n2]Change state from APPEND to COMPARE at -1
2022-11-05 21:29:54 INFO EntryDispatcher-n0-n2 - [Push-n2][DoCompare] compareIndex=-1 means start to compare
2022-11-05 21:29:54 INFO QuorumAckChecker-n0 - Initialize the pending append map in QuorumAckChecker for term=117
2022-11-05 21:29:54 INFO QuorumAckChecker-n0 - Initialize the watermark in QuorumAckChecker for term=117
2022-11-05 21:29:54 INFO EntryDispatcher-n0-n1 - [Push-n1]Change state from APPEND to COMPARE at -1
2022-11-05 21:29:54 INFO QuorumAckChecker-n0 - [TermChange] Will clear the pending response index=578832166 for term changed from 114 to 117
2022-11-05 21:29:54 INFO EntryDispatcher-n0-n1 - [Push-n1][DoCompare] compareIndex=-1 means start to compare
2022-11-05 21:29:54 INFO QuorumAckChecker-n0 - [TermChange] Will clear the watermarks for term changed from 114 to 117
2022-11-05 21:29:54 INFO EntryDispatcher-n0-n2 - [Push-n2]Change state from COMPARE to APPEND at 590274995
2022-11-05 21:29:55 INFO QuorumAckChecker-n0 - [n0][LEADER] term=117 ledgerBegin=561124490 ledgerEnd=590274995 committed=590274995 watermarks={117:{"n0":590274995,"n1":-1,"n2":590274995}}
2022-11-05 21:29:56 ERROR NettyClientPublicExecutor_4 - Vote request time out, info[group=RaftNode00,term=116,code=200,local=null,remote=n1,leader=n0]
2022-11-05 21:29:56 INFO NettyClientPublicExecutor_4 - [n0][GetVoteResponse] {"code":200,"term":-1,"voteResult":"UNKNOWN"}
2022-11-05 21:29:57 ERROR EntryDispatcher-n0-n1 - [Push-n1]Error in EntryDispatcher-n0-n1 writeIndex=578832166 compareIndex=590274995
java.util.concurrent.TimeoutException: null
        at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1784) ~[na:1.8.0_311]
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928) ~[na:1.8.0_311]
        at io.openmessaging.storage.dledger.DLedgerEntryPusher$EntryDispatcher.doCompare(DLedgerEntryPusher.java:663) ~[dledger-0.2.2.jar:na]
        at io.openmessaging.storage.dledger.DLedgerEntryPusher$EntryDispatcher.doWork(DLedgerEntryPusher.java:740) ~[dledger-0.2.2.jar:na]
        at io.openmessaging.storage.dledger.ShutdownAbleThread.run(ShutdownAbleThread.java:86) [dledger-0.2.2.jar:na]
2022-11-05 21:29:58 INFO QuorumAckChecker-n0 - [n0][LEADER] term=117 ledgerBegin=561124490 ledgerEnd=590274995 committed=590274995 watermarks={117:{"n0":590274995,"n1":-1,"n2":590274995}}
2022-11-05 21:29:59 ERROR NettyClientPublicExecutor_6 - Vote request time out, info[group=RaftNode00,term=117,code=200,local=null,remote=n1,leader=n0]
2022-11-05 21:29:59 ERROR NettyClientPublicExecutor_4 - Vote request time out, info[group=RaftNode00,term=117,code=200,local=null,remote=n1,leader=n0]
2022-11-05 21:29:59 INFO NettyClientPublicExecutor_6 - [n0][GetVoteResponse] {"code":200,"term":-1,"voteResult":"UNKNOWN"}
2022-11-05 21:29:59 ERROR NettyClientPublicExecutor_3 - HeartBeat request time out, info[group=RaftNode00,term=117,code=200,local=n0,remote=n1,leader=n0]
2022-11-05 21:29:59 INFO NettyClientPublicExecutor_4 - [n0][GetVoteResponse] {"code":200,"term":-1,"voteResult":"UNKNOWN"}
2022-11-05 21:30:00 ERROR EntryDispatcher-n0-n1 - [Push-n1]Error in EntryDispatcher-n0-n1 writeIndex=578832166 compareIndex=590274995
java.util.concurrent.TimeoutException: null
        at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1784) ~[na:1.8.0_311]
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928) ~[na:1.8.0_311]
        at io.openmessaging.storage.dledger.DLedgerEntryPusher$EntryDispatcher.doCompare(DLedgerEntryPusher.java:663) ~[dledger-0.2.2.jar:na]
        at io.openmessaging.storage.dledger.DLedgerEntryPusher$EntryDispatcher.doWork(DLedgerEntryPusher.java:740) ~[dledger-0.2.2.jar:na]
        at io.openmessaging.storage.dledger.ShutdownAbleThread.run(ShutdownAbleThread.java:86) [dledger-0.2.2.jar:na]
2022-11-05 21:30:01 ERROR NettyClientPublicExecutor_7 - HeartBeat request time out, info[group=RaftNode00,term=117,code=200,local=n0,remote=n1,leader=n0]
2022-11-05 21:30:01 INFO QuorumAckChecker-n0 - [n0][LEADER] term=117 ledgerBegin=561124490 ledgerEnd=590274995 committed=590274995 watermarks={117:{"n0":590274995,"n1":-1,"n2":590274995}}
2022-11-05 21:30:03 ERROR NettyClientPublicExecutor_8 - HeartBeat request time out, info[group=RaftNode00,term=117,code=200,local=n0,remote=n1,leader=n0]
2022-11-05 21:30:04 INFO QuorumAckChecker-n0 - [n0][LEADER] term=117 ledgerBegin=561124490 ledgerEnd=590274995 committed=590274995 watermarks={117:{"n0":590274995,"n1":-1,"n2":590274995}}
2022-11-05 21:30:04 ERROR EntryDispatcher-n0-n1 - [Push-n1]Error in EntryDispatcher-n0-n1 writeIndex=578832166 compareIndex=590274995
java.util.concurrent.TimeoutException: null
        at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1784) ~[na:1.8.0_311]
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928) ~[na:1.8.0_311]
        at io.openmessaging.storage.dledger.DLedgerEntryPusher$EntryDispatcher.doCompare(DLedgerEntryPusher.java:663) ~[dledger-0.2.2.jar:na]
        at io.openmessaging.storage.dledger.DLedgerEntryPusher$EntryDispatcher.doWork(DLedgerEntryPusher.java:740) ~[dledger-0.2.2.jar:na]
        at io.openmessaging.storage.dledger.ShutdownAbleThread.run(ShutdownAbleThread.java:86) [dledger-0.2.2.jar:na]
2022-11-05 21:30:04 INFO EntryDispatcher-n0-n1 - [Push-n1]Change state from COMPARE to TRUNCATE at 590274995
2022-11-05 21:30:04 INFO EntryDispatcher-n0-n1 - [Push-n1]Will push data to truncate truncateIndex=590274995 pos=569653967134
2022-11-05 21:30:04 INFO EntryDispatcher-n0-n1 - [Push-n1]Change state from TRUNCATE to APPEND at 590274995
