### ISSUE TITLE
The current rocketmq logger incompatible with third-party libraries 

### ISSUE THREAD

**Issue by echooymxq** [apache/rocketmq#5604]
```
java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at io.openmessaging.storage.dledger.DLedgerServer.<clinit>(DLedgerServer.java:69)
	at org.apache.rocketmq.controller.impl.DLedgerController.<init>(DLedgerController.java:113)
	at org.apache.rocketmq.controller.ControllerManager.initialize(ControllerManager.java:98)
	at org.apache.rocketmq.namesrv.NamesrvStartup.start(NamesrvStartup.java:201)
	at org.apache.rocketmq.namesrv.NamesrvStartup.createAndStartControllerManager(NamesrvStartup.java:180)
	at org.apache.rocketmq.namesrv.NamesrvStartup.controllerManagerMain(NamesrvStartup.java:73)
	at org.apache.rocketmq.namesrv.NamesrvStartup.main(NamesrvStartup.java:54)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
```
@aaron-ai

**Comment by aaron-ai** [comment]
OK, I'll fix it.
