### ISSUE TITLE
org.apache.rocketmq.remoting.exception.RemotingTooMuchRequestException: sendDefaultImpl call timeout

### ISSUE THREAD

**Issue by fengxueyun** [apache/rocketmq#568]
org.apache.rocketmq.remoting.exception.RemotingTooMuchRequestException: sendDefaultImpl call timeout
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendDefaultImpl(DefaultMQProducerImpl.java:612) ~[rocketmq-client-4.3.1.jar:4.3.1]
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1253) ~[rocketmq-client-4.3.1.jar:4.3.1]
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1203) ~[rocketmq-client-4.3.1.jar:4.3.1]
	at org.apache.rocketmq.client.producer.DefaultMQProducer.send(DefaultMQProducer.java:214) ~[rocketmq-client-4.3.1.jar:4.3.1]

在出这个异常之前有[NettyClientSelector_1] INFO  RocketmqRemoting.info (Slf4jLoggerFactory.java:95) 
closeChannel: close the connection to remote address[] result: true

通过telnet验证过9876端口是通的
rocketMQ后台管理界面有应用机器ip，master的broker.log中查看也有对应ip。但是就是发消息失败

**Comment by fengxueyun** [comment]
少开了端口10909。

**Comment by FFGF** [comment]
> maybe you should close the vip channel,detail can see [Apache RocketMQ单机部署](https://liangyuanpeng.github.io/post/2018-11-27-rocketmq%E7%8E%AF%E5%A2%83%E6%90%AD%E5%BB%BA/)
> 
> rocket除了9876其实还有两个端口
> 10911
> 10909
> 
> 10909是VIP通道对应的端口，在JAVA中的消费者对象或者是生产者对象中关闭VIP通道即可无需开放10909端口
> 
> 使用如下方法
> `setVipChannelEnabled(false);`
> 详细的可以看看[Apache RocketMQ单机部署](https://liangyuanpeng.github.io/post/2018-11-27-rocketmq%E7%8E%AF%E5%A2%83%E6%90%AD%E5%BB%BA/)

 `setVipChannelEnabled(false);`解决问题了，搞了三四个小时，各种设置，官网的demo也不说一声，有点坑啊。

**Comment by liyang12162006** [comment]
producer.setSendMsgTimeout(15000);
