### ISSUE TITLE
rocketmq does not support IPv6 in dleger mode

### ISSUE THREAD

**Issue by renwanqian** [apache/rocketmq#5858]
in dleger mode，rocketmq can't parse the dLegerPeers in ipv6 mode.
for example, when you setting the dLegerPeers as belows: 
dLegerPeers=n0-[fd15:4ba5:5a2b:1008::9:5]:30921;n1-[fd15:4ba5:5a2b:1008::9:3]:30921;n2-[fd15:4ba5:5a2b:1008::9:4]:30921
a error will occur:
java.lang.NumberFormatException: For input string: "4ba5"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.parseInt(Integer.java:615)
        at io.openmessaging.storage.dledger.DLedgerRpcNettyService.<init>(DLedgerRpcNettyService.java:104)
        at io.openmessaging.storage.dledger.DLedgerServer.<init>(DLedgerServer.java:105)
        at io.openmessaging.storage.dledger.DLedgerServer.<init>(DLedgerServer.java:87)
        at org.apache.rocketmq.store.dledger.DLedgerCommitLog.<init>(DLedgerCommitLog.java:102)
        at org.apache.rocketmq.store.DefaultMessageStore.<init>(DefaultMessageStore.java:183)
        at org.apache.rocketmq.broker.BrokerController.initialize(BrokerController.java:723)
        at org.apache.rocketmq.broker.BrokerStartup.createBrokerController(BrokerStartup.java:224)
        at org.apache.rocketmq.broker.BrokerStartup.main(BrokerStartup.java:58)

**Comment by renwanqian** [comment]
anyone done in dLegerPeers mode and IPv6 environment？

**Comment by renwanqian** [comment]
This bug  hasn't been solved yet, but it stems from a bug in another project, openmessaging delger.
So, I will file the issue on that project.
