### ISSUE TITLE
docker with lots of topic: No file descriptors available

### ISSUE THREAD

**Issue by carlvine500** [apache/rocketmq#5899]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)
run rocketmq4.9 in docker with lots of topic and consumerGroup for about 1 week ,

- What is expected to see?
can produce message  and consume message
- What did you see instead?
produce or consume message timeout
there some error in broker_default.log: 
```
2023-01-17 11:57:57 WARN NettyNIOBoss_1 - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It us
ually means the last handler in the pipeline did not handle the exception.
java.io.IOException: No file descriptors available
        at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
        at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422)
        at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
        at io.netty.util.internal.SocketUtils$5.run(SocketUtils.java:119)
        at io.netty.util.internal.SocketUtils$5.run(SocketUtils.java:116)
        at java.security.AccessController.doPrivileged(Native Method)
        at io.netty.util.internal.SocketUtils.accept(SocketUtils.java:116)
        at io.netty.channel.socket.nio.NioServerSocketChannel.doReadMessages(NioServerSocketChannel.java:154)
        at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:79)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by carlvine500** [comment]
we fix it after check the ulimit  .
before fixed: 
> ulimit -a
```
...
-n: file descriptors               1024
...
```
after fixed:
```
...
-n: file descriptors               10240
...
```
step1: /usr/lib/systemd/system/docker.service
[Service]
LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity
step2: /etc/sysconfig/docker
OPTIONS="--default-ulimit nofile=10240:10240"
