### ISSUE TITLE
Cannot start mqbroker.cmd due to corrupted delayOffset.json file on Windows system

### ISSUE THREAD

**Issue by zhuermao** [apache/rocketmq#6096]
# Symptom

I run the following command to start RocketMQ Broker on Windows system:

```
start c:\Programs\rocketmq-all-4.9.4-bin-release\bin\mqbroker.cmd -n localhost:9876 autoCreateTopicEnable=true
```

But it failed and showed nothing.

I checked the `broker.log` file in the `logs/rocketmqlogs` directory under my user home dir.  It says:

```
2023-02-16 19:04:21 INFO main - rocketmqHome=c:\Programs\rocketmq-all-4.9.4-bin-release\
2023-02-16 19:04:21 INFO main - namesrvAddr=localhost:9876
2023-02-16 19:04:21 INFO main - brokerIP1=192.168.0.231
2023-02-16 19:04:21 INFO main - brokerIP2=192.168.0.231
2023-02-16 19:04:21 INFO main - brokerName=ShawnPro14
2023-02-16 19:04:21 INFO main - brokerClusterName=DefaultCluster
2023-02-16 19:04:21 INFO main - brokerId=0
2023-02-16 19:04:21 INFO main - brokerPermission=6
2023-02-16 19:04:21 INFO main - defaultTopicQueueNums=8
2023-02-16 19:04:21 INFO main - autoCreateTopicEnable=true
2023-02-16 19:04:21 INFO main - clusterTopicEnable=true
2023-02-16 19:04:21 INFO main - brokerTopicEnable=true
2023-02-16 19:04:21 INFO main - autoCreateSubscriptionGroup=true
2023-02-16 19:04:21 INFO main - messageStorePlugIn=
2023-02-16 19:04:21 INFO main - msgTraceTopicName=RMQ_SYS_TRACE_TOPIC
2023-02-16 19:04:21 INFO main - traceTopicEnable=false
2023-02-16 19:04:21 INFO main - sendMessageThreadPoolNums=4
2023-02-16 19:04:21 INFO main - putMessageFutureThreadPoolNums=4
2023-02-16 19:04:21 INFO main - pullMessageThreadPoolNums=48
2023-02-16 19:04:21 INFO main - processReplyMessageThreadPoolNums=48
2023-02-16 19:04:21 INFO main - queryMessageThreadPoolNums=24
2023-02-16 19:04:21 INFO main - adminBrokerThreadPoolNums=16
2023-02-16 19:04:21 INFO main - clientManageThreadPoolNums=32
2023-02-16 19:04:21 INFO main - consumerManageThreadPoolNums=32
2023-02-16 19:04:21 INFO main - heartbeatThreadPoolNums=16
2023-02-16 19:04:21 INFO main - endTransactionThreadPoolNums=40
2023-02-16 19:04:21 INFO main - flushConsumerOffsetInterval=5000
2023-02-16 19:04:21 INFO main - flushConsumerOffsetHistoryInterval=60000
2023-02-16 19:04:21 INFO main - rejectTransactionMessage=false
2023-02-16 19:04:21 INFO main - fetchNamesrvAddrByAddressServer=false
2023-02-16 19:04:21 INFO main - sendThreadPoolQueueCapacity=10000
2023-02-16 19:04:21 INFO main - putThreadPoolQueueCapacity=10000
2023-02-16 19:04:21 INFO main - pullThreadPoolQueueCapacity=100000
2023-02-16 19:04:21 INFO main - replyThreadPoolQueueCapacity=10000
2023-02-16 19:04:21 INFO main - queryThreadPoolQueueCapacity=20000
2023-02-16 19:04:21 INFO main - clientManagerThreadPoolQueueCapacity=1000000
2023-02-16 19:04:21 INFO main - consumerManagerThreadPoolQueueCapacity=1000000
2023-02-16 19:04:21 INFO main - heartbeatThreadPoolQueueCapacity=50000
2023-02-16 19:04:21 INFO main - endTransactionPoolQueueCapacity=100000
2023-02-16 19:04:21 INFO main - filterServerNums=0
2023-02-16 19:04:21 INFO main - longPollingEnable=true
2023-02-16 19:04:21 INFO main - shortPollingTimeMills=1000
2023-02-16 19:04:21 INFO main - notifyConsumerIdsChangedEnable=true
2023-02-16 19:04:21 INFO main - highSpeedMode=false
2023-02-16 19:04:21 INFO main - commercialEnable=true
2023-02-16 19:04:21 INFO main - commercialTimerCount=1
2023-02-16 19:04:21 INFO main - commercialTransCount=1
2023-02-16 19:04:21 INFO main - commercialBigCount=1
2023-02-16 19:04:21 INFO main - commercialBaseCount=1
2023-02-16 19:04:21 INFO main - transferMsgByHeap=true
2023-02-16 19:04:21 INFO main - maxDelayTime=40
2023-02-16 19:04:21 INFO main - regionId=DefaultRegion
2023-02-16 19:04:21 INFO main - registerBrokerTimeoutMills=6000
2023-02-16 19:04:21 INFO main - slaveReadEnable=false
2023-02-16 19:04:21 INFO main - disableConsumeIfConsumerReadSlowly=false
2023-02-16 19:04:21 INFO main - consumerFallbehindThreshold=17179869184
2023-02-16 19:04:21 INFO main - brokerFastFailureEnable=true
2023-02-16 19:04:21 INFO main - waitTimeMillsInSendQueue=200
2023-02-16 19:04:21 INFO main - waitTimeMillsInPullQueue=5000
2023-02-16 19:04:21 INFO main - waitTimeMillsInHeartbeatQueue=31000
2023-02-16 19:04:21 INFO main - waitTimeMillsInTransactionQueue=3000
2023-02-16 19:04:21 INFO main - startAcceptSendRequestTimeStamp=0
2023-02-16 19:04:21 INFO main - traceOn=true
2023-02-16 19:04:21 INFO main - enableCalcFilterBitMap=false
2023-02-16 19:04:21 INFO main - expectConsumerNumUseFilter=32
2023-02-16 19:04:21 INFO main - maxErrorRateOfBloomFilter=20
2023-02-16 19:04:21 INFO main - filterDataCleanTimeSpan=86400000
2023-02-16 19:04:21 INFO main - filterSupportRetry=false
2023-02-16 19:04:21 INFO main - enablePropertyFilter=false
2023-02-16 19:04:21 INFO main - compressedRegister=false
2023-02-16 19:04:21 INFO main - forceRegister=true
2023-02-16 19:04:21 INFO main - registerNameServerPeriod=30000
2023-02-16 19:04:21 INFO main - transactionTimeOut=6000
2023-02-16 19:04:21 INFO main - transactionCheckMax=15
2023-02-16 19:04:21 INFO main - transactionCheckInterval=60000
2023-02-16 19:04:21 INFO main - aclEnable=false
2023-02-16 19:04:21 INFO main - storeReplyMessageEnable=true
2023-02-16 19:04:21 INFO main - enableDetailStat=true
2023-02-16 19:04:21 INFO main - autoDeleteUnusedStats=false
2023-02-16 19:04:21 INFO main - isolateLogEnable=false
2023-02-16 19:04:21 INFO main - listenPort=10911
2023-02-16 19:04:21 INFO main - serverWorkerThreads=8
2023-02-16 19:04:21 INFO main - serverCallbackExecutorThreads=0
2023-02-16 19:04:21 INFO main - serverSelectorThreads=3
2023-02-16 19:04:21 INFO main - serverOnewaySemaphoreValue=256
2023-02-16 19:04:21 INFO main - serverAsyncSemaphoreValue=64
2023-02-16 19:04:21 INFO main - serverChannelMaxIdleTimeSeconds=120
2023-02-16 19:04:21 INFO main - serverSocketSndBufSize=0
2023-02-16 19:04:21 INFO main - serverSocketRcvBufSize=0
2023-02-16 19:04:21 INFO main - writeBufferHighWaterMark=0
2023-02-16 19:04:21 INFO main - writeBufferLowWaterMark=0
2023-02-16 19:04:21 INFO main - serverSocketBacklog=1024
2023-02-16 19:04:21 INFO main - serverPooledByteBufAllocatorEnable=true
2023-02-16 19:04:21 INFO main - useEpollNativeSelector=false
2023-02-16 19:04:21 INFO main - clientWorkerThreads=4
2023-02-16 19:04:21 INFO main - clientCallbackExecutorThreads=16
2023-02-16 19:04:21 INFO main - clientOnewaySemaphoreValue=65535
2023-02-16 19:04:21 INFO main - clientAsyncSemaphoreValue=65535
2023-02-16 19:04:21 INFO main - connectTimeoutMillis=3000
2023-02-16 19:04:21 INFO main - channelNotActiveInterval=60000
2023-02-16 19:04:21 INFO main - clientChannelMaxIdleTimeSeconds=120
2023-02-16 19:04:21 INFO main - clientSocketSndBufSize=0
2023-02-16 19:04:21 INFO main - clientSocketRcvBufSize=0
2023-02-16 19:04:21 INFO main - clientPooledByteBufAllocatorEnable=false
2023-02-16 19:04:21 INFO main - clientCloseSocketIfTimeout=true
2023-02-16 19:04:21 INFO main - useTLS=false
2023-02-16 19:04:21 INFO main - writeBufferHighWaterMark=0
2023-02-16 19:04:21 INFO main - writeBufferLowWaterMark=0
2023-02-16 19:04:21 INFO main - storePathRootDir=C:\Users\shawn.zhu\store
2023-02-16 19:04:21 INFO main - storePathCommitLog=
2023-02-16 19:04:21 INFO main - storePathDLedgerCommitLog=
2023-02-16 19:04:21 INFO main - readOnlyCommitLogStorePaths=
2023-02-16 19:04:21 INFO main - mappedFileSizeCommitLog=1073741824
2023-02-16 19:04:21 INFO main - mappedFileSizeConsumeQueue=6000000
2023-02-16 19:04:21 INFO main - enableConsumeQueueExt=false
2023-02-16 19:04:21 INFO main - mappedFileSizeConsumeQueueExt=50331648
2023-02-16 19:04:21 INFO main - bitMapLengthConsumeQueueExt=64
2023-02-16 19:04:21 INFO main - flushIntervalCommitLog=500
2023-02-16 19:04:21 INFO main - commitIntervalCommitLog=200
2023-02-16 19:04:21 INFO main - useReentrantLockWhenPutMessage=true
2023-02-16 19:04:21 INFO main - flushCommitLogTimed=true
2023-02-16 19:04:21 INFO main - flushIntervalConsumeQueue=1000
2023-02-16 19:04:21 INFO main - cleanResourceInterval=10000
2023-02-16 19:04:21 INFO main - deleteCommitLogFilesInterval=100
2023-02-16 19:04:21 INFO main - deleteConsumeQueueFilesInterval=100
2023-02-16 19:04:21 INFO main - destroyMapedFileIntervalForcibly=120000
2023-02-16 19:04:21 INFO main - redeleteHangedFileInterval=120000
2023-02-16 19:04:21 INFO main - deleteWhen=04
2023-02-16 19:04:21 INFO main - diskMaxUsedSpaceRatio=75
2023-02-16 19:04:21 INFO main - fileReservedTime=72
2023-02-16 19:04:21 INFO main - putMsgIndexHightWater=600000
2023-02-16 19:04:21 INFO main - maxMessageSize=4194304
2023-02-16 19:04:21 INFO main - checkCRCOnRecover=true
2023-02-16 19:04:21 INFO main - flushCommitLogLeastPages=4
2023-02-16 19:04:21 INFO main - commitCommitLogLeastPages=4
2023-02-16 19:04:21 INFO main - flushLeastPagesWhenWarmMapedFile=4096
2023-02-16 19:04:21 INFO main - flushConsumeQueueLeastPages=2
2023-02-16 19:04:21 INFO main - flushCommitLogThoroughInterval=10000
2023-02-16 19:04:21 INFO main - commitCommitLogThoroughInterval=200
2023-02-16 19:04:21 INFO main - flushConsumeQueueThoroughInterval=60000
2023-02-16 19:04:21 INFO main - maxTransferBytesOnMessageInMemory=262144
2023-02-16 19:04:21 INFO main - maxTransferCountOnMessageInMemory=32
2023-02-16 19:04:21 INFO main - maxTransferBytesOnMessageInDisk=65536
2023-02-16 19:04:21 INFO main - maxTransferCountOnMessageInDisk=8
2023-02-16 19:04:21 INFO main - accessMessageInMemoryMaxRatio=40
2023-02-16 19:04:21 INFO main - messageIndexEnable=true
2023-02-16 19:04:21 INFO main - maxHashSlotNum=5000000
2023-02-16 19:04:21 INFO main - maxIndexNum=20000000
2023-02-16 19:04:21 INFO main - maxMsgsNumBatch=64
2023-02-16 19:04:21 INFO main - messageIndexSafe=false
2023-02-16 19:04:21 INFO main - haListenPort=10912
2023-02-16 19:04:21 INFO main - haSendHeartbeatInterval=5000
2023-02-16 19:04:21 INFO main - haHousekeepingInterval=20000
2023-02-16 19:04:21 INFO main - haTransferBatchSize=32768
2023-02-16 19:04:21 INFO main - haMasterAddress=
2023-02-16 19:04:21 INFO main - haSlaveFallbehindMax=268435456
2023-02-16 19:04:21 INFO main - brokerRole=ASYNC_MASTER
2023-02-16 19:04:21 INFO main - flushDiskType=ASYNC_FLUSH
2023-02-16 19:04:21 INFO main - syncFlushTimeout=5000
2023-02-16 19:04:21 INFO main - slaveTimeout=3000
2023-02-16 19:04:21 INFO main - messageDelayLevel=1s 5s 10s 30s 1m 2m 3m 4m 5m 6m 7m 8m 9m 10m 20m 30m 1h 2h
2023-02-16 19:04:21 INFO main - flushDelayOffsetInterval=10000
2023-02-16 19:04:21 INFO main - cleanFileForciblyEnable=true
2023-02-16 19:04:21 INFO main - warmMapedFileEnable=false
2023-02-16 19:04:21 INFO main - offsetCheckInSlave=false
2023-02-16 19:04:21 INFO main - debugLockEnable=false
2023-02-16 19:04:21 INFO main - duplicationEnable=false
2023-02-16 19:04:21 INFO main - diskFallRecorded=true
2023-02-16 19:04:21 INFO main - osPageCacheBusyTimeOutMills=1000
2023-02-16 19:04:21 INFO main - defaultQueryMaxNum=32
2023-02-16 19:04:21 INFO main - transientStorePoolEnable=false
2023-02-16 19:04:21 INFO main - transientStorePoolSize=5
2023-02-16 19:04:21 INFO main - fastFailIfNoBufferInStorePool=false
2023-02-16 19:04:21 INFO main - enableDLegerCommitLog=false
2023-02-16 19:04:21 INFO main - dLegerGroup=
2023-02-16 19:04:21 INFO main - dLegerPeers=
2023-02-16 19:04:21 INFO main - dLegerSelfId=
2023-02-16 19:04:21 INFO main - preferredLeaderId=
2023-02-16 19:04:21 INFO main - isEnableBatchPush=false
2023-02-16 19:04:21 INFO main - enableScheduleMessageStats=true
2023-02-16 19:04:21 INFO main - enableLmq=false
2023-02-16 19:04:21 INFO main - enableMultiDispatch=false
2023-02-16 19:04:21 INFO main - maxLmqConsumeQueueNum=20000
2023-02-16 19:04:21 INFO main - enableScheduleAsyncDeliver=false
2023-02-16 19:04:21 INFO main - scheduleAsyncDeliverMaxPendingLimit=2000
2023-02-16 19:04:21 INFO main - scheduleAsyncDeliverMaxResendNum2Blocked=3
2023-02-16 19:04:22 INFO main - load exist local topic, TopicConfig [topicName=logwire_web_socket, readQueueNums=4, writeQueueNums=4, perm=RW-, topicFilterType=SINGLE_TAG, topicSysFlag=0, order=false]
2023-02-16 19:04:22 INFO main - load exist local topic, TopicConfig [topicName=RMQ_SYS_TRANS_HALF_TOPIC, readQueueNums=1, writeQueueNums=1, perm=RW-, topicFilterType=SINGLE_TAG, topicSysFlag=0, order=false]
2023-02-16 19:04:22 INFO main - load exist local topic, TopicConfig [topicName=%RETRY%logwire_web_socket, readQueueNums=1, writeQueueNums=1, perm=RW-, topicFilterType=SINGLE_TAG, topicSysFlag=0, order=false]
2023-02-16 19:04:22 INFO main - load exist local topic, TopicConfig [topicName=BenchmarkTest, readQueueNums=1024, writeQueueNums=1024, perm=RW-, topicFilterType=SINGLE_TAG, topicSysFlag=0, order=false]
2023-02-16 19:04:22 INFO main - load exist local topic, TopicConfig [topicName=OFFSET_MOVED_EVENT, readQueueNums=1, writeQueueNums=1, perm=RW-, topicFilterType=SINGLE_TAG, topicSysFlag=0, order=false]
2023-02-16 19:04:22 INFO main - load exist local topic, TopicConfig [topicName=ShawnPro14, readQueueNums=1, writeQueueNums=1, perm=RWX, topicFilterType=SINGLE_TAG, topicSysFlag=0, order=false]
2023-02-16 19:04:22 INFO main - load exist local topic, TopicConfig [topicName=TBW102, readQueueNums=8, writeQueueNums=8, perm=RWX, topicFilterType=SINGLE_TAG, topicSysFlag=0, order=false]
2023-02-16 19:04:22 INFO main - load exist local topic, TopicConfig [topicName=SELF_TEST_TOPIC, readQueueNums=1, writeQueueNums=1, perm=RW-, topicFilterType=SINGLE_TAG, topicSysFlag=0, order=false]
2023-02-16 19:04:22 INFO main - load exist local topic, TopicConfig [topicName=DefaultCluster, readQueueNums=16, writeQueueNums=16, perm=RWX, topicFilterType=SINGLE_TAG, topicSysFlag=0, order=false]
2023-02-16 19:04:22 INFO main - load exist local topic, TopicConfig [topicName=SCHEDULE_TOPIC_XXXX, readQueueNums=18, writeQueueNums=18, perm=RW-, topicFilterType=SINGLE_TAG, topicSysFlag=0, order=false]
2023-02-16 19:04:22 INFO main - load exist local topic, TopicConfig [topicName=DefaultCluster_REPLY_TOPIC, readQueueNums=1, writeQueueNums=1, perm=RW-, topicFilterType=SINGLE_TAG, topicSysFlag=0, order=false]
2023-02-16 19:04:22 INFO main - load exist local topic, TopicConfig [topicName=%RETRY%logwire_zx_generate_data_key, readQueueNums=1, writeQueueNums=1, perm=RW-, topicFilterType=SINGLE_TAG, topicSysFlag=0, order=false]
2023-02-16 19:04:22 INFO main - load C:\Users\shawn.zhu\store\config\topics.json OK
2023-02-16 19:04:22 INFO main - load C:\Users\shawn.zhu\store\config\consumerOffset.json OK
2023-02-16 19:04:22 INFO main - load exist subscription group, SubscriptionGroupConfig [groupName=SELF_TEST_C_GROUP, consumeEnable=true, consumeFromMinEnable=true, consumeBroadcastEnable=true, retryQueueNums=1, retryMaxTimes=16, brokerId=0, whichBrokerWhenConsumeSlowly=1, notifyConsumerIdsChangedEnable=true]
2023-02-16 19:04:22 INFO main - load exist subscription group, SubscriptionGroupConfig [groupName=logwire_web_socket, consumeEnable=true, consumeFromMinEnable=true, consumeBroadcastEnable=true, retryQueueNums=1, retryMaxTimes=16, brokerId=0, whichBrokerWhenConsumeSlowly=1, notifyConsumerIdsChangedEnable=true]
2023-02-16 19:04:22 INFO main - load exist subscription group, SubscriptionGroupConfig [groupName=CID_ONSAPI_OWNER, consumeEnable=true, consumeFromMinEnable=true, consumeBroadcastEnable=true, retryQueueNums=1, retryMaxTimes=16, brokerId=0, whichBrokerWhenConsumeSlowly=1, notifyConsumerIdsChangedEnable=true]
2023-02-16 19:04:22 INFO main - load exist subscription group, SubscriptionGroupConfig [groupName=CID_ONSAPI_PERMISSION, consumeEnable=true, consumeFromMinEnable=true, consumeBroadcastEnable=true, retryQueueNums=1, retryMaxTimes=16, brokerId=0, whichBrokerWhenConsumeSlowly=1, notifyConsumerIdsChangedEnable=true]
2023-02-16 19:04:22 INFO main - load exist subscription group, SubscriptionGroupConfig [groupName=TOOLS_CONSUMER, consumeEnable=true, consumeFromMinEnable=true, consumeBroadcastEnable=true, retryQueueNums=1, retryMaxTimes=16, brokerId=0, whichBrokerWhenConsumeSlowly=1, notifyConsumerIdsChangedEnable=true]
2023-02-16 19:04:22 INFO main - load exist subscription group, SubscriptionGroupConfig [groupName=CID_ONS-HTTP-PROXY, consumeEnable=true, consumeFromMinEnable=true, consumeBroadcastEnable=true, retryQueueNums=1, retryMaxTimes=16, brokerId=0, whichBrokerWhenConsumeSlowly=1, notifyConsumerIdsChangedEnable=true]
2023-02-16 19:04:22 INFO main - load exist subscription group, SubscriptionGroupConfig [groupName=FILTERSRV_CONSUMER, consumeEnable=true, consumeFromMinEnable=true, consumeBroadcastEnable=true, retryQueueNums=1, retryMaxTimes=16, brokerId=0, whichBrokerWhenConsumeSlowly=1, notifyConsumerIdsChangedEnable=true]
2023-02-16 19:04:22 INFO main - load exist subscription group, SubscriptionGroupConfig [groupName=CID_ONSAPI_PULL, consumeEnable=true, consumeFromMinEnable=true, consumeBroadcastEnable=true, retryQueueNums=1, retryMaxTimes=16, brokerId=0, whichBrokerWhenConsumeSlowly=1, notifyConsumerIdsChangedEnable=true]
2023-02-16 19:04:22 INFO main - load exist subscription group, SubscriptionGroupConfig [groupName=logwire_zx_generate_data_key, consumeEnable=true, consumeFromMinEnable=true, consumeBroadcastEnable=true, retryQueueNums=1, retryMaxTimes=16, brokerId=0, whichBrokerWhenConsumeSlowly=1, notifyConsumerIdsChangedEnable=true]
2023-02-16 19:04:22 INFO main - load C:\Users\shawn.zhu\store\config\subscriptionGroup.json OK
2023-02-16 19:04:22 INFO main - load C:\Users\shawn.zhu\store\config\consumerFilter.json OK
2023-02-16 19:04:22 INFO main - Try to start service thread:AllocateMappedFileService started:false lastThread:null
2023-02-16 19:04:22 ERROR main - load C:\Users\shawn.zhu\store\config\delayOffset.json failed, and try to load backup file
com.alibaba.fastjson.JSONException: syntax error, expect {, actual EOF, pos 21, fastjson-version 1.2.69
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:503)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.parseRest(JavaBeanDeserializer.java:1576)
	at com.alibaba.fastjson.parser.deserializer.FastjsonASMDeserializer_7_DelayOffsetSerializeWrapper.deserialze(Unknown Source)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:284)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:688)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:396)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:300)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:573)
	at org.apache.rocketmq.remoting.protocol.RemotingSerializable.fromJson(RemotingSerializable.java:46)
	at org.apache.rocketmq.store.schedule.ScheduleMessageService.decode(ScheduleMessageService.java:262)
	at org.apache.rocketmq.common.ConfigManager.load(ConfigManager.java:38)
	at org.apache.rocketmq.store.schedule.ScheduleMessageService.load(ScheduleMessageService.java:210)
	at org.apache.rocketmq.store.DefaultMessageStore.load(DefaultMessageStore.java:217)
	at org.apache.rocketmq.broker.BrokerController.initialize(BrokerController.java:270)
	at org.apache.rocketmq.broker.BrokerStartup.createBrokerController(BrokerStartup.java:220)
	at org.apache.rocketmq.broker.BrokerStartup.main(BrokerStartup.java:57)
2023-02-16 19:04:22 ERROR main - load C:\Users\shawn.zhu\store\config\delayOffset.json Failed
com.alibaba.fastjson.JSONException: syntax error, expect {, actual EOF, pos 21, fastjson-version 1.2.69
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:503)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.parseRest(JavaBeanDeserializer.java:1576)
	at com.alibaba.fastjson.parser.deserializer.FastjsonASMDeserializer_7_DelayOffsetSerializeWrapper.deserialze(Unknown Source)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:284)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:688)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:396)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:300)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:573)
	at org.apache.rocketmq.remoting.protocol.RemotingSerializable.fromJson(RemotingSerializable.java:46)
	at org.apache.rocketmq.store.schedule.ScheduleMessageService.decode(ScheduleMessageService.java:262)
	at org.apache.rocketmq.common.ConfigManager.loadBak(ConfigManager.java:56)
	at org.apache.rocketmq.common.ConfigManager.load(ConfigManager.java:44)
	at org.apache.rocketmq.store.schedule.ScheduleMessageService.load(ScheduleMessageService.java:210)
	at org.apache.rocketmq.store.DefaultMessageStore.load(DefaultMessageStore.java:217)
	at org.apache.rocketmq.broker.BrokerController.initialize(BrokerController.java:270)
	at org.apache.rocketmq.broker.BrokerStartup.createBrokerController(BrokerStartup.java:220)
	at org.apache.rocketmq.broker.BrokerStartup.main(BrokerStartup.java:57)
2023-02-16 19:04:22 INFO main - Try to shutdown service thread:AllocateMappedFileService started:true lastThread:Thread[AllocateMappedFileService,5,main]
2023-02-16 19:04:22 INFO main - shutdown thread AllocateMappedFileService interrupt true
2023-02-16 19:04:22 INFO main - join thread AllocateMappedFileService elapsed time(ms) 0 90000
2023-02-16 19:04:22 INFO main - Try to shutdown service thread:PullRequestHoldService started:false lastThread:null
```

Following the ERROR message, I found the `delayOffset.json` file.  Its content is completely not JSON.  It is only 21 bytes of `NUL`.

[delayOffset.zip](https://github.com/apache/rocketmq/files/10755321/delayOffset.zip)

By the way, there are also `delayOffset.json.bak` and `delayOffset.json.tmp`.  These two files have exactly the same content and same modified time with `delayOffset.json`.

# Environment

* Windows 10
* RocketMQ 4.9.4

# See also

I think this problem is exactly the same with which described in issue #3401 .  But that issue has been closed without any fix.

# Reproducing the bug

I have found the way to reproduce the bug:

* Power off my laptop by continuously pressing the power button for several seconds when the RocketMQ broker is running.
* Power on my laptop, I find that `C:\Users\shawn.zhu\store\config\delayOffset.json` has already corrupted.
  * Sometimes, the content of `delayOffset.json` is 21 bytes of `NUL`.  Sometimes, `delayOffset.json` does not exist at all.
  * Everytime, the content of `delayOffset.json.bak` and `delayOffset.json.tmp` are both 21 bytes of `NUL`.

**Comment by zhuermao** [comment]
# Reproducing the bug

I have found the way to reproduce the bug:

* Power off my laptop by continuously pressing the power button for several seconds when the RocketMQ broker is running.
* Power on my laptop, I find that `C:\Users\shawn.zhu\store\config\delayOffset.json` has already corrupted.
  * Sometimes, the content of `delayOffset.json` is 21 bytes of `NUL`.  Sometimes, `delayOffset.json` does not exist at all.
  * Everytime, the content of `delayOffset.json.bak` and `delayOffset.json.tmp` are both 21 bytes of `NUL`.
