### ISSUE TITLE
NPE found when timerWheel disabled

### ISSUE THREAD

**Issue by imzs** [apache/rocketmq#6169]
```
2023-02-24 11:12:10 INFO PopReviveService_0 - reviveQueueId=0, old offset is -1
2023-02-24 11:12:10 INFO PopReviveService_1 - reviveQueueId=1, old offset is -1
2023-02-24 11:12:10 ERROR PopReviveService_2 - reviveQueueId=2, revive error
java.lang.NullPointerException: null
	at org.apache.rocketmq.broker.processor.PopReviveService.consumeReviveMessage(PopReviveService.java:327)
	at org.apache.rocketmq.broker.processor.PopReviveService.run(PopReviveService.java:606)
	at java.lang.Thread.run(Thread.java:766)
2023-02-24 11:12:10 ERROR PopReviveService_6 - reviveQueueId=6, revive error
java.lang.NullPointerException: null
	at org.apache.rocketmq.broker.processor.PopReviveService.consumeReviveMessage(PopReviveService.java:327)
	at org.apache.rocketmq.broker.processor.PopReviveService.run(PopReviveService.java:606)
	at java.lang.Thread.run(Thread.java:766)
2023-02-24 11:12:10 ERROR PopReviveService_4 - reviveQueueId=4, revive error
```

TimerMessageStore could be null when timerWheelEnable setting false.

Since some processors are related with [timerWheelEnable], such as PopMessageProcessor, AckMessageProcessor, and only initialized once before startup, so can we check this switch and skip instantiation when disabled?

**Comment by fuyou001** [comment]
set timerWheelEnable  true, PoP feature dependency   timerWheel feature.

**Comment by drpmma** [comment]
The timerWheel-based timer message serves as the foundation of PopMessage so that it is necessary to set timerWheelEnable to true to use PopMessage.

**Comment by RongtongJin** [comment]
Hi @imzs @fuyou001 @drpmma IMO, it is not elegant to keep reporting NPE in the log when the user neither uses pop consume nor timerWheel. Maybe we can optimize it, when users disable timerWheel, they will be forced to not use pop consume and invalid NPE logs will not print.
