### ISSUE TITLE
mqAppender1 not can used

### ISSUE THREAD

**Issue by sailliu** [apache/rocketmq#619]
this is my logback.xml
```
 <appender name="mqAppender1" class="org.apache.rocketmq.logappender.logback.RocketmqLogbackAppender">
        <tag>test</tag>
        <topic>logback</topic>
        <producerGroup>test-log</producerGroup>
        <nameServerAddress>XXXXX</nameServerAddress>
        <layout>
            <pattern>%date %p %t - %m%n</pattern>
        </layout>
    </appender>

    <appender name="mqAsyncAppender1" class="ch.qos.logback.classic.AsyncAppender">
        <queueSize>1024</queueSize>
        <discardingThreshold>80</discardingThreshold>
        <maxFlushTime>2000</maxFlushTime>
        <neverBlock>true</neverBlock>
        <appender-ref ref="mqAppender1"/>
    </appender>
```
this is my RocketMQ client
```

        <dependency>
            <groupId>org.apache.rocketmq</groupId>
            <artifactId>rocketmq-client</artifactId>
            <version>4.3.2</version>
        </dependency>
```
this is my java exception
```
11:00:43,654 |-ERROR in ch.qos.logback.core.joran.action.AppenderAction - Could not create an Appender of type [org.apache.rocketmq.logappender.logback.RocketmqLogbackAppender]. ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type org.apache.rocketmq.logappender.logback.RocketmqLogbackAppender
	at ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type org.apache.rocketmq.logappender.logback.RocketmqLogbackAppender
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:69)
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassName(OptionHelper.java:45)
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassName(OptionHelper.java:34)
	at 	at ch.qos.logback.core.joran.action.AppenderAction.begin(AppenderAction.java:52)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.callBeginAction(Interpreter.java:269)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:145)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:128)
	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:50)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
	at 	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
	at 	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
	at 	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
	at 	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at 	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
	at 	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at 	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
	at 	at org.apache.rocketmq.logging.Slf4jLoggerFactory.<init>(Slf4jLoggerFactory.java:26)
	at 	at org.apache.rocketmq.logging.InternalLoggerFactory.<clinit>(InternalLoggerFactory.java:65)
	at 	at org.apache.rocketmq.client.log.ClientLogger.<clinit>(ClientLogger.java:51)
	at 	at org.apache.rocketmq.client.consumer.rebalance.AllocateMessageQueueAveragely.<init>(AllocateMessageQueueAveragely.java:30)
	at 	at org.apache.rocketmq.client.consumer.DefaultMQPushConsumer.<init>(DefaultMQPushConsumer.java:285)
	at 	at com.lf.rocketmq.base.consumer.PushConsumer.main(PushConsumer.java:21)
Caused by: java.lang.ClassNotFoundException: org.apache.rocketmq.logappender.logback.RocketmqLogbackAppender
	at 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:56)
	at 	... 24 common frames omitted
11:00:43,654 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@82:106 - ActionException in Action for tag [appender] ch.qos.logback.core.joran.spi.ActionException: ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type org.apache.rocketmq.logappender.logback.RocketmqLogbackAppender
	at ch.qos.logback.core.joran.spi.ActionException: ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type org.apache.rocketmq.logappender.logback.RocketmqLogbackAppender
	at 	at ch.qos.logback.core.joran.action.AppenderAction.begin(AppenderAction.java:76)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.callBeginAction(Interpreter.java:269)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:145)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:128)
	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:50)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
	at 	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
	at 	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
	at 	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
	at 	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at 	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
	at 	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at 	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
	at 	at org.apache.rocketmq.logging.Slf4jLoggerFactory.<init>(Slf4jLoggerFactory.java:26)
	at 	at org.apache.rocketmq.logging.InternalLoggerFactory.<clinit>(InternalLoggerFactory.java:65)
	at 	at org.apache.rocketmq.client.log.ClientLogger.<clinit>(ClientLogger.java:51)
	at 	at org.apache.rocketmq.client.consumer.rebalance.AllocateMessageQueueAveragely.<init>(AllocateMessageQueueAveragely.java:30)
	at 	at org.apache.rocketmq.client.consumer.DefaultMQPushConsumer.<init>(DefaultMQPushConsumer.java:285)
	at 	at com.lf.rocketmq.base.consumer.PushConsumer.main(PushConsumer.java:21)
Caused by: ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type org.apache.rocketmq.logappender.logback.RocketmqLogbackAppender
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:69)
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassName(OptionHelper.java:45)
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassName(OptionHelper.java:34)
	at 	at ch.qos.logback.core.joran.action.AppenderAction.begin(AppenderAction.java:52)
	at 	... 21 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.apache.rocketmq.logappender.logback.RocketmqLogbackAppender
	at 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:56)
	at 	... 24 common frames omitted
11:00:43,654 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.classic.AsyncAppender]
```

**Comment by ymwneu** [comment]
The exception already tells you the reason: ClassNotFoundException. Class RocketmqLogbackAppender is defined in logappender module.
try add dependency:
         <dependency>
            <groupId>org.apache.rocketmq</groupId>
            <artifactId>rocketmq-logappender</artifactId>
        </dependency>

**Comment by ShannonDing** [comment]
close due to time too long.
