### ISSUE TITLE
updateSubGroup command set retryPolicy can  raise JSON Exception

### ISSUE THREAD

**Issue by orchidFang** [apache/rocketmq#6416]
你好，使用updateSubGroup设置重试策略时，经检查json配置没有问题，但报json解析错误。

COMMAND:

./mqadmin updateSubGroup -n localhost:9876 -g system -p {"type":"EXPONENTIAL","exponentialRetryPolicy":{"initial":5000,"max":7200000,"multiplier":2}}

ERROR MSG:

org.apache.rocketmq.tools.command.SubCommandException: UpdateSubGroupSubCommand command failed
at org.apache.rocketmq.tools.command.consumer.UpdateSubGroupSubCommand.execute(UpdateSubGroupSubCommand.java:211)
at org.apache.rocketmq.tools.command.MQAdminStartup.main0(MQAdminStartup.java:160)
at org.apache.rocketmq.tools.command.MQAdminStartup.main(MQAdminStartup.java:110)
Caused by: com.alibaba.fastjson.JSONException: error parse true
at com.alibaba.fastjson.parser.JSONLexerBase.scanTrue(JSONLexerBase.java:4642)
at com.alibaba.fastjson.parser.JSONLexerBase.nextToken(JSONLexerBase.java:148)
at com.alibaba.fastjson.parser.DefaultJSONParser.(DefaultJSONParser.java:170)
at com.alibaba.fastjson.parser.DefaultJSONParser.(DefaultJSONParser.java:141)
at com.alibaba.fastjson.JSON.parseObject(JSON.java:378)
at com.alibaba.fastjson.JSON.parseObject(JSON.java:298)
at com.alibaba.fastjson.JSON.parseObject(JSON.java:588)
at org.apache.rocketmq.tools.command.consumer.UpdateSubGroupSubCommand.execute(UpdateSubGroupSubCommand.java:159)
... 2 more

**Comment by ShadowySpirits** [comment]
Your JSON string is valid. However, it's possible that your command line tools are outdated. If you have any additional questions, please move to [GitHub Discussion](https://github.com/apache/rocketmq/discussions), see #6153.

**Comment by orchidFang** [comment]
ok, I have moved it to Github Discussion.
