### ISSUE TITLE
Can't start the broker according to quickstart on official website

### ISSUE THREAD

**Issue by LeBW** [apache/rocketmq#6420]
**BUG REPORT**

1. Please describe the issue you observed:

When starting the broker according to the [quickstart](https://rocketmq.apache.org/zh/docs/quickStart/01quickstart), the broker fails to start.

Command: `nohup sh bin/mqbroker -n localhost:9876 --enable-proxy &`

Log:
```
2023-03-21 09:38:27 INFO main - grpc server has built. port: 8081, tlsKeyPath: 1, tlsCertPath: 16, threadPool: 136314880,              queueCapacity: {}, boosLoop: {}, workerLoop: {}, maxInboundMessageSize: {}
 2023-03-21 09:38:27 INFO main - Server is running in TLS permissive mode
 2023-03-21 09:38:27 INFO main - Using OpenSSL provider
 2023-03-21 09:38:27 INFO main - SSLContext created for server
 2023-03-21 09:38:27 INFO main - The broker[broker-a, 30.221.130.104:10911] boot success. serializeType=JSON and name server is         localhost:9876
 2023-03-21 09:38:27 INFO main - user specified name server address: localhost:9876
 2023-03-21 09:38:27 INFO main - user specified name server address: localhost:9876
 2023-03-21 09:38:27 INFO RenewalScheduledThread_1 - scan for renewal done. cost:0ms
 2023-03-21 09:38:27 ERROR main - find an unexpect err.
 java.io.IOException: Failed to bind to address 0.0.0.0/0.0.0.0:8081
     at io.grpc.netty.shaded.io.grpc.netty.NettyServer.start(NettyServer.java:328)
     at io.grpc.internal.ServerImpl.start(ServerImpl.java:184)
     at io.grpc.internal.ServerImpl.start(ServerImpl.java:93)
     at org.apache.rocketmq.proxy.grpc.GrpcServer.start(GrpcServer.java:36)
     at org.apache.rocketmq.proxy.common.AbstractStartAndShutdown.start(AbstractStartAndShutdown.java:33)
     at org.apache.rocketmq.proxy.ProxyStartup.main(ProxyStartup.java:91)
 Caused by: java.net.BindException: Address already in use
     at java.base/sun.nio.ch.Net.bind0(Native Method)
     at java.base/sun.nio.ch.Net.bind(Net.java:555)
     at java.base/sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:337)
     at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:294)
     at io.grpc.netty.shaded.io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:141)
     at io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:562)
     at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1334)
     at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:506)
     at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:491)
     at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:973)
     at io.grpc.netty.shaded.io.netty.channel.AbstractChannel.bind(AbstractChannel.java:260)
     at io.grpc.netty.shaded.io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:356)
     at io.grpc.netty.shaded.io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
     at io.grpc.netty.shaded.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
     at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
     at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
     at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
     at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
     at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
     at java.base/java.lang.Thread.run(Thread.java:833)
 2023-03-21 09:38:32 INFO RenewalScheduledThread_1 - scan for renewal done. cost:0ms
```

- What did you do (The steps to reproduce)?

- What is expected to see?

- What did you see instead?

3. Please tell us about your environment:
* Mac OS
* JDK 1.8

5. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

3. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

6. If there are some sub-tasks involved, use -[] for each sub-task and create a corresponding issue to map to the sub-task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by ShadowySpirits** [comment]
Port 8081 is currently being used. If you have any additional questions, please move to [GitHub Discussion](https://github.com/apache/rocketmq/discussions), see https://github.com/apache/rocketmq/issues/6153.

**Comment by LeBW** [comment]
> Port 8081 is currently being used. If you have any additional questions, please move to [GitHub Discussion](https://github.com/apache/rocketmq/discussions), see #6153.

![image](https://user-images.githubusercontent.com/18557164/226507883-caa5e948-7653-4835-a3ae-6ed5dfb73848.png)
8081 is not used. That's why I submit this issue.
