### ISSUE TITLE
netty bug CPU 100%

### ISSUE THREAD

**Issue by makabakaboom** [apache/rocketmq#643]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?

场景：一个JVM里面会启动很多的DefaultMQAdminExt连接去查看不同集群的状态

`"TaskWorker_466" #753 daemon prio=5 os_prio=0  nid=0x29ef9 ...
   java.lang.Thread.State: RUNNABLE
	at io.netty.util.Recycler$Stack.scavengeSome(Recycler.java:504)
	at io.netty.util.Recycler$Stack.scavenge(Recycler.java:454)
	at io.netty.util.Recycler$Stack.pop(Recycler.java:435)
	at io.netty.util.Recycler.get(Recycler.java:144)
	at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.newInstance(AbstractChannelHandlerContext.java:1115)
	at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.access$1600(AbstractChannelHandlerContext.java:1104)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:825)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:799)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:835)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1017)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:256)
	at org.apache.rocketmq.remoting.netty.NettyRemotingAbstract.invokeSyncImpl(NettyRemotingAbstract.java:370)
	at org.apache.rocketmq.remoting.netty.NettyRemotingClient.invokeSync(NettyRemotingClient.java:374)
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.getBrokerRuntimeInfo(MQClientAPIImpl.java:1121)
	at org.apache.rocketmq.tools.admin.DefaultMQAdminExtImpl.fetchBrokerRuntimeStats(DefaultMQAdminExtImpl.java:235)
	at org.apache.rocketmq.tools.admin.DefaultMQAdminExt.fetchBrokerRuntimeStats(DefaultMQAdminExt.java:202)`
- What did you expect to see?

- What did you see instead?
大量线程阻塞在Recycler类，通过Top查看线程CPU使用率100%
2. Please tell us about your environment:
version:4.3.0
3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):
https://github.com/netty/netty/pull/6180
这个是netty github上面对这个bug的描述

**Comment by whathi** [comment]
test

**Comment by dongeforever** [comment]
@davidpdw It is welcome submitting a PR to fix it.

**Comment by hdchen** [comment]
可以通过DefaultMQAdminExt#setClientCallbackExecutorThreads，把Netty的网络线程数量限制一下，默认情况下会开启 n  * DefaultMQAdminExt  *  cpucores 个网络线程！
