### ISSUE TITLE
Producer often timeout

### ISSUE THREAD

**Issue by liuluo129** [apache/rocketmq#647]
**FEATURE REQUEST**

目前是双 Master 模式，Producer 端经常会报异常，堆栈信息如下:
```
org.apache.rocketmq.remoting.exception.RemotingTimeoutException: wait response on the channel <172.19.4.4:10909> timeout, 3000(ms)
        at org.apache.rocketmq.remoting.netty.NettyRemotingAbstract.invokeSyncImpl(NettyRemotingAbstract.java:386)
        at org.apache.rocketmq.remoting.netty.NettyRemotingClient.invokeSync(NettyRemotingClient.java:369)
        at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessageSync(MQClientAPIImpl.java:351)
        at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessage(MQClientAPIImpl.java:335)
        at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessage(MQClientAPIImpl.java:298)
        at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendKernelImpl(DefaultMQProducerImpl.java:696)
        at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendSelectImpl(DefaultMQProducerImpl.java:914)
        at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:891)
        at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:886)
        at org.apache.rocketmq.client.producer.DefaultMQProducer.send(DefaultMQProducer.java:389)
```
目前双 Master 模式，配置如下:
```
brokerName=Broker-A   // 第二台是 Broker-B
brokerId=0
deleteWhen=04
fileReservedTime=72
brokerRole=ASYNC_MASTER
flushDiskType=ASYNC_FLUSH

storePathRootDir=/data/rocketmq/store
storePathCommitLog=/data/rocketmq/store/commitlog
autoCreateTopicEnable=TRUE
clusterTopicEnable=FALSE
brokerTopicEnable=FALSE

fetchNamesrvAddrByAddressServer=false
namesrvAddr=xxxx;xxxx
waitTimeMillsInSendQueue=5000
osPageCacheBusyTimeOutMills=5000
```
Producer 超时的，都发生在向Broker-B发送的时候

两台机器配置一致，且日志两边对比过，没发现有什么异常现象

**Comment by dongeforever** [comment]
@liuluo129 Make the waitTimeMillsInSendQueue is smaller than 3000 and you may get another error 'TIMEOUT_CLEAN_QUEUE'.
It seems a performance issue.

**Comment by liuluo129** [comment]
> @liuluo129 Make the waitTimeMillsInSendQueue is smaller than 3000 and you may get another error 'TIMEOUT_CLEAN_QUEUE'.

多谢回复，我再补充一些信息，出现超时的时候，并不是高峰期，而且只会在其中一台超时，观察两台机器的cpu,io,网络和日志，没发现有什么异常点，如果是性能问题，该如何排查呢

**Comment by lazyfighter** [comment]
have you Solve this problem

**Comment by Cczzzz** [comment]
请问解决这个问题了吗，我遇到同样的问题，3个master只有连接其中一个时会出现。并不是在高峰期

**Comment by duhenglucky** [comment]
@Cczzzz 看下出现问题的broker请求是否有异常，比如消费堆积严重，或者持续消费冷数据，看下stats.log 以及store.log
