### ISSUE TITLE
How to consume messages in batches? I want batch insert db

### ISSUE THREAD

**Issue by changyoutianxia** [apache/rocketmq#6481]
**FEATURE REQUEST**

1. I want batch insert db.

2.         provider.newPushConsumerBuilder()
                .setClientConfiguration(configuration)
                .setConsumerGroup(mqConsumerConfig.getConsumerGroup())
                .setSubscriptionExpressions(subscriptionMap)
                .setMessageListener(new MessageListener() {
                    @Override
                    public ConsumeResult consume(List<MessageView> messageView) {
                        return ConsumeResult.SUCCESS;
                    }
                }).build();

**Comment by f1amingo** [comment]
If I understand correctly.
Invoke the method `setConsumeMessageBatchMaxSize()` on your builder to specify the message consumption batch size (`DefaultMQPushConsumer#consumeMessageBatchMaxSize`) you want. 
By default, `consumeMessageBatchMaxSize = 1`.
By viewing the method `ConsumeMessageConcurrentlyService#submitConsumeRequest(4)`, you can understand the implementation details of consumption batching.

**Comment by francisoliverlee** [comment]
参考下：https://github.com/apache/rocketmq-clients/blob/master/java/client/src/main/java/org/apache/rocketmq/client/java/example/SimpleConsumerExample.java

**Comment by changyoutianxia** [comment]
> 参考下：https://github.com/apache/rocketmq-clients/blob/master/java/client/src/main/java/org/apache/rocketmq/client/java/example/SimpleConsumerExample.java

thank you

**Comment by fengcharly** [comment]
> 参考下：https://github.com/apache/rocketmq-clients/blob/master/java/client/src/main/java/org/apache/rocketmq/client/java/example/SimpleConsumerExample.java

SimpleConsumerExample can not consumer message，I get the error：
Exception in thread "main" io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 32.997119300s. [remote_addr=/10.12.19.4:30106]
at io.grpc.Status.asRuntimeException(Status.java:539)
at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:487)
at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:563)
at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:744)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723)
at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
