### ISSUE TITLE
mqadmin queryMsgById Command IP Error

### ISSUE THREAD

**Issue by xox9001** [apache/rocketmq#656]
i try query msg by msgId , but command Prompt error。 follow message " connect to <152.31.168.192:5664> failed " is error,IP address is 192.168.31.152,not 152.31.168.192:5664.
=========================
./mqadmin queryMsgById -d ppp -g ShowCommand -i 981FA8C0000016220000BD5803150100 -n localhost:9876
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0
org.apache.rocketmq.remoting.exception.RemotingConnectException: connect to <152.31.168.192:5664> failed
	at org.apache.rocketmq.remoting.netty.NettyRemotingClient.invokeSync(NettyRemotingClient.java:393)
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.viewMessage(MQClientAPIImpl.java:661)
	at org.apache.rocketmq.client.impl.MQAdminImpl.viewMessage(MQAdminImpl.java:252)
	at org.apache.rocketmq.tools.admin.DefaultMQAdminExtImpl.viewMessage(DefaultMQAdminExtImpl.java:958)
	at org.apache.rocketmq.tools.admin.DefaultMQAdminExtImpl.consumeMessageDirectly(DefaultMQAdminExtImpl.java:724)
	at org.apache.rocketmq.tools.admin.DefaultMQAdminExt.consumeMessageDirectly(DefaultMQAdminExt.java:397)
	at org.apache.rocketmq.tools.command.message.QueryMsgByIdSubCommand.pushMsg(QueryMsgByIdSubCommand.java:269)
	at org.apache.rocketmq.tools.command.message.QueryMsgByIdSubCommand.execute(QueryMsgByIdSubCommand.java:237)
	at org.apache.rocketmq.tools.command.MQAdminStartup.main0(MQAdminStartup.java:132)
	at org.apache.rocketmq.tools.command.MQAdminStartup.main(MQAdminStartup.java:83)

**Comment by dongeforever** [comment]
@xox9001 There maybe multi network interfaces in the host, the rocketmq broker will bind to one of them.
You could use `mqadmin clusterList` to check the binded ip. 
Alternatively, you could config the "brokerIP1" in the conf to have a determinate binding.

**Comment by xox9001** [comment]
i config brokerIP1=192.168.31.152,my cluster only one broker and one namesrv. use code push and consumer no problem,but use mqadmin has error

**Comment by xox9001** [comment]
> @xox9001 There maybe multi network interfaces in the host, the rocketmq broker will bind to one of them.
> You could use `mqadmin clusterList` to check the binded ip.
> Alternatively, you could config the "brokerIP1" in the conf to have a determinate binding.

i config brokerIP1=192.168.31.152,my cluster only one broker and one namesrv. use code push and consumer no problem,but use mqadmin has error

**Comment by xox9001** [comment]
> @xox9001 There maybe multi network interfaces in the host, the rocketmq broker will bind to one of them.
> You could use `mqadmin clusterList` to check the binded ip.
> Alternatively, you could config the "brokerIP1" in the conf to have a determinate binding.

Thanks for your reply

**Comment by xox9001** [comment]
> @xox9001 There maybe multi network interfaces in the host, the rocketmq broker will bind to one of them.
> You could use `mqadmin clusterList` to check the binded ip.
> Alternatively, you could config the "brokerIP1" in the conf to have a determinate binding.

my cluster runtime is docker,i have modified broker config brokerIP1=192.168.31.152 ，and it's already in effect

**Comment by ShannonDing** [comment]
close due to time too long, if this issue still occurs on the latest version, please reopen this issue again.
