### ISSUE TITLE
mqadmin can't resend message through queryMsgById subcommand

### ISSUE THREAD

**Issue by tongtaodragon** [apache/rocketmq#6565]
1. Please describe the issue you observed:
    a) Enable ACL
    b) Send a message successfully (This confirm local acl configuration correct)
    c) Resend message

    I expect resend message successfully. But command failed as below.
bin/mqadmin queryMsgById -i AC10051200002776000000000440F6F4 -n 172.16.7.190:8100 -s true
prepare resend msg. originalMsgId=AC10051200002776000000000440F6F4org.apache.rocketmq.client.exception.MQClientException: Send [3] times, still failed, cost [27]ms, Topic: bietp1, BrokersSent: [broker-1, broker-2, broker-3]
See http://rocketmq.apache.org/docs/faq/ for further details.
        at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendDefaultImpl(DefaultMQProducerImpl.java:647)
        at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1363)
        at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1307)
        at org.apache.rocketmq.client.producer.DefaultMQProducer.send(DefaultMQProducer.java:333)
        at org.apache.rocketmq.tools.command.message.QueryMsgByIdSubCommand.sendMsg(QueryMsgByIdSubCommand.java:278)
        at org.apache.rocketmq.tools.command.message.QueryMsgByIdSubCommand.execute(QueryMsgByIdSubCommand.java:240)
        at org.apache.rocketmq.tools.command.MQAdminStartup.main0(MQAdminStartup.java:149)
        at org.apache.rocketmq.tools.command.MQAdminStartup.main(MQAdminStartup.java:100)
Caused by: org.apache.rocketmq.client.exception.MQBrokerException: CODE: 1  DESC: org.apache.rocketmq.acl.common.AclException: No accessKey is configured, org.apache.rocketmq.acl.plain.PlainPermissionManager.validate(PlainPermissionManager.java:705) BROKER: 172.16.7.193:10110
For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
        at org.apache.rocketmq.client.impl.MQClientAPIImpl.processSendResponse(MQClientAPIImpl.java:675)
        at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessageSync(MQClientAPIImpl.java:523)
        at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessage(MQClientAPIImpl.java:505)
        at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessage(MQClientAPIImpl.java:449)
        at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendKernelImpl(DefaultMQProducerImpl.java:837)
        at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendDefaultImpl(DefaultMQProducerImpl.java:575)
        ... 7 more

2. Please tell us about your environment:
A rocketmq 4.9.4 environment with one namesrv and one broker
Enable ACL

3. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):
Check the code, there is code issue in org.apache.rocketmq.tools.command.message.QueryMsgByIdSubCommand java code.

    @Override
    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {
        DefaultMQAdminExt defaultMQAdminExt = new DefaultMQAdminExt(rpcHook);
        defaultMQAdminExt.setInstanceName(Long.toString(System.currentTimeMillis()));

        =======>> no rpcHook as parameter construct producer
        DefaultMQProducer defaultMQProducer = new DefaultMQProducer("ReSendMsgById");
        defaultMQProducer.setInstanceName(Long.toString(System.currentTimeMillis()));

**Comment by Oliverwqcwrw** [comment]
This is a print error in your log
<img width="800" alt="image" src="https://user-images.githubusercontent.com/31796988/231028010-a03b604a-b76a-4dfb-ac1f-54b6f18d521c.png">
Currently, the queryMsgById command cannot be used to configure accesskey and secretKey

Welcome to submit pr to polish it

**Comment by caigy** [comment]
You may try configuring your AK/SK with admin privilege in `${ROCKETMQ_HOME}/conf/tools.yml` like this: 
```yaml
accessKey: YOUR_ADMIN_AK
secretKey: YOUR_ADMIN_SK
```

**Comment by tongtaodragon** [comment]
I configured this in ${ROCKETMQ_HOME}/conf/tools.yml already. With this configuration, I can send message successfully. But I can't resend message with the same configuration.
