### ISSUE TITLE
apache/rocketmq:5.1.0 unable to mount directory to host，/home/rocketmq/store

### ISSUE THREAD

**Issue by zhl19911203** [apache/rocketmq#6622]
docker run --name rmqbroker \
--restart=always \
-p 10909:10909 \
-p 10911:10911 \
-p 10912:10912 \
-v /home/rocketmq/broker/logs:/home/rocketmq/logs \
-v /home/rocketmq/broker/store:/home/rocketmq/store \
-v /home/rocketmq/broker/broker.conf:/home/rocketmq/rocketmq-5.1.0/conf/broker.conf \
-d apache/rocketmq:5.1.0 \
sh mqbroker -n 127.0.0.1:9876 -c /home/rocketmq/rocketmq-5.1.0/conf/broker.conf

启动命令加上这个，-v /home/rocketmq/broker/store:/home/rocketmq/store \ 就会报错，怎么把store挂载载主机上

java.lang.NullPointerException
        at org.apache.rocketmq.broker.schedule.ScheduleMessageService.configFilePath(ScheduleMessageService.java:288)
        at org.apache.rocketmq.common.ConfigManager.persist(ConfigManager.java:84)
        at org.apache.rocketmq.broker.BrokerController.shutdownBasicService(BrokerController.java:1370)
        at org.apache.rocketmq.broker.BrokerController.shutdown(BrokerController.java:1425)
        at org.apache.rocketmq.broker.BrokerStartup.createBrokerController(BrokerStartup.java:232)
        at org.apache.rocketmq.broker.BrokerStartup.main(BrokerStartup.java:50)
java.lang.NullPointerException
        at org.apache.rocketmq.broker.schedule.ScheduleMessageService.configFilePath(ScheduleMessageService.java:288)
        at org.apache.rocketmq.common.ConfigManager.persist(ConfigManager.java:84)
        at org.apache.rocketmq.broker.BrokerController.shutdownBasicService(BrokerController.java:1370)
        at org.apache.rocketmq.broker.BrokerController.shutdown(BrokerController.java:1425)
        at org.apache.rocketmq.broker.BrokerStartup.createBrokerController(BrokerStartup.java:232)
        at org.apache.rocketmq.broker.BrokerStartup.main(BrokerStartup.java:50)
java.lang.NullPointerException
        at org.apache.rocketmq.broker.schedule.ScheduleMessageService.configFilePath(ScheduleMessageService.java:288)
        at org.apache.rocketmq.common.ConfigManager.persist(ConfigManager.java:84)
        at org.apache.rocketmq.broker.BrokerController.shutdownBasicService(BrokerController.java:1370)
        at org.apache.rocketmq.broker.BrokerController.shutdown(BrokerController.java:1425)
        at org.apache.rocketmq.broker.BrokerStartup.createBrokerController(BrokerStartup.java:232)
        at org.apache.rocketmq.broker.BrokerStartup.main(BrokerStartup.java:50)

**Comment by KitherRunner** [comment]
store 目录设置权限：chmod -R 777 /home/rocketmq/broker/store

**Comment by zhl19911203** [comment]
> 做法一：修改 store/logs 目录所属用户： chown -R 3000:3000 /home/rocketmq/broker/store /home/rocketmq/broker/logs 做法二：修改 store/logs 目录权限(暴力)： chmod -R 777 /home/rocketmq/broker/store /home/rocketmq/broker/logs

两种方法都试了，启动namesrv的时候就报错了，还是没有权限

<img width="1557" alt="image" src="https://user-images.githubusercontent.com/36956485/233754541-ed1a0e1d-ec09-4237-a13a-ea11c04c81ed.png">

**Comment by zhl19911203** [comment]
> 做法一：修改 store/logs 目录所属用户： chown -R 3000:3000 /home/rocketmq/broker/store /home/rocketmq/broker/logs 做法二：修改 store/logs 目录权限(暴力)： chmod -R 777 /home/rocketmq/broker/store /home/rocketmq/broker/logs

我修改了用户和权限，可以了，谢谢🙏
