### ISSUE TITLE
when I use rocketMq with docker, and I test Producer, it occur following error, i want got help, very thanks

### ISSUE THREAD

**Issue by BetaLi** [apache/rocketmq#6631]
./tools.sh org.apache.rocketmq.example.quickstart.Producer

04:21:23.861 [NettyClientSelector_1] INFO  RocketmqRemoting - closeChannel: close the connection to remote address[] result: true
org.apache.rocketmq.client.exception.MQClientException: Send [3] times, still failed, cost [6]ms, Topic: TopicTest, BrokersSent: [broker-a, broker-a, broker-a]
See http://rocketmq.apache.org/docs/faq/ for further details.
        at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendDefaultImpl(DefaultMQProducerImpl.java:633)
        at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1280)
        at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1226)
        at org.apache.rocketmq.client.producer.DefaultMQProducer.send(DefaultMQProducer.java:283)
        at org.apache.rocketmq.example.quickstart.Producer.main(Producer.java:67)
Caused by: org.apache.rocketmq.remoting.exception.RemotingConnectException: connect to <8.130.123.101 #change you own physical IP Address:10909> failed
        at org.apache.rocketmq.remoting.netty.NettyRemotingClient.invokeSync(NettyRemotingClient.java:392)
        at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessageSync(MQClientAPIImpl.java:356)
        at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessage(MQClientAPIImpl.java:340)
        at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessage(MQClientAPIImpl.java:294)
        at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendKernelImpl(DefaultMQProducerImpl.java:808)
        at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendDefaultImpl(DefaultMQProducerImpl.java:552)
        ... 4 more

**Comment by caigy** [comment]
Is `8.130.123.101 #change you own physical IP Address:10909` original text in logs?

**Comment by KitherRunner** [comment]
> Is `8.130.123.101 #change you own physical IP Address:10909` original text in logs?

org.apache.rocketmq.example.quickstart.Producer
prioritize the use of environment variables：NAMESRV_ADDR
