### ISSUE TITLE
[Bug] Client unsupport jdk1.8

### ISSUE THREAD

**Issue by micsmile** [apache/rocketmq#6739]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

windows 111

### RocketMQ version

<dependency>
        <groupId>org.apache.rocketmq</groupId>
         <artifactId>rocketmq-client-java</artifactId>
          <version>5.0.0</version>
</dependency>

### JDK Version

JDK1.8

### Describe the Bug

五月 12, 2023 9:29:03 上午 org.apache.rocketmq.shaded.grpc.netty.GrpcSslContexts defaultSslProvider
信息: Java 9 ALPN API unavailable (this may be normal)
五月 12, 2023 9:29:03 上午 org.apache.rocketmq.shaded.grpc.netty.GrpcSslContexts defaultSslProvider
信息: netty-tcnative unavailable (this may be normal)
java.lang.IllegalArgumentException: Failed to load any of the given libraries: [netty_tcnative_windows_x86_32, netty_tcnative_x86_32, netty_tcnative]
	at org.apache.rocketmq.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:107)
	at org.apache.rocketmq.shaded.io.grpc.netty.shaded.io.netty.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:705)
	at org.apache.rocketmq.shaded.io.grpc.netty.shaded.io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:146)
	at org.apache.rocketmq.shaded.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:230)
	at org.apache.rocketmq.shaded.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:146)
	at org.apache.rocketmq.shaded.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:95)
	at org.apache.rocketmq.client.java.rpc.RpcClientImpl.<init>(RpcClientImpl.java:82)
	at org.apache.rocketmq.client.java.impl.ClientManagerImpl.getRpcClient(ClientManagerImpl.java:177)
	at org.apache.rocketmq.client.java.impl.ClientManagerImpl.queryRoute(ClientManagerImpl.java:193)
	at org.apache.rocketmq.client.java.impl.ClientImpl.fetchTopicRoute0(ClientImpl.java:635)
	at org.apache.rocketmq.client.java.impl.ClientImpl.fetchTopicRoute(ClientImpl.java:611)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1556)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.apache.rocketmq.client.java.impl.ClientImpl.startUp(ClientImpl.java:192)
	at org.apache.rocketmq.client.java.impl.producer.ProducerImpl.startUp(ProducerImpl.java:113)
	at org.apache.rocketmq.shaded.com.google.common.util.concurrent.AbstractIdleService$DelegateService$1.run(AbstractIdleService.java:62)
	at org.apache.rocketmq.shaded.com.google.common.util.concurrent.Callables.lambda$threadRenaming$3(Callables.java:103)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: org_apache_rocketmq_shaded_io_grpc_netty_shaded_netty_tcnative_windows_x86_32
		at org.apache.rocketmq.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:217)
		at org.apache.rocketmq.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:98)
		... 22 more
	Caused by: java.io.FileNotFoundException: META-INF/native/org_apache_rocketmq_shaded_io_grpc_netty_shaded_netty_tcnative_windows_x86_32.dll
		at org.apache.rocketmq.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:164)
		... 23 more
		Suppressed: java.lang.UnsatisfiedLinkError: no org_apache_rocketmq_shaded_io_grpc_netty_shaded_netty_tcnative_windows_x86_32 in java.library.path
			at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
			at java.lang.Runtime.loadLibrary0(Runtime.java:870)
			at java.lang.System.loadLibrary(System.java:1122)
			at org.apache.rocketmq.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
			at org.apache.rocketmq.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:319)
			at org.apache.rocketmq.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:139)
			... 23 more
			Suppressed: java.lang.UnsatisfiedLinkError: no org_apache_rocketmq_shaded_io_grpc_netty_shaded_netty_tcnative_windows_x86_32 in java.library.path
				at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
				at java.lang.Runtime.loadLibrary0(Runtime.java:870)
				at java.lang.System.loadLibrary(System.java:1122)
				at org.apache.rocketmq.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
				at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
				at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
				at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
				at java.lang.reflect.Method.invoke(Method.java:498)
				at org.apache.rocketmq.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:353)
				at java.security.AccessController.doPrivileged(Native Method)
				at org.apache.rocketmq.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:345)
				at org.apache.rocketmq.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:311)
				... 24 more
	Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: org_apache_rocketmq_shaded_io_grpc_netty_shaded_netty_tcnative_x86_32
		at org.apache.rocketmq.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:217)
		at org.apache.rocketmq.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:98)
		... 22 more
	Caused by: java.io.FileNotFoundException: META-INF/native/org_apache_rocketmq_shaded_io_grpc_netty_shaded_netty_tcnative_x86_32.dll
		at org.apache.rocketmq.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:164)
		... 23 more
		Suppressed: java.lang.UnsatisfiedLinkError: no org_apache_rocketmq_shaded_io_grpc_netty_shaded_netty_tcnative_x86_32 in java.library.path
			at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
			at java.lang.Runtime.loadLibrary0(Runtime.java:870)
			at java.lang.System.loadLibrary(System.java:1122)
			at org.apache.rocketmq.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
			at org.apache.rocketmq.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:319)
			at org.apache.rocketmq.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:139)
			... 23 more
			Suppressed: java.lang.UnsatisfiedLinkError: no org_apache_rocketmq_shaded_io_grpc_netty_shaded_netty_tcnative_x86_32 in java.library.path
				at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
				at java.lang.Runtime.loadLibrary0(Runtime.java:870)
				at java.lang.System.loadLibrary(System.java:1122)
				at org.apache.rocketmq.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
				at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
				at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
				at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
				at java.lang.reflect.Method.invoke(Method.java:498)
				at org.apache.rocketmq.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:353)
				at java.security.AccessController.doPrivileged(Native Method)
				at org.apache.rocketmq.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:345)
				at org.apache.rocketmq.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:311)
				... 24 more
	Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: org_apache_rocketmq_shaded_io_grpc_netty_shaded_netty_tcnative
		at org.apache.rocketmq.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:217)
		at org.apache.rocketmq.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:98)
		... 22 more
	Caused by: java.io.FileNotFoundException: META-INF/native/org_apache_rocketmq_shaded_io_grpc_netty_shaded_netty_tcnative.dll
		at org.apache.rocketmq.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:164)
		... 23 more
		Suppressed: java.lang.UnsatisfiedLinkError: no org_apache_rocketmq_shaded_io_grpc_netty_shaded_netty_tcnative in java.library.path
			at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
			at java.lang.Runtime.loadLibrary0(Runtime.java:870)
			at java.lang.System.loadLibrary(System.java:1122)
			at org.apache.rocketmq.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
			at org.apache.rocketmq.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:319)
			at org.apache.rocketmq.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:139)
			... 23 more
			Suppressed: java.lang.UnsatisfiedLinkError: no org_apache_rocketmq_shaded_io_grpc_netty_shaded_netty_tcnative in java.library.path
				at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
				at java.lang.Runtime.loadLibrary0(Runtime.java:870)
				at java.lang.System.loadLibrary(System.java:1122)
				at org.apache.rocketmq.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
				at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
				at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
				at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
				at java.lang.reflect.Method.invoke(Method.java:498)
				at org.apache.rocketmq.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:353)
				at java.security.AccessController.doPrivileged(Native Method)
				at org.apache.rocketmq.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:345)
				at org.apache.rocketmq.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:311)
				... 24 more

五月 12, 2023 9:29:03 上午 org.apache.rocketmq.shaded.grpc.netty.GrpcSslContexts defaultSslProvider
信息: Conscrypt not found (this may be normal)
java.lang.ClassNotFoundException: org.conscrypt.Conscrypt
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.apache.rocketmq.shaded.io.grpc.internal.ConscryptLoader.newProvider(ConscryptLoader.java:72)
	at org.apache.rocketmq.shaded.grpc.netty.GrpcSslContexts$ConscryptHolder.<clinit>(GrpcSslContexts.java:295)
	at org.apache.rocketmq.shaded.grpc.netty.GrpcSslContexts.findJdkProvider(GrpcSslContexts.java:268)
	at org.apache.rocketmq.shaded.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:234)
	at org.apache.rocketmq.shaded.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:146)
	at org.apache.rocketmq.shaded.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:95)
	at org.apache.rocketmq.client.java.rpc.RpcClientImpl.<init>(RpcClientImpl.java:82)
	at org.apache.rocketmq.client.java.impl.ClientManagerImpl.getRpcClient(ClientManagerImpl.java:177)
	at org.apache.rocketmq.client.java.impl.ClientManagerImpl.queryRoute(ClientManagerImpl.java:193)
	at org.apache.rocketmq.client.java.impl.ClientImpl.fetchTopicRoute0(ClientImpl.java:635)
	at org.apache.rocketmq.client.java.impl.ClientImpl.fetchTopicRoute(ClientImpl.java:611)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1556)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.apache.rocketmq.client.java.impl.ClientImpl.startUp(ClientImpl.java:192)
	at org.apache.rocketmq.client.java.impl.producer.ProducerImpl.startUp(ProducerImpl.java:113)
	at org.apache.rocketmq.shaded.com.google.common.util.concurrent.AbstractIdleService$DelegateService$1.run(AbstractIdleService.java:62)
	at org.apache.rocketmq.shaded.com.google.common.util.concurrent.Callables.lambda$threadRenaming$3(Callables.java:103)
	at java.lang.Thread.run(Thread.java:748)

五月 12, 2023 9:29:03 上午 org.apache.rocketmq.shaded.grpc.netty.GrpcSslContexts defaultSslProvider
信息: Jetty ALPN unavailable (this may be normal)
java.lang.ClassNotFoundException: org/eclipse/jetty/alpn/ALPN
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.rocketmq.shaded.grpc.netty.JettyTlsUtil.isJettyAlpnConfigured(JettyTlsUtil.java:64)
	at org.apache.rocketmq.shaded.grpc.netty.GrpcSslContexts.findJdkProvider(GrpcSslContexts.java:254)
	at org.apache.rocketmq.shaded.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:234)
	at org.apache.rocketmq.shaded.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:146)
	at org.apache.rocketmq.shaded.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:95)
	at org.apache.rocketmq.client.java.rpc.RpcClientImpl.<init>(RpcClientImpl.java:82)
	at org.apache.rocketmq.client.java.impl.ClientManagerImpl.getRpcClient(ClientManagerImpl.java:177)
	at org.apache.rocketmq.client.java.impl.ClientManagerImpl.queryRoute(ClientManagerImpl.java:193)
	at org.apache.rocketmq.client.java.impl.ClientImpl.fetchTopicRoute0(ClientImpl.java:635)
	at org.apache.rocketmq.client.java.impl.ClientImpl.fetchTopicRoute(ClientImpl.java:611)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1556)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.apache.rocketmq.client.java.impl.ClientImpl.startUp(ClientImpl.java:192)
	at org.apache.rocketmq.client.java.impl.producer.ProducerImpl.startUp(ProducerImpl.java:113)
	at org.apache.rocketmq.shaded.com.google.common.util.concurrent.AbstractIdleService$DelegateService$1.run(AbstractIdleService.java:62)
	at org.apache.rocketmq.shaded.com.google.common.util.concurrent.Callables.lambda$threadRenaming$3(Callables.java:103)
	at java.lang.Thread.run(Thread.java:748)

Exception in thread "main" java.lang.IllegalStateException: Expected the service ProducerImpl [FAILED] to be RUNNING, but the service has FAILED
	at org.apache.rocketmq.shaded.com.google.common.util.concurrent.AbstractService.checkCurrentState(AbstractService.java:381)
	at org.apache.rocketmq.shaded.com.google.common.util.concurrent.AbstractService.awaitRunning(AbstractService.java:305)
	at org.apache.rocketmq.shaded.com.google.common.util.concurrent.AbstractIdleService.awaitRunning(AbstractIdleService.java:165)
	at org.apache.rocketmq.client.java.impl.producer.ProducerBuilderImpl.build(ProducerBuilderImpl.java:93)
	at com.king.rocketmq.quicstart.ProducerExample.main(ProducerExample.java:30)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Could not find TLS ALPN provider; no working netty-tcnative, Conscrypt, or Jetty NPN/ALPN available
	at org.apache.rocketmq.shaded.com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:588)
	at org.apache.rocketmq.shaded.com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:547)
	at org.apache.rocketmq.shaded.com.google.common.util.concurrent.FluentFuture$TrustedFuture.get(FluentFuture.java:91)
	at org.apache.rocketmq.client.java.impl.ClientImpl.startUp(ClientImpl.java:194)
	at org.apache.rocketmq.client.java.impl.producer.ProducerImpl.startUp(ProducerImpl.java:113)
	at org.apache.rocketmq.shaded.com.google.common.util.concurrent.AbstractIdleService$DelegateService$1.run(AbstractIdleService.java:62)
	at org.apache.rocketmq.shaded.com.google.common.util.concurrent.Callables.lambda$threadRenaming$3(Callables.java:103)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Could not find TLS ALPN provider; no working netty-tcnative, Conscrypt, or Jetty NPN/ALPN available
	at org.apache.rocketmq.shaded.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:246)
	at org.apache.rocketmq.shaded.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:146)
	at org.apache.rocketmq.shaded.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:95)
	at org.apache.rocketmq.client.java.rpc.RpcClientImpl.<init>(RpcClientImpl.java:82)
	at org.apache.rocketmq.client.java.impl.ClientManagerImpl.getRpcClient(ClientManagerImpl.java:177)
	at org.apache.rocketmq.client.java.impl.ClientManagerImpl.queryRoute(ClientManagerImpl.java:193)
	at org.apache.rocketmq.client.java.impl.ClientImpl.fetchTopicRoute0(ClientImpl.java:635)
	at org.apache.rocketmq.client.java.impl.ClientImpl.fetchTopicRoute(ClientImpl.java:611)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1556)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.apache.rocketmq.client.java.impl.ClientImpl.startUp(ClientImpl.java:192)
	... 4 more
Exception in thread "Thread-1" java.lang.IllegalStateException: Expected the service ProducerImpl [FAILED] to be TERMINATED, but the service has FAILED
	at org.apache.rocketmq.shaded.com.google.common.util.concurrent.AbstractService.checkCurrentState(AbstractService.java:381)
	at org.apache.rocketmq.shaded.com.google.common.util.concurrent.AbstractService.awaitTerminated(AbstractService.java:338)
	at org.apache.rocketmq.shaded.com.google.common.util.concurrent.AbstractIdleService.awaitTerminated(AbstractIdleService.java:183)
	at org.apache.rocketmq.client.java.impl.ClientImpl.lambda$new$0(ClientImpl.java:177)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Could not find TLS ALPN provider; no working netty-tcnative, Conscrypt, or Jetty NPN/ALPN available
	at org.apache.rocketmq.shaded.com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:588)
	at org.apache.rocketmq.shaded.com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:547)
	at org.apache.rocketmq.shaded.com.google.common.util.concurrent.FluentFuture$TrustedFuture.get(FluentFuture.java:91)
	at org.apache.rocketmq.client.java.impl.ClientImpl.startUp(ClientImpl.java:194)
	at org.apache.rocketmq.client.java.impl.producer.ProducerImpl.startUp(ProducerImpl.java:113)
	at org.apache.rocketmq.shaded.com.google.common.util.concurrent.AbstractIdleService$DelegateService$1.run(AbstractIdleService.java:62)
	at org.apache.rocketmq.shaded.com.google.common.util.concurrent.Callables.lambda$threadRenaming$3(Callables.java:103)
	... 1 more
Caused by: java.lang.IllegalStateException: Could not find TLS ALPN provider; no working netty-tcnative, Conscrypt, or Jetty NPN/ALPN available
	at org.apache.rocketmq.shaded.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:246)
	at org.apache.rocketmq.shaded.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:146)
	at org.apache.rocketmq.shaded.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:95)
	at org.apache.rocketmq.client.java.rpc.RpcClientImpl.<init>(RpcClientImpl.java:82)
	at org.apache.rocketmq.client.java.impl.ClientManagerImpl.getRpcClient(ClientManagerImpl.java:177)
	at org.apache.rocketmq.client.java.impl.ClientManagerImpl.queryRoute(ClientManagerImpl.java:193)
	at org.apache.rocketmq.client.java.impl.ClientImpl.fetchTopicRoute0(ClientImpl.java:635)
	at org.apache.rocketmq.client.java.impl.ClientImpl.fetchTopicRoute(ClientImpl.java:611)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1556)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.apache.rocketmq.client.java.impl.ClientImpl.startUp(ClientImpl.java:192)
	... 4 more

Process finished with exit code 1

### Steps to Reproduce

run rocketmq client

### What Did You Expect to See?

success

### What Did You See Instead?

success

### Additional Context

1111

**Comment by aaron-ai** [comment]
See https://github.com/apache/rocketmq/issues/6015#issuecomment-1492132106.

**Comment by micsmile** [comment]
![image](https://github.com/apache/rocketmq/assets/66999495/fb95447a-8160-4f9d-8383-96853a5f0ea2)

**Comment by micsmile** [comment]
could not found ClientConfigurationBuilder#enableSsl(false). use jdk11 is ok

**Comment by aaron-ai** [comment]
> could not found ClientConfigurationBuilder#enableSsl(false). use jdk11 is ok

@micsmile Have you ever checked this in the latest client version?
