### ISSUE TITLE
[Bug]Failed to load netty-tcnative; OpenSslEngine will be unavailable, unless the application has already loaded the symbols by some other means.

### ISSUE THREAD

**Issue by charlienss** [apache/rocketmq#6877]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

Centos7

### RocketMQ version

5.1.1

### JDK Version

JDK8

### Describe the Bug

The broker of Rocketmq5.1.1 reported the following error when starting:

DEBUG main - Failed to load netty-tcnative; OpenSslEngine will be unavailable, unless the application has already loaded the symbols by some other means. See https://netty.io/wiki/forked-tomcat-native.html for more information.
java.lang.IllegalArgumentException: Failed to load any of the given libraries: [netty_tcnative_linux_x86_64, netty_tcnative_linux_x86_64_fedora, netty_tcnative_x86_64, netty_tcnative]
        at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:104)
        at io.netty.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:596)
        at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:136)
        at org.apache.rocketmq.remoting.netty.TlsHelper.buildSslContext(TlsHelper.java:97)
        at org.apache.rocketmq.remoting.netty.NettyRemotingServer.loadSslContext(NettyRemotingServer.java:166)
        at org.apache.rocketmq.remoting.netty.NettyRemotingServer.<init>(NettyRemotingServer.java:126)
        at org.apache.rocketmq.broker.BrokerController.initializeRemotingServer(BrokerController.java:422)
        at org.apache.rocketmq.broker.BrokerController.initialize(BrokerController.java:793)
        at org.apache.rocketmq.broker.BrokerStartup.createBrokerController(BrokerStartup.java:240)
        at org.apache.rocketmq.broker.BrokerStartup.main(BrokerStartup.java:50)
        Suppressed: java.lang.UnsatisfiedLinkError: /tmp/libnetty_tcnative_linux_x86_649057233340719808098.so: Error loading shared library libcrypt.so.1: No such file or directory (needed by /tmp/libnetty_tcnative_linux_x86_649057233340719808098.so)
                at java.lang.ClassLoader$NativeLibrary.load(Native Method)
                at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
                at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
                at java.lang.Runtime.load0(Runtime.java:809)
                at java.lang.System.load(System.java:1086)
                at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:36)
                at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:344)
                at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:200)
                at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:96)
                ... 9 common frames omitted
                Suppressed: java.lang.UnsatisfiedLinkError: /tmp/libnetty_tcnative_linux_x86_649057233340719808098.so: Error loading shared library libcrypt.so.1: No such file or directory (needed by /tmp/libnetty_tcnative_linux_x86_649057233340719808098.so)
                        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
                        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
                        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
                        at java.lang.Runtime.load0(Runtime.java:809)
                        at java.lang.System.load(System.java:1086)
                        at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:36)
                        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                        at java.lang.reflect.Method.invoke(Method.java:498)
                        at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:378)
                        at java.security.AccessController.doPrivileged(Native Method)
                        at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:370)
                        at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:336)
                        ... 11 common frames omitted
                Suppressed: java.lang.UnsatisfiedLinkEr

### Steps to Reproduce

The broker of Rocketmq5.1.1 reported the following error when starting:
Failed to load netty tcnative; OpenSslEngine will be unavailable, less the application has already loaded the symbols by some other means

### What Did You Expect to See?

No error message reported

### What Did You See Instead?

The broker of Rocketmq5.1.1 reported the following error when starting:
Failed to load netty tcnative; OpenSslEngine will be unavailable, less the application has already loaded the symbols by some other means

**Comment by fengcharly** [comment]
The issue with the netty version was resolved after netty3.4.0:
https://github.com/netty/netty/issues/12343
