### ISSUE TITLE
[Bug] Proxy Error: org.apache.rocketmq.client.exception.MQBrokerException: CODE: 1  DESC: org.apache.rocketmq.acl.common.AclException: No accessKey is configured, org.apache.rocketmq.acl.plain.PlainPermissionManager.validate(PlainPermissionManager.java:607) BROKER

### ISSUE THREAD

**Issue by fengcharly** [apache/rocketmq#6884]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

Centos 7

### RocketMQ version

5.1.1

### JDK Version

JDK8

### Describe the Bug

After the proxy of Rocketmq5.1.1 is started, the following error is reported:

2023-06-09 15:26:22 WARN RebalanceService - Compute consume offset from last offset exception, mq=MessageQueue [topic=DefaultHeartBeatSyncerTopic, brokerName=rocketmq-standalone-broker-0, queueId=0], exception={}
org.apache.rocketmq.client.exception.MQClientException: Invoke Broker[10.244.134.179:10911] exception
For more information, please visit the url, https://rocketmq.apache.org/docs/bestPractice/06FAQ
        at org.apache.rocketmq.client.impl.MQAdminImpl.maxOffset(MQAdminImpl.java:215)
        at org.apache.rocketmq.client.impl.consumer.RebalancePushImpl.computePullFromWhereWithException(RebalancePushImpl.java:185)
        at org.apache.rocketmq.client.impl.consumer.RebalancePushImpl.computePullFromWhere(RebalancePushImpl.java:158)
        at org.apache.rocketmq.client.impl.consumer.RebalanceImpl.updateProcessQueueTableInRebalance(RebalanceImpl.java:524)
        at org.apache.rocketmq.client.impl.consumer.RebalanceImpl.rebalanceByTopic(RebalanceImpl.java:305)
        at org.apache.rocketmq.client.impl.consumer.RebalanceImpl.doRebalance(RebalanceImpl.java:247)
        at org.apache.rocketmq.client.impl.consumer.DefaultMQPushConsumerImpl.doRebalance(DefaultMQPushConsumerImpl.java:1362)
        at org.apache.rocketmq.client.impl.factory.MQClientInstance.doRebalance(MQClientInstance.java:867)
        at org.apache.rocketmq.client.impl.consumer.RebalanceService.run(RebalanceService.java:41)
        at java.lang.Thread.run(Thread.java:750)
Caused by: org.apache.rocketmq.client.exception.MQBrokerException: CODE: 1  DESC: org.apache.rocketmq.acl.common.AclException: No accessKey is configured, org.apache.rocketmq.acl.plain.PlainPermissionManager.validate(PlainPermissionManager.java:607) BROKER: 10.244.134.179:10911
For more information, please visit the url, https://rocketmq.apache.org/docs/bestPractice/06FAQ
        at org.apache.rocketmq.client.impl.MQClientAPIImpl.getMaxOffset(MQClientAPIImpl.java:1232)
        at org.apache.rocketmq.client.impl.MQAdminImpl.maxOffset(MQAdminImpl.java:213)
        ... 9 common frames omitted

### Steps to Reproduce

After the proxy of Rocketmq5.1.1 is started, the error is reported

### What Did You Expect to See?

Rocketmq5.1.1's proxy starts normally

### What Did You See Instead?

Rocketmq5.1.1's proxy starts not normally

**Comment by drpmma** [comment]
Does the broker open the acl?

**Comment by fengcharly** [comment]
> Does the broker open the acl?

I have enabled ACL, which only appears in the scenario where ACL is enabled
