### ISSUE TITLE
[Bug] IpV6 CANNOT run-through in 5.1+ versions

### ISSUE THREAD

**Issue by leixiaoxiao7** [apache/rocketmq#6923]
### Before Creating the Bug Report

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

### Runtime platform environment

Linux environment

### RocketMQ version

5.1.1

### JDK Version

JDK 1.8.191

### Describe the Bug

I have setup the configurations for both [server] and [broker] (with ipv6) but the service cannot be started. 

### Steps to Reproduce

[namesrv.properties] set below configurations:
listenPort=9876

(run below command):
sh bin/mqnamesrv -c conf/namesrv.properties

[broker.conf] set below configurations:
brokerClusterName = DefaultCluster
brokerName = broker-a
brokerId = 0
namesrvAddr=[2106:440:608::1:0:5cc]:9876
deleteWhen = 04
fileReservedTime = 48
brokerRole = ASYNC_MASTER
flushDiskType = ASYNC_FLUSH
aclEnable=true
autoCreateTopicEnable=false
brokerIP1=2106:440:608::1:0:5cc
listenPort=12012
haListenPort=12013

(run below command): tried both
sh bin/mqbroker -c conf/broker.conf -n 0.0.0.0:9876
sh bin/mqbroker -c conf/broker.conf -n 2106:440:608::1:0:5cc:9876

### What Did You Expect to See?

both [server] and [broker] can properly function

### What Did You See Instead?

[server check]:
^X[root@image-kafka bin]# tail -f ~/logs/rocketmqlogs/namesrv.log
2023-06-20 16:48:21 INFO NSScanScheduledThread - start scanNotActiveBroker
2023-06-20 16:48:26 INFO NSScanScheduledThread - start scanNotActiveBroker
2023-06-20 16:48:28 INFO NSScheduledThread - --------------------------------------------------------
2023-06-20 16:48:28 INFO NSScheduledThread - configTable SIZE: 0
2023-06-20 16:48:31 INFO NSScanScheduledThread - start scanNotActiveBroker
2023-06-20 16:48:36 INFO NSScanScheduledThread - start scanNotActiveBroker
2023-06-20 16:48:41 INFO NSScanScheduledThread - start scanNotActiveBroker
2023-06-20 16:48:46 INFO NSScanScheduledThread - start scanNotActiveBroker

[broker check]:
[root@image-kafka bin]# tail -f ~/logs/rocketmqlogs/proxy.log
2023-06-19 15:59:46 ERROR main - find an unexpect err.
java.lang.RuntimeException: The configuration item NamesrvAddr is not configured
        at org.apache.rocketmq.client.impl.mqclient.MQClientAPIFactory.init(MQClientAPIFactory.java:60)
        at org.apache.rocketmq.client.impl.mqclient.MQClientAPIFactory.<init>(MQClientAPIFactory.java:53)
        at org.apache.rocketmq.proxy.service.LocalServiceManager.<init>(LocalServiceManager.java:71)
        at org.apache.rocketmq.proxy.service.ServiceManagerFactory.createForLocalMode(ServiceManagerFactory.java:28)
        at org.apache.rocketmq.proxy.processor.DefaultMessagingProcessor.createForLocalMode(DefaultMessagingProcessor.java:107)
        at org.apache.rocketmq.proxy.processor.DefaultMessagingProcessor.createForLocalMode(DefaultMessagingProcessor.java:103)
        at org.apache.rocketmq.proxy.ProxyStartup.createMessagingProcessor(ProxyStartup.java:194)
        at org.apache.rocketmq.proxy.ProxyStartup.main(ProxyStartup.java:76)

[the rocketmq service CANNOT run at all]

### Additional Context

Does rocketmq 5.1.+ versions support IPV6 at all? thanks very much.

**Comment by drpmma** [comment]
> The configuration item NamesrvAddr is not configured

It seems that you are using local proxy mode with broker.  You can check the ProxyConfig.
