### ISSUE TITLE
[Bug] Broker+Proxy Message push exception

### ISSUE THREAD

**Issue by Magician-Sun** [apache/rocketmq#6951]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

centos 7.9

### RocketMQ version

branch: rocketmq-5.1.1
commit e244ebb

### JDK Version

java version "1.8.0_261"

### Describe the Bug

|ERROR|com.tianma.gx.mysql.binlog.mq.producer.Rocket5MQProducer:syncSend|88|canal-client-thread|"普通消息发送异常，error={}"|"org.apache.rocketmq.client.java.exception.InternalErrorException: [request-id=5c7933ca-d56f-4690-9720-2976d22da7d9, response-code=50001] org.apache.rocketmq.proxy.common.ProxyException: service not available now. It may be caused by one of the following reasons: the broker's disk is full [CL:  0.44 CQ:  0.44 INDEX:  0.44], messages are put to the slave, message store has been shut down, etc.
        at org.apache.rocketmq.client.java.exception.StatusChecker.check(StatusChecker.java:90)
        at org.apache.rocketmq.client.java.impl.producer.SendReceiptImpl.processResponseInvocation(SendReceiptImpl.java:85)
        at org.apache.rocketmq.client.java.impl.producer.ProducerImpl.lambda$send0$5(ProducerImpl.java:428)
        at org.apache.rocketmq.shaded.com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:221)
        at org.apache.rocketmq.shaded.com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:208)

### Steps to Reproduce

Deploying a controller cluster
Nameserver and controller deployment in the same process
Broker and proxy are deployed in the same process, using the Local mode

Exception when Producer pushes to proxy service bound to broker slave：push failed

### What Did You Expect to See?

SendResult [sendStatus=SEND_OK, msgId=0A64085E326418B4AAC288FAFEE70000, offsetMsgId=C0A815DF00007CA7000000000004639E, messageQueue=MessageQueue [topic=TopicTest, brokerName=broker-a, queueId=5], queueOffset=1]

### What Did You See Instead?

|ERROR|com.tianma.gx.mysql.binlog.mq.producer.Rocket5MQProducer:syncSend|88|canal-client-thread|"普通消息发送异常，error={}"|"org.apache.rocketmq.client.java.exception.InternalErrorException: [request-id=5c7933ca-d56f-4690-9720-2976d22da7d9, response-code=50001] org.apache.rocketmq.proxy.common.ProxyException: service not available now. It may be caused by one of the following reasons: the broker's disk is full [CL:  0.44 CQ:  0.44 INDEX:  0.44], messages are put to the slave, message store has been shut down, etc.
        at org.apache.rocketmq.client.java.exception.StatusChecker.check(StatusChecker.java:90)
        at org.apache.rocketmq.client.java.impl.producer.SendReceiptImpl.processResponseInvocation(SendReceiptImpl.java:85)
        at org.apache.rocketmq.client.java.impl.producer.ProducerImpl.lambda$send0$5(ProducerImpl.java:428)
        at org.apache.rocketmq.shaded.com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:221)
        at org.apache.rocketmq.shaded.com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:208)

**Comment by cdmaji** [comment]
We are also facing the same problem. Do you have any solutions? Or do you have a fix plan?
