### ISSUE TITLE
[Bug] ConsumerLagCalculator#processAllGroup occurred NPE

### ISSUE THREAD

**Issue by fuyou001** [apache/rocketmq#7028]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

all environment

### RocketMQ version

5.x version

### JDK Version

jdk11

### Describe the Bug

Jun 16, 2023 1:31:17 PM io.opentelemetry.sdk.internal.ThrottlingLogger doLog
WARNING: An exception occurred invoking callback for Instrument rocketmq_consumer_lag_messages.
java.lang.NullPointerException
	at java.base/java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at org.apache.rocketmq.broker.topic.TopicConfigManager.selectTopicConfig(TopicConfigManager.java:198)
	at org.apache.rocketmq.broker.metrics.ConsumerLagCalculator.getConsumerLagStats(ConsumerLagCalculator.java:263)
	at org.apache.rocketmq.broker.metrics.ConsumerLagCalculator.lambda$calculateLag$0(ConsumerLagCalculator.java:207)
	at org.apache.rocketmq.broker.metrics.ConsumerLagCalculator.processAllGroup(ConsumerLagCalculator.java:187)
	at org.apache.rocketmq.broker.metrics.ConsumerLagCalculator.calculateLag(ConsumerLagCalculator.java:196)
	at org.apache.rocketmq.broker.metrics.BrokerMetricsManager.lambda$initLagAndDlqMetrics$14(BrokerMetricsManager.java:467)
	at io.opentelemetry.sdk.metrics.AbstractInstrumentBuilder.lambda$registerLongAsynchronousInstrument$1(AbstractInstrumentBuilder.java:98)
	at io.opentelemetry.sdk.metrics.internal.state.CallbackRegistration.invokeCallback(CallbackRegistration.java:97)
	at io.opentelemetry.sdk.metrics.internal.state.MeterSharedState.collectAll(MeterSharedState.java:96)
	at io.opentelemetry.sdk.metrics.SdkMeter.collectAll(SdkMeter.java:67)
	at io.opentelemetry.sdk.metrics.SdkMeterProvider$LeasedMetricProducer.collectAllMetrics(SdkMeterProvider.java:180)
	at io.opentelemetry.sdk.metrics.export.PeriodicMetricReader$Scheduled.doRun(PeriodicMetricReader.java:156)
	at io.opentelemetry.sdk.metrics.export.PeriodicMetricReader$Scheduled.run(PeriodicMetricReader.java:148)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:991)

### Steps to Reproduce

no steps 

### What Did You Expect to See?

no NPE Exception

### What Did You See Instead?

no

**Comment by fuyou001** [comment]
fixed
