### ISSUE TITLE
[Bug] createChannel: create channel exception

### ISSUE THREAD

**Issue by witt-bit** [apache/rocketmq#7101]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

docker 

### RocketMQ version

4.3.0

### JDK Version

jdk 1.8

### Describe the Bug

In the online environment, this log is printed very frequently, but it does not affect our normal use

```java
2023-08-01 15:53:58.915 ERROR [ScheduledThread] [N/A] RocketmqRemoting#error:155 : createChannel: create channel exception
java.lang.ArrayIndexOutOfBoundsException: 1
	at org.apache.rocketmq.remoting.common.RemotingHelper.string2SocketAddress(RemotingHelper.java:57)
	at org.apache.rocketmq.remoting.netty.NettyRemotingClient.createChannel(NettyRemotingClient.java:485)
	at org.apache.rocketmq.remoting.netty.NettyRemotingClient.getAndCreateNameserverChannel(NettyRemotingClient.java:439)
	at org.apache.rocketmq.remoting.netty.NettyRemotingClient.getAndCreateChannel(NettyRemotingClient.java:399)
	at org.apache.rocketmq.remoting.netty.NettyRemotingClient.invokeSync(NettyRemotingClient.java:364)
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.getTopicRouteInfoFromNameServer(MQClientAPIImpl.java:1212)
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.getTopicRouteInfoFromNameServer(MQClientAPIImpl.java:1202)
	at org.apache.rocketmq.client.impl.factory.MQClientInstance.updateTopicRouteInfoFromNameServer(MQClientInstance.java:605)
	at org.apache.rocketmq.client.impl.factory.MQClientInstance.updateTopicRouteInfoFromNameServer(MQClientInstance.java:492)
	at org.apache.rocketmq.client.impl.factory.MQClientInstance.updateTopicRouteInfoFromNameServer(MQClientInstance.java:361)
	at org.apache.rocketmq.client.impl.factory.MQClientInstance$3.run(MQClientInstance.java:278)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2023-08-01 15:53:58.923 ERROR [ScheduledThread] [N/A] RocketmqRemoting#error:155 : createChannel: create channel exception
java.lang.ArrayIndexOutOfBoundsException: 1
	at org.apache.rocketmq.remoting.common.RemotingHelper.string2SocketAddress(RemotingHelper.java:57)
	at org.apache.rocketmq.remoting.netty.NettyRemotingClient.createChannel(NettyRemotingClient.java:485)
	at org.apache.rocketmq.remoting.netty.NettyRemotingClient.getAndCreateNameserverChannel(NettyRemotingClient.java:439)
	at org.apache.rocketmq.remoting.netty.NettyRemotingClient.getAndCreateChannel(NettyRemotingClient.java:399)
	at org.apache.rocketmq.remoting.netty.NettyRemotingClient.invokeSync(NettyRemotingClient.java:364)
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.getTopicRouteInfoFromNameServer(MQClientAPIImpl.java:1212)
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.getTopicRouteInfoFromNameServer(MQClientAPIImpl.java:1202)
	at org.apache.rocketmq.client.impl.factory.MQClientInstance.updateTopicRouteInfoFromNameServer(MQClientInstance.java:605)
	at org.apache.rocketmq.client.impl.factory.MQClientInstance.updateTopicRouteInfoFromNameServer(MQClientInstance.java:492)
	at org.apache.rocketmq.client.impl.factory.MQClientInstance.updateTopicRouteInfoFromNameServer(MQClientInstance.java:361)
	at org.apache.rocketmq.client.impl.factory.MQClientInstance$3.run(MQClientInstance.java:278)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

### Steps to Reproduce

It just happened naturally, I didn't do anything

### What Did You Expect to See?

Hope to solve this problem or can tell me the way to solve this error

### What Did You See Instead?

I checked through the command line arthas tool and found that the calling line parameters are as follows

```java
[arthas@1]$ watch org.apache.rocketmq.remoting.common.RemotingHelper string2SocketAddress "{params}" -x 2 -e 
Press Q or Ctrl+C to abort.
Affect(class count: 1 , method count: 1) cost in 361 ms, listenerId: 1
method=org.apache.rocketmq.remoting.common.RemotingHelper.string2SocketAddress location=AtExceptionExitmethod=org.apache.rocketmq.remoting.common.RemotingHelper.string2SocketAddress location=AtExceptionExit

ts=2023-08-01 16:03:37; [cost=0.078843ms] result=@ArrayList[ts=2023-08-01 16:03:37; [cost=1.327615ms] result=@ArrayList[

    @Object[][
    @Object[][        @String[null],

        @String[null],    ],

    ],]

]
method=org.apache.rocketmq.remoting.common.RemotingHelper.string2SocketAddress location=AtExceptionExit
ts=2023-08-01 16:03:40; [cost=0.094959ms] result=@ArrayList[
    @Object[][
        @String[null],
    ],
]
method=org.apache.rocketmq.remoting.common.RemotingHelper.string2SocketAddress location=AtExceptionExit
ts=2023-08-01 16:03:40; [cost=0.078543ms] result=@ArrayList[
    @Object[][
        @String[null],
    ],
]
```

The call is traced up as follows

```java
[arthas@1]$ watch org.apache.rocketmq.client.impl.MQClientAPIImpl getTopicRouteInfoFromNameServer "{params}" -x 2 -e 
Press Q or Ctrl+C to abort.
Affect(class count: 1 , method count: 2) cost in 409 ms, listenerId: 2
method=org.apache.rocketmq.client.impl.MQClientAPIImpl.getTopicRouteInfoFromNameServer location=AtExceptionExit
ts=2023-08-01 16:06:04; [cost=0.838545ms] result=@ArrayList[
    @Object[][
        @String[TBW102],
        @Long[3000],
        @Boolean[true],
    ],
]
method=org.apache.rocketmq.client.impl.MQClientAPIImpl.getTopicRouteInfoFromNameServer location=AtExceptionExit
ts=2023-08-01 16:06:04; [cost=3.419284ms] result=@ArrayList[
    @Object[][
        @String[TBW102],
        @Long[3000],
    ],
]
method=org.apache.rocketmq.client.impl.MQClientAPIImpl.getTopicRouteInfoFromNameServer location=AtExceptionExit
ts=2023-08-01 16:06:04; [cost=0.223639ms] result=@ArrayList[
    @Object[][
        @String[TBW102],
        @Long[3000],
        @Boolean[true],
    ],
]

```

Hope this information is helpful to you

**Comment by leizhiyuan** [comment]
maybe you can update the newer client version and test again
