### ISSUE TITLE
at org.apache.rocketmq.proxy.grpc.v2.channel.GrpcClientChannel.processGetConsumerRunningInfo(GrpcClientChannel.java:213)

### ISSUE THREAD

**Issue by weihubeats** [apache/rocketmq#7199]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

Ubuntu 22.04.2 LTS

### RocketMQ version

5.1.0

### JDK Version

1.8

### Describe the Bug

2023-08-17 10:18:51 ERROR AdminBrokerThread_7 - process failed. msg:RemotingCommand [code=307, language=JAVA, version=433, opaque=1051433444, flag(B)=0, remark=null, extFields={clientId=ip-10-11-11-1@1962523@54@gnt74v0lis, jstackEnable=false, consumerGroup=test_topic}, serializeTypeCurrentRPC=JSON]
java.lang.NullPointerException: null
        at org.apache.rocketmq.proxy.grpc.v2.channel.GrpcClientChannel.processGetConsumerRunningInfo(GrpcClientChannel.java:213)
        at org.apache.rocketmq.proxy.service.relay.ProxyChannel.writeAndFlush(ProxyChannel.java:97)
        at org.apache.rocketmq.remoting.netty.NettyRemotingAbstract.invokeSyncImpl(NettyRemotingAbstract.java:476)
        at org.apache.rocketmq.remoting.netty.NettyRemotingServer.invokeSync(NettyRemotingServer.java:438)
        at org.apache.rocketmq.broker.client.net.Broker2Client.callClient(Broker2Client.java:80)
        at org.apache.rocketmq.broker.processor.AdminBrokerProcessor.callConsumer(AdminBrokerProcessor.java:2347)
        at org.apache.rocketmq.broker.processor.AdminBrokerProcessor.getConsumerRunningInfo(AdminBrokerProcessor.java:1979)
        at org.apache.rocketmq.broker.processor.AdminBrokerProcessor.processRequest(AdminBrokerProcessor.java:278)
        at org.apache.rocketmq.remoting.netty.NettyRemotingAbstract.lambda$buildProcessRequestHandler$1(NettyRemotingAbstract.java:312)
        at org.apache.rocketmq.remoting.netty.RequestTask.run(RequestTask.java:80)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)

### Steps to Reproduce

no

### What Did You Expect to See?

no error

### What Did You See Instead?

no

**Comment by weihubeats** [comment]
Can anyone help merge the pr associated with this issue?
