### ISSUE TITLE
[Bug] Failed to write response[request code: 60, response code: 0, opaque: 8154] to channel[id: 0x675d9a9f, L:/192.168.1.40:30909 ! R:/192.168.1.42:45266] io.netty.channel.StacklessClosedChannelException: null

### ISSUE THREAD

**Issue by weihubeats** [apache/rocketmq#7243]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

Ubuntu 22.04.2 LTS

### RocketMQ version

5.1.0

### JDK Version

1.8

### Describe the Bug
- server
```java
Failed to write response[request code: 60, response code: 0, opaque: 8154] to channel[id: 0x675d9a9f, L:/192.168.1.40:30909 ! R:/192.168.1.42:45266]
io.netty.channel.StacklessClosedChannelException: null
        at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)
2023-08-24 14:35:38 INFO NettyServerCodecThread_9 - NETTY SERVER PIPELINE: channelInactive, the channel[192.168.1.42:23046]
2023-08-24 14:35:38 INFO NettyServerCodecThread_9 - NETTY SERVER PIPELINE: channelUnregistered, the channel[192.168.1.42:23046]
2023-08-24 14:35:38 INFO NettyServerCodecThread_10 - NETTY SERVER PIPELINE: channelRegistered 192.168.1.42:23050
2023-08-24 14:35:38 INFO NettyServerCodecThread_10 - NETTY SERVER PIPELINE: channelActive, the channel[192.168.1.42:23050]
2023-08-24 14:35:38 ERROR NettyServerEPOLLSelector_5_3 - Failed to write response[request code: 21, response code: 0, opaque: 8176] to channel[id: 0x102f41a0, L:/192.168.1.40:30909 ! R:/192.168.1.42:45278]
io.netty.channel.StacklessClosedChannelException: null
        at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)
2023-08-24 14:35:41 INFO NettyServerCodecThread_10 - NETTY SERVER PIPELINE: channelInactive, the channel[192.168.1.42:23050]
2023-08-24 14:35:41 INFO NettyServerCodecThread_10 - NETTY SERVER PIPELINE: channelUnregistered, the channel[192.168.1.42:23050]
2023-08-24 14:35:41 INFO NettyServerCodecThread_2 - NETTY SERVER PIPELINE: channelRegistered 192.168.1.42:55430
2023-08-24 14:35:41 INFO NettyServerCodecThread_2 - NETTY SERVER PIPELINE: channelActive, the channel[192.168.1.42:55430]
2023-08-24 14:35:43 ERROR NettyServerEPOLLSelector_5_2 - Failed to write response[request code: 43, response code: 0, opaque: 8190] to channel[id: 0xa079b68e, L:/192.168.1.40:30911 ! R:/192.168.1.42:34376]
io.netty.channel.StacklessClosedChannelException: null
```
- client
```java
2023-08-24 15:20:42 ERROR BrokerControllerScheduledThread1 - SyncSubscriptionGroup Exception, 192.101.10.41:30911
org.apache.rocketmq.remoting.exception.RemotingTimeoutException: wait response on the channel <192.101.10.41:30909> timeout, 2999(ms)
        at org.apache.rocketmq.remoting.netty.NettyRemotingAbstract.invokeSyncImpl(NettyRemotingAbstract.java:493)
        at org.apache.rocketmq.remoting.netty.NettyRemotingClient.invokeSync(NettyRemotingClient.java:565)
        at org.apache.rocketmq.broker.out.BrokerOuterAPI.getTimerCheckPoint(BrokerOuterAPI.java:703)
        at org.apache.rocketmq.broker.slave.SlaveSynchronize.syncTimerCheckPoint(SlaveSynchronize.java:194)
        at org.apache.rocketmq.broker.controller.ReplicasManager.lambda$handleSlaveSynchronize$3(ReplicasManager.java:285)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
```

### Steps to Reproduce

no

### What Did You Expect to See?

no timeout

### What Did You See Instead?

time out

**Comment by weihubeats** [comment]
Something like this https://github.com/apache/rocketmq/issues/3726

**Comment by weihubeats** [comment]
I run the following command on the master broker again to make sure there are no network delays
```
. /mqadmin getBrokerConfig -n 192.156.1.1:9876 -b 192.101.12.42:30911
···

I find that the broker immediately prints 
```
NETTY SERVER PIPELINE: channelRegistered 192.168.1.1
```

But it took a few minutes to print
```
ERROR NettyServerEPOLLSelector_5_3 - Failed to write response[request code
```

**Comment by weihubeats** [comment]
@RongtongJin Can you help me with this?

**Comment by qianghong000** [comment]
我也遇到了

**Comment by luoye783** [comment]
i meet the question too. May I ask how you solved it.

**Comment by 15874959295** [comment]
i meet the question too. May I ask how you solved it.
