### ISSUE TITLE
jna--934747322/jna13951917643251975730.tmp, 0x0001): tried: '/private/var/folders/nv/z8ncdq6n6ngf1nqfsq4hrkk80000gn/T/jna--934747322/jna13951917643251975730.tmp' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64e'))

### ISSUE THREAD

**Issue by Guohaonan1** [apache/rocketmq#7292]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

macOS12.4 m1

### RocketMQ version

5.1.2|5.1.3

### JDK Version

zulujdk 17.0.8

### Describe the Bug

in `macOS M1 arm64` environment
`rocketMQ 5.1.2`和`rocketMQ 5.1.3` broker start fail, and log report below

```
java.lang.UnsatisfiedLinkError: /private/var/folders/nv/z8ncdq6n6ngf1nqfsq4hrkk80000gn/T/jna--934747322/jna13951917643251975730.tmp: dlopen(/private/var/folders/nv/z8ncdq6n6ngf1nqfsq4hrkk80000gn/T/jna--934747322/jna13951917643251975730.tmp, 0x0001): tried: '/private/var/folders/nv/z8ncdq6n6ngf1nqfsq4hrkk80000gn/T/jna--934747322/jna13951917643251975730.tmp' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64e'))
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2394)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1953)
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:851)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:826)
	at com.sun.jna.Native.<clinit>(Native.java:140)
	at org.apache.rocketmq.store.util.LibC.<clinit>(LibC.java:26)
	at org.apache.rocketmq.store.CommitLog$ColdDataCheckService.initPageSize(CommitLog.java:2188)
	at org.apache.rocketmq.store.CommitLog$ColdDataCheckService.<init>(CommitLog.java:2071)
	at org.apache.rocketmq.store.CommitLog.<init>(CommitLog.java:112)
	at org.apache.rocketmq.store.DefaultMessageStore.<init>(DefaultMessageStore.java:221)
	at org.apache.rocketmq.broker.BrokerController.initializeMessageStore(BrokerController.java:749)
	at org.apache.rocketmq.broker.BrokerController.initialize(BrokerController.java:786)
	at org.apache.rocketmq.broker.BrokerStartup.createBrokerController(BrokerStartup.java:240)
	at org.apache.rocketmq.broker.BrokerStartup.main(BrokerStartup.java:50)
```
`rocketMQ 5.1.1` broker start success
i suppose it may be caused by a new part which use jna, as i know, jna support m1(arch64) start from jna5.7 ,but in project use 4.2.2, but i check 4,9,3 version , it also use 4.2.2, so i dont konw the real reason

### Steps to Reproduce

download bin from https://rocketmq.apache.org/zh/download

unzip and cd to the folder, use the command
`nohup sh bin/mqbroker -n localhost:9876 &`

### What Did You Expect to See?

in log
`The broker[xx,xx] boot success. serializeType=JSON and name server is localhost:9876`

### What Did You See Instead?

`[1]  + exit 255   nohup sh bin/mqbroker -n localhost:9876 --enable-proxy`

**Comment by RongtongJin** [comment]
Fix in #7014
