### ISSUE TITLE
[Bug] report 'PullMessageService - Pull Message Service Run Method exception' in the log, and found  some queue  do not consume in rocketmq dashboard, 

### ISSUE THREAD

**Issue by L-xiaohai** [apache/rocketmq#7538]
### Before Creating the Bug Report

- [ ] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

NAME="Rocky Linux"
VERSION="8.6 (Green Obsidian)"

### RocketMQ version

rocketmq client version 5.1.4

### JDK Version

openjdk version "1.8.0_302"
OpenJDK Runtime Environment (Zulu 8.56.0.21-CA-linux64) (build 1.8.0_302-b08)
OpenJDK 64-Bit Server VM (Zulu 8.56.0.21-CA-linux64) (build 25.302-b08, mixed mode)

### Describe the Bug

now project use DefaultMQPushConsumer method poll message,
when report PullMessageService error, ProcessQueue stop poll message.
review code, due to trigger cached message size limiting, pullRequest should execute later, and print 'so do flow control' in the log, but msgTreeMap has no element, msgTreeMap of msgbody size don't add up to more than cached message size of limiting

### Steps to Reproduce

indetermination，project need to use rocketmq to delivery message to other project, when receive messge in A topic, message will follows a certain logic to delivery other topic in other thread pool
first, create two topic with 16 queue 
second, receiving message modify topic value to delivery message to other topic

### What Did You Expect to See?

![image](https://github.com/apache/rocketmq/assets/61721102/eccac75f-7c9b-4347-a261-86b481eaccb1)

2023-11-04 11:09:30,671 [PullMessageService] ERROR      PullMessageService - Pull Message Service Run Method exception
java.util.NoSuchElementException: null
        at java.util.TreeMap.key(TreeMap.java:1327)
        at java.util.TreeMap.firstKey(TreeMap.java:290)
        at org.apache.rocketmq.client.impl.consumer.DefaultMQPushConsumerImpl.pullMessage(DefaultMQPushConsumerImpl.java:286)
        at org.apache.rocketmq.client.impl.consumer.PullMessageService.pullMessage(PullMessageService.java:101)
        at org.apache.rocketmq.client.impl.consumer.PullMessageService.run(PullMessageService.java:127)
        at java.lang.Thread.run(Thread.java:748)

### What Did You See Instead?

nothing

**Comment by L-xiaohai** [comment]
rocketmq dashboard
![image](https://github.com/apache/rocketmq/assets/61721102/6cf7684e-e205-4c36-b311-6cf8b0045ba9)

**Comment by humkum** [comment]
What do you mean? Please describe more details for this question.

**Comment by L-xiaohai** [comment]
> What do you mean? Please describe more details for this question.
In the actual production environment, when the tps pressure is relatively high, the msgtreemap data is empty, but the message size limit is triggered, and the line of code that prints logs reports an error

**Comment by L-xiaohai** [comment]
stop comsume topic queue

![image](https://github.com/apache/rocketmq/assets/61721102/c2641212-165c-43ec-a08b-126630ee51ca)

2023-11-16 10:01:05.263 [RebalanceService] INFO       RebalanceImpl - %RETRY%vip2_node_client_to_wechat_center Rebalance changed, also update version: 1700100065163, 1700100065263
2023-11-16 10:01:05.263 [NettyClientPublicExecutor_8] INFO       ClientRemotingProcessor - receive broker's notification[192.168.206.222:10811], the consumer group: vip2_site_wechat_to_client_center changed, rebalance immediately
2023-11-16 10:01:05.264 [NettyClientPublicExecutor_4] INFO       ClientRemotingProcessor - receive broker's notification[192.168.206.221:10811], the consumer group: vip2_site_wechat_to_client_center changed, rebalance immediately
2023-11-16 10:01:05.264 [NettyClientPublicExecutor_1] INFO       ClientRemotingProcessor - receive broker's notification[192.168.206.222:10911], the consumer group: vip2_site_wechat_to_client_center changed, rebalance immediately
2023-11-16 10:01:05.265 [NettyClientPublicExecutor_6] INFO       ClientRemotingProcessor - receive broker's notification[192.168.206.221:10911], the consumer group: vip2_site_wechat_to_client_center changed, rebalance immediately
2023-11-16 10:01:05.660 [PullMessageService] INFO       DefaultMQPushConsumerImpl - the pull request[PullRequest [consumerGroup=vip2_node_client_to_wechat_center, messageQueue=MessageQueue [topic=%RETRY%vip2_node_client_to_wechat_center
, brokerName=yjy-broker-n1, queueId=0], nextOffset=0]] is dropped.
2023-11-16 10:01:06.124 [NettyClientSelector_1] DEBUG      RocketmqRemoting - Response[request code: 307, response code: 0, opaque: 876426720] is written to channel[id: 0x489bbabb, L:/192.168.206.150:60008 - R:/192.168.206.222:10811]
2023-11-16 10:01:06.326 [PullMessageService] ERROR      PullMessageService - Pull Message Service Run Method exception
java.util.NoSuchElementException: null
        at java.util.TreeMap.key(TreeMap.java:1327)
        at java.util.TreeMap.firstKey(TreeMap.java:290)
        at org.apache.rocketmq.client.impl.consumer.DefaultMQPushConsumerImpl.pullMessage(DefaultMQPushConsumerImpl.java:286)

**Comment by yuz10** [comment]
Please check the consumer code, don't modify message body in consumer callback, for example:
```
consumer.registerMessageListener((MessageListenerConcurrently) (msgs, context) -> {
            msgs.get(0).setBody(new byte[0]);
            return ConsumeConcurrentlyStatus.CONSUME_SUCCESS;
        });
```
the msgSize will be wrong in processqueue,  and pull will be ratelimted forever
