### ISSUE TITLE
[Bug] An unstable unit test:  ConcurrentHashMapUtilsTest.computeIfAbsent

### ISSUE THREAD

**Issue by yp969803** [apache/rocketmq#7590]
### Before Creating the Bug Report

- [x] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

ubuntu 20.04

### RocketMQ version

develop

### Describe the Bug

failed detail : 
```
java.lang.IllegalStateException: Recursive update
	at org.apache.rocketmq.common.utils.ConcurrentHashMapUtilsTest.lambda$3(ConcurrentHashMapUtilsTest.java:39)
	at org.apache.rocketmq.common.utils.ConcurrentHashMapUtilsTest.computeIfAbsent(ConcurrentHashMapUtilsTest.java:39)
```

### Steps to Reproduce

by running

```
mvn test
```

### What Did You Expect to See?

Test should pass

### What Did You See Instead?

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project rocketmq-common: There are test failures.

```

**Comment by yp969803** [comment]
#asign
