### ISSUE TITLE
[Bug] Timed messages cannot be consumed

### ISSUE THREAD

**Issue by zyhui98** [apache/rocketmq#7641]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

CentOS 7.6 

### RocketMQ version

5.1.4

### JDK Version

1.8.0_66

### Describe the Bug

2023-12-12 00:25:46 ERROR TimerEnqueueGetService - Unknown exception in enqueuing
java.lang.IllegalArgumentException: null
        at java.nio.Buffer.limit(Buffer.java:275)
        at org.apache.rocketmq.store.timer.TimerMessageStore.getMessageByCommitOffset(TimerMessageStore.java:1013)
        at org.apache.rocketmq.store.timer.TimerMessageStore.enqueue(TimerMessageStore.java:652)
        at org.apache.rocketmq.store.timer.TimerMessageStore$TimerEnqueueGetService.run(TimerMessageStore.java:1269)
        at java.lang.Thread.run(Thread.java:745)

### Steps to Reproduce

发送消息必现，有两台broke，有一台正常

### What Did You Expect to See?

normal consume message

### What Did You See Instead?

not stored message

### Additional Context

2023-12-12 00:25:46 ERROR TimerEnqueueGetService - Unknown exception in enqueuing
java.lang.IllegalArgumentException: null
        at java.nio.Buffer.limit(Buffer.java:275)
        at org.apache.rocketmq.store.timer.TimerMessageStore.getMessageByCommitOffset(TimerMessageStore.java:1013)
        at org.apache.rocketmq.store.timer.TimerMessageStore.enqueue(TimerMessageStore.java:652)
        at org.apache.rocketmq.store.timer.TimerMessageStore$TimerEnqueueGetService.run(TimerMessageStore.java:1269)
        at java.lang.Thread.run(Thread.java:745)

**Comment by GenerousMan** [comment]
两个broker收发普通消息都正常吗？只有定时消息有问题嘛？

**Comment by zyhui98** [comment]
是消息太大超过我们的maxMessageSize配置的64kb，轮转不了。
