### ISSUE TITLE
acl set globalWhiteRemoteAddresses with '.' broker init fail

### ISSUE THREAD

**Issue by jackxu2011** [apache/rocketmq#771]
The issue tracker is **ONLY** used for bug report(feature request need to follow [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal)). Keep in mind, please check whether there is an existing same report before your raise a new one.

Alternately (especially if your communication is not a bug report), you can send mail to our [mailing lists](http://rocketmq.apache.org/about/contact/). We welcome any friendly suggestions, bug fixes, collaboration and other improvements.

Please ensure that your bug report is clear and that it is complete. Otherwise, we may be unable to understand it or to reproduce it, either of which would prevent us from fixing the bug. We strongly recommend the report(bug report or feature request) could include some hints as the following:

**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
set the globalWhiteRemoteAddresses property with value  192.168.\*.\*
- What did you expect to see?
broker startup
- What did you see instead?
``` java
exception: java.lang.ClassCastException: java.lang.Class cannot be cast to org.apache.rocketmq.acl.AccessValidator
```
and get
``` java 
 2019-02-15 09:19:45 ERROR main - Unable to init service.
com.alibaba.fastjson.JSONException: not close json text, token : .
        at com.alibaba.fastjson.parser.DefaultJSONParser.close(DefaultJSONParser.java:1493) ~[fastjson-1.2.51.jar:na]
        at com.alibaba.fastjson.JSON.parse(JSON.java:159) ~[fastjson-1.2.51.jar:na]
        at com.alibaba.fastjson.JSON.parse(JSON.java:165) ~[fastjson-1.2.51.jar:na]
        at com.alibaba.fastjson.JSON.parse(JSON.java:134) ~[fastjson-1.2.51.jar:na]
        at com.alibaba.fastjson.JSONObject.getJSONArray(JSONObject.java:135) ~[fastjson-1.2.51.jar:na]
        at org.apache.rocketmq.acl.plain.PlainPermissionLoader.load(PlainPermissionLoader.java:75) ~[rocketmq-acl-4.4.0.jar:4.4.0]
        at org.apache.rocketmq.acl.plain.PlainPermissionLoader.<init>(PlainPermissionLoader.java:59) ~[rocketmq-acl-4.4.0.jar:4.4.0]
        at org.apache.rocketmq.acl.plain.PlainAccessValidator.<init>(PlainAccessValidator.java:44) ~[rocketmq-acl-4.4.0.jar:4.4.0]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_181]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_181]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_181]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_181]
        at java.lang.Class.newInstance(Class.java:442) ~[na:1.8.0_181]
        at org.apache.rocketmq.broker.util.ServiceProvider.initService(ServiceProvider.java:176) [rocketmq-broker-4.4.0.jar:4.4.0]
        at org.apache.rocketmq.broker.util.ServiceProvider.load(ServiceProvider.java:119) [rocketmq-broker-4.4.0.jar:4.4.0]
        at org.apache.rocketmq.broker.BrokerController.initialAcl(BrokerController.java:500) [rocketmq-broker-4.4.0.jar:4.4.0]
        at org.apache.rocketmq.broker.BrokerController.initialize(BrokerController.java:473) [rocketmq-broker-4.4.0.jar:4.4.0]
        at org.apache.rocketmq.broker.BrokerStartup.createBrokerController(BrokerStartup.java:218) [rocketmq-broker-4.4.0.jar:4.4.0]
        at org.apache.rocketmq.broker.BrokerStartup.main(BrokerStartup.java:58) [rocketmq-broker-4.4.0.jar:4.4.0]
```
2. Please tell us about your environment:
CentOS Linux release 7.3.1611  内核 3.10.0-514.el7.x86_64
java version "1.8.0_181"

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

yaml配置文件
```yaml

globalWhiteRemoteAddresses: 192.168.*.*

accounts:
- accessKey: RocketMQ
  secretKey: 12345678
  whiteRemoteAddress: 
  admin: false
  defaultTopicPerm: DENY
  defaultGroupPerm: SUB
  topicPerms:
  - topicA=DENY
  - topicB=PUB|SUB
  - topicC=SUB
  groupPerms:
  # the group should convert to retry topic
  - groupA=DENY
  - groupB=PUB|SUB
  - groupC=SUB

- accessKey: rocketmq2
  secretKey: 12345678
  whiteRemoteAddress: 
  # if it is admin, it could access all resources
  admin: true
```

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by zongtanghu** [comment]
Okay,I will reconfirm in my cluster enviroment. @jackxu2011

**Comment by zongtanghu** [comment]
We look at you yaml config file,you globalWhiteRemoteAddresses formate is wrong.The right globalWhiteRemoteAddresses  formate is as follows:

globalWhiteRemoteAddresses:
- 10.10.103.*
- 192.168.0.*

accounts:
- accessKey: RocketMQ
  secretKey: 12345678
  whiteRemoteAddress: 192.168.0.*
  admin: false
  defaultTopicPerm: DENY
  defaultGroupPerm: SUB
  topicPerms:
  - topicA=DENY
  - topicB=PUB|SUB
  - topicC=SUB
  groupPerms:
  # the group should convert to retry topic
  - groupA=DENY
  - groupB=SUB
  - groupC=SUB

- accessKey: rocketmq2
  secretKey: 12345678
  whiteRemoteAddress: 192.168.1.*
  # if it is admin, it could access all resources
  admin: true
