### ISSUE TITLE
[Bug] can not get consumerStatus

### ISSUE THREAD

**Issue by Jinduoxia666** [apache/rocketmq#7728]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

macos sonoma 14.2.1

### RocketMQ version

5.1.4

### JDK Version

openjdk 8

### Describe the Bug

org.apache.rocketmq.client.exception.MQClientException: CODE: 1  DESC: invoke consumer <GID_jdx> <jinduoxiadeMacBook-Pro.local@5751@2@5vp8vpbzq> Exception: org.apache.rocketmq.remoting.exception.RemotingSendRequestException: send request to <192.168.2.7:58210> failed, org.apache.rocketmq.remoting.netty.NettyRemotingAbstract.invokeSyncImpl(NettyRemotingAbstract.java:496)
For more information, please visit the url, https://rocketmq.apache.org/docs/bestPractice/06FAQ
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.getConsumerRunningInfo(MQClientAPIImpl.java:2618)
	at org.apache.rocketmq.tools.admin.DefaultMQAdminExtImpl.getConsumerRunningInfo(DefaultMQAdminExtImpl.java:1312)
	at org.apache.rocketmq.tools.admin.DefaultMQAdminExtImpl.getConsumerRunningInfo(DefaultMQAdminExtImpl.java:1299)
	at org.apache.rocketmq.tools.admin.DefaultMQAdminExt.getConsumerRunningInfo(DefaultMQAdminExt.java:580)
	at org.apache.rocketmq.tools.command.consumer.ConsumerStatusSubCommand.execute(ConsumerStatusSubCommand.java:103)
	at org.apache.rocketmq.tools.command.MQAdminStartup.main0(MQAdminStartup.java:165)
	at org.apache.rocketmq.tools.command.MQAdminStartup.main(MQAdminStartup.java:115)

### Steps to Reproduce

the proxy also report a Excetion
ERROR AdminBrokerThread_9 - process failed. msg:RemotingCommand [code=307, language=JAVA, version=441, opaque=3843, flag(B)=0, remark=null, extFields={clientId=jinduoxiadeMacBook-Pro.local@5751@1@5voc0573e, Signature=0ISOzhT8nbdxUPN+6dsrJrOHtK0=, jstackEnable=false, AccessKey=rocketmq2, consumerGroup=GID_jdx}, serializeTypeCurrentRPC=JSON]
java.lang.NullPointerException: null
	at org.apache.rocketmq.proxy.grpc.v2.channel.GrpcClientChannel.processGetConsumerRunningInfo(GrpcClientChannel.java:213)
	at org.apache.rocketmq.proxy.service.relay.ProxyChannel.writeAndFlush(ProxyChannel.java:97)
	at org.apache.rocketmq.remoting.netty.NettyRemotingAbstract.invokeSyncImpl(NettyRemotingAbstract.java:477)
	at org.apache.rocketmq.remoting.netty.NettyRemotingServer.invokeSync(NettyRemotingServer.java:383)
	at org.apache.rocketmq.broker.client.net.Broker2Client.callClient(Broker2Client.java:80)
	at org.apache.rocketmq.broker.processor.AdminBrokerProcessor.callConsumer(AdminBrokerProcessor.java:2484)

### What Did You Expect to See?

get the correct consumerStatus

### What Did You See Instead?

the Exception

### Additional Context

no

**Comment by Jinduoxia666** [comment]
i try openjdk21,also report this Exception

**Comment by leizhiyuan** [comment]
you use grpc client ? and proxy+broker deploy mode?

**Comment by Jinduoxia666** [comment]
> you use grpc client ? and proxy+broker deploy mode?

yeah,i guess that the grpc client have some problems.
