### ISSUE TITLE
[Bug] RemotingTooMuchRequestException: sendDefaultImpl call timeout 

### ISSUE THREAD

**Issue by lijie123bes** [apache/rocketmq#7883]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

centos7.9

### RocketMQ version

4.3.1

### Describe the Bug

org.apache.rocketmq.remoting.exception.RemotingTooMuchRequestException: sendDefaultImpl call timeout at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendDefaultImpl(DefaultMQProducerImpl.java:612) ~[rocketmq-client-4.3.1.jar:4.3.1] at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1253) ~[rocketmq-client-4.3.1.jar:4.3.1] at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1203) ~[rocketmq-client-4.3.1.jar:4.3.1] at org.apache.rocketmq.client.producer.DefaultMQProducer.send(DefaultMQProducer.java:214) ~[rocketmq-client-4.3.1.jar:4.3.1]

### Steps to Reproduce

[NettyClientSelector_1] INFO RocketmqRemoting.info (Slf4jLoggerFactory.java:95) closeChannel: close the connection to remote address[] result: true

### What Did You Expect to See?

connect normally

### What Did You See Instead?

RemotingTooMuchRequestException

**Comment by leizhiyuan** [comment]
need more logs. There are many possible reasons for this issue, such as slow server processing or client-side garbage collection.
