### ISSUE TITLE
[Bug]使用5.2.0开启acl功能 为什么rocketmq2这个accessKey删除后，执行命令就报错

### ISSUE THREAD

**Issue by 1195952223** [apache/rocketmq#8120]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

Linux test-ProLiant-DL388-Gen10 5.4.0-150-generic #167~18.04.1-Ubuntu SMP Wed May 24 00:51:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### RocketMQ version

5.2.0

### JDK Version

1.8

### Describe the Bug

使用5.2.0开启acl功能 为什么rocketmq2这个accessKey删除后，执行命令就报错

### Steps to Reproduce

account's accessKey is:rocketmq2root@hp:/home/bk/rocketmq/rocketmq-all-5.2.0-bin-release# ./bin/mqadmin deleteAccessConfig -n xxxxxx -c DefaultCluster -a admfcvv
org.apache.rocketmq.tools.command.SubCommandException: DeleteAccessConfigSubCommand command failed
	at org.apache.rocketmq.tools.command.acl.DeleteAccessConfigSubCommand.execute(DeleteAccessConfigSubCommand.java:107)
	at org.apache.rocketmq.tools.command.MQAdminStartup.main0(MQAdminStartup.java:164)
	at org.apache.rocketmq.tools.command.MQAdminStartup.main(MQAdminStartup.java:114)
Caused by: org.apache.rocketmq.client.exception.MQClientException: CODE: 1  DESC: org.apache.rocketmq.acl.common.AclException: No acl config for rocketmq2, org.apache.rocketmq.acl.plain.PlainPermissionManager.validate(PlainPermissionManager.java:613)
For more information, please visit the url, https://rocketmq.apache.org/docs/bestPractice/06FAQ
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.deleteAccessConfig(MQClientAPIImpl.java:467)
	at org.apache.rocketmq.tools.admin.DefaultMQAdminExtImpl.deletePlainAccessConfig(DefaultMQAdminExtImpl.java:285)
	at org.apache.rocketmq.tools.admin.DefaultMQAdminExt.deletePlainAccessConfig(DefaultMQAdminExt.java:211)
	at org.apache.rocketmq.tools.command.acl.DeleteAccessConfigSubCommand.execute(DeleteAccessConfigSubCommand.java:97)
	... 2 more

### What Did You Expect to See?

能修改或删除

### What Did You See Instead?

能修改或删除

**Comment by TickFairy** [comment]
我看conf/tool.yml 配置了这个用户 ，应该是能改的吧

**Comment by 1195952223** [comment]
看到了 谢谢
