### ISSUE TITLE
4.4.0 version No route info problem

### ISSUE THREAD

**Issue by toto1297488504** [apache/rocketmq#816]
使用官网rocketmq远程调用rocketmq4.4，出现错误（只有sync的正常），将版本jar包依赖都换成4.2的rocketmq,相同代码所有的都正常了

错误现象：
Exception in thread "main" org.apache.rocketmq.client.exception.MQClientException: No route info of this topic, TopicTest
See http://rocketmq.apache.org/docs/faq/ for further details.
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendDefaultImpl(DefaultMQProducerImpl.java:564)
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:420)
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:414)
	at org.apache.rocketmq.client.producer.DefaultMQProducer.send(DefaultMQProducer.java:255)
	at AsyncProducer.main(AsyncProducer.java:29)

尝试过程：
1、关闭远程Rocketmq4.4所在机器的防火墙
2、设置topic权限为6
3、安装在windows下，分别尝试4.3，4.4，4.2版本（安装方式：https://www.jianshu.com/p/4a275e779afa），最终发现只有4.2版本正常。
4、修改远程Centos7下的rocketmq /bin/ runbroker.sh中的内存大小
5、使用rocketmq-console 管理和监控过程。（另外，rocketmq-console中的源码要修改rocketmq的jar版本为正式release的版本，而不是githup中的版本才可以正常运行rocketmq-console）

**Comment by zongtanghu** [comment]
Firstly,you should put forward the issue as rocketmq template.Thank you. @toto1297488504

**Comment by ymwneu** [comment]
1. 提issue的时候注意一下规范，参照rocketmq template；
2. 提问请在官方邮件列表中提；
3. 根据你的问题描述，不好判断哪里有问题，我在自己电脑上也无法重现你的问题。报No route info of this topic错误时，先看rocketmq_client.log，看里面是否有更多的报错信息。请求nameserver的过程中，如果有网络问题，也可能会报no route info。如果日志中也不能排查到问题，建议可以在本地跑一下example包下的org.apache.rocketmq.example.quickstart.Producer，然后调试一下，client端代码不多，可以很快走到抛错的地方，确认问题。

**Comment by zongtanghu** [comment]
As mentioned above,the code of client is not complex，you can debug the client module and will find detail reason.@toto1297488504
