### ISSUE TITLE
After boker turns on acl verification, docker compose cannot start proxy

### ISSUE THREAD

**Issue by sochina-heart** [apache/rocketmq#8406]
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq/issues) and [GitHub Discussions](https://github.com/apache/rocketmq/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

centos7 docker

### RocketMQ version

52.0

### Describe the Bug

After boker turns on acl verification, docker compose cannot start proxy and will report an error

### Steps to Reproduce

Docker compose deploys RocketMQ5.2.0 deldger+proxy to deploy cluster, broker turns on acl verification, proxy fails to start and reports an error.
`OpenJDK 64-Bit Server VM warning: Using the DefNew young collector with the CMS collector is deprecated and will likely be removed in a future release
OpenJDK 64-Bit Server VM warning: UseCMSCompactAtFullCollection is deprecated and will likely be removed in a future release.
org.apache.rocketmq.proxy.common.ProxyException: create system broadcast topic DefaultHeartBeatSyncerTopic failed on cluster sochina
        at org.apache.rocketmq.proxy.service.sysmessage.AbstractSystemMessageSyncer.createSysTopic(AbstractSystemMessageSyncer.java:177)
        at org.apache.rocketmq.proxy.service.sysmessage.AbstractSystemMessageSyncer.start(AbstractSystemMessageSyncer.java:143)
        at org.apache.rocketmq.proxy.service.client.ClusterConsumerManager.start(ClusterConsumerManager.java:68)
        at org.apache.rocketmq.common.utils.AbstractStartAndShutdown.start(AbstractStartAndShutdown.java:33)
        at org.apache.rocketmq.common.utils.AbstractStartAndShutdown.start(AbstractStartAndShutdown.java:33)
        at org.apache.rocketmq.common.utils.AbstractStartAndShutdown.start(AbstractStartAndShutdown.java:33)
        at org.apache.rocketmq.proxy.ProxyStartup.main(ProxyStartup.java:96)`
I configured the proxy acl as described on github, but it didn't work. The above error was still reported when I started it.

### What Did You Expect to See?

I want to know how to start the proxy after enabling acl verification when deploying deldger+proxy in rocketmq5.2.0 docker compose.

### What Did You See Instead?

I am using docker compose to deploy a rocketmq5.2.0 cluster, using deldger and proxy, but if the broker turns on acl verification, the proxy cannot start normally.
`OpenJDK 64-Bit Server VM warning: Using the DefNew young collector with the CMS collector is deprecated and will likely be removed in a future release
OpenJDK 64-Bit Server VM warning: UseCMSCompactAtFullCollection is deprecated and will likely be removed in a future release.
org.apache.rocketmq.proxy.common.ProxyException: create system broadcast topic DefaultHeartBeatSyncerTopic failed on cluster sochina
        at org.apache.rocketmq.proxy.service.sysmessage.AbstractSystemMessageSyncer.createSysTopic(AbstractSystemMessageSyncer.java:177)
        at org.apache.rocketmq.proxy.service.sysmessage.AbstractSystemMessageSyncer.start(AbstractSystemMessageSyncer.java:143)
        at org.apache.rocketmq.proxy.service.client.ClusterConsumerManager.start(ClusterConsumerManager.java:68)
        at org.apache.rocketmq.common.utils.AbstractStartAndShutdown.start(AbstractStartAndShutdown.java:33)
        at org.apache.rocketmq.common.utils.AbstractStartAndShutdown.start(AbstractStartAndShutdown.java:33)
        at org.apache.rocketmq.common.utils.AbstractStartAndShutdown.start(AbstractStartAndShutdown.java:33)
        at org.apache.rocketmq.proxy.ProxyStartup.main(ProxyStartup.java:96)`

**Comment by sochina-heart** [comment]
Sorry, the rocketmq version number is wrong, it should be 5.2.0

**Comment by leizhiyuan** [comment]
see this code in proxy

 public static DefaultMessagingProcessor createForClusterMode() {
        RPCHook rpcHook = null;
        if (ConfigurationManager.getProxyConfig().isEnableAclRpcHookForClusterMode()) {
            rpcHook = AclUtils.getAclRPCHook(ROCKETMQ_HOME + MixAll.ACL_CONF_TOOLS_FILE);
        }
        return createForClusterMode(rpcHook);
    }

need open EnableAclRpcHookForClusterMode and put the wrong acl in yaml
