### ISSUE TITLE
初始化Producer时需要设置通信配置以及预绑定的Topic报错

### ISSUE THREAD

**Issue by LKLKenneth** [apache/rocketmq#9031]
### Search before creation

- [X] I had searched in the [issues](https://github.com/apache/rocketmq/issues) and found no similar issues.

### Documentation Related

java 连接         // 初始化Producer时需要设置通信配置以及预绑定的Topic。
        Producer producer = provider.newProducerBuilder()
            .setTopics(topic)
            .setClientConfiguration(configuration)
            .build();  走到这一步报错

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by yx9o** [comment]
能提供具体报错和configuration的信息吗

**Comment by LKLKenneth** [comment]
Exception in thread "main" java.lang.IllegalStateException: Expected the service ProducerImpl-0 [FAILED] to be RUNNING, but the service has FAILED
        at org.apache.rocketmq.shaded.com.google.common.util.concurrent.AbstractService.checkCurrentState(AbstractService.java:381)
        at org.apache.rocketmq.shaded.com.google.common.util.concurrent.AbstractService.awaitRunning(AbstractService.java:305)
        at org.apache.rocketmq.shaded.com.google.common.util.concurrent.AbstractIdleService.awaitRunning(AbstractIdleService.java:165)
        at org.apache.rocketmq.client.java.impl.producer.ProducerBuilderImpl.build(ProducerBuilderImpl.java:93)
        at com.homeinns.rocketmq.producer.PushMessageDemo.main(PushMessageDemo.java:30)

**Comment by qianye1001** [comment]
i guess you do use namesrv endpoint instead of proxy endpoint， rmq grpc client need to connect to proxy

**Comment by lanendiencgr2002** [comment]
我也是这样，后来确定brokerIP1，topic没问题后，试了下初始化消费者创建TestConsumerGroup组手动发个消息没问题，然后再回来就没报错了
